### ISSUE TITLE
Issure about my own experiment

### ISSUE THREAD

**Issue by diaodeyi** [eladrich/pixel2style2pixel#102]
HI ， Thanks for your great work， i made some change in the task of encoding , and now the train process can output the  perfect result(dataset is CelebaHQ-30000), but the output of Validation set and test set  are bad. The experiment images are as follows:
![Selection_009 (1)](https://user-images.githubusercontent.com/48873381/111557841-6c975c80-87c8-11eb-8ebe-85887ffdb30d.png)
![Selection_008 (1)](https://user-images.githubusercontent.com/48873381/111557851-75882e00-87c8-11eb-843a-81c5b3063e0b.png)
the bottom one is train result(about 255500 steps) ,the upper  one is the val result(about 255500 steps)
I don't think  it's overfit, because if i set the val and train is same , the result seems same

**Comment by yuval-alaluf** [comment]
Hi @diaodeyi 
I agree that something a bit strange is going on. Can you please provide details regarding the hyperparameters you chose?

**Comment by diaodeyi** [comment]
sure，"batch_size": 2,
"board_interval": 50,
"checkpoint_path": null,
"dataset_type": "ffhq_encode",
"encoder_type": "GradualStyleEncoder",
"exp_dir": "./outputs_encoding_M",
"id_lambda": 0.1,
"image_interval": 100,
"input_nc": 3,
"input_nc_1": 19,
"l2_lambda": 1.0,
"l2_lambda_crop": 0,
"label_nc": 0,
"learn_in_w": false,
"learning_rate": 0.0001,
"lpips_lambda": 0.8,
"lpips_lambda_crop": 0,
"max_steps": 500000,
"optim_name": "ranger",
"resize_factors": null,
"save_interval": 5000,
"start_from_latent_avg": true,
"stylegan_weights": "pretrained_models/stylegan2-ffhq-config-f.pt",
"test_batch_size": 8,
"test_workers": 8,
"train_decoder": false,
"val_interval": 2500,
"w_norm_lambda": 0,
"workers": 8

**Comment by diaodeyi** [comment]
I add the celebaHQ mask together with the image as the input in the encoding task.

**Comment by yuval-alaluf** [comment]
If I understand correctly, the input to the encoder is now 22 channels (3 RGB and 19 for the mask)?  
In any case, I think a potential issue could be the small batch size use or training. 
In addition, the `lpips_lambda` weight is high for your batch size. In our work, we used a batch size of `8` with a weight of `0.8` (i.e., a weight of 0.1 per sample). Therefore, you should also try adjusting your lpips lambda weight according to your batch size (in this case it would be `2 * 0.1 = 0.2`. 
Did you try training the encoding task using only RGB images (without the masks) using the Celeb data to verify that you are successful in training the encoding task using your hyperparameters?

**Comment by diaodeyi** [comment]
Yes, thanks a lot. 
My GPU is TITAN 12GB, And In my experiment , the batchsize can only be set to a maximum of 2, otherwise it will run out of memory;
And i will try the lpips_lambda setting;
No , although the stylegan is pretrained on FFHQ, i think PSP has strong generalization. And you can see the training result is perfect, but i will try it  , thank you a lot .

**Comment by diaodeyi** [comment]
By the way, about the batchsize , I think my experiment somewhere must be wrong . Because i can run the 8 in your origin experiment both mask and encoding . After adding the mask , the  maximum only be 2.

**Comment by diaodeyi** [comment]
Hi，i make some change as you advicing , Now the result seems better , but the color of the validation changes as the training process, and i don't konw how to adjust parameter further，And meanwhile i set the l2_lambda to 0.4 because  when set it to 1, the result seems cartoonlization.Here are the validation result of 100000，90000，80000steps
![Selection_010](https://user-images.githubusercontent.com/48873381/111873943-ca48c600-89cd-11eb-9f9f-bc5d73c2e4da.png)
![Selection_011](https://user-images.githubusercontent.com/48873381/111873945-cb79f300-89cd-11eb-9390-78d10cfa9df6.png)
![Selection_012](https://user-images.githubusercontent.com/48873381/111873950-ccab2000-89cd-11eb-8cae-b49df2b7bc49.png)

**Comment by diaodeyi** [comment]
I mean i want the color same as the  input

**Comment by yuval-alaluf** [comment]
> Now the result seems better , but the color of the validation changes as the training process, and i don't konw how to adjust parameter further

I don't think the reasoning for the poor color is because of the loss weight. 
If I remember correctly, you are inputting a 22-channel input to your encoder (3 for the RGB image and 19 for the mask). I suspect that the 19 channels for the mask result in the encoder practically ignoring the RGB channels resulting in the poor reconstruction you're seeing. That is, the imbalance between the 19 mask channels and 3 RGB channels may be the problem.
I feel like this is the reasoning for your results because this is the color-style of outputs you'd expect to see in our segmentation-to-image task. 
This is just a hunch and I may be mistaken as I don't know exactly what you're trying to solve.
