### ISSUE TITLE
Any support for Stylegan2-ada-pytorch?

### ISSUE THREAD

**Issue by JulianPinzaru** [eladrich/pixel2style2pixel#104]
It turns out there is no way yet to use models that you get as a final result when using pytorch. 
Although NVlabs still generate pkl files in their stylegan2-ada-pytorch, it throws errors/exceptions when trying to load that one into psp training.
Is there any chance to fix that thing ?
Any feedback is highly appreciated.
Thanks

**Comment by yuval-alaluf** [comment]
Please see my comment in the following issue: 
https://github.com/eladrich/pixel2style2pixel/issues/24#issuecomment-789840789
Adding support for NVIDIA's pytorch version of StyleGAN-ADA is not a quick fix, but more of a major design change.
With that, as I wrote in the linked issue, adding support for NVIDIA's version should be possible. We invite you to try it out and let us know if you're able to get it working

**Comment by justinpinkney** [comment]
A quick fix might be to use this notebook I put together to convert weights fomm stylegan-ada-pytorch format to rosinality's format (used in psp). Link in this tweet:
https://twitter.com/Buntworthy/status/1372118922019880960?s=19

It's a bit messy and you have to make sure you get the right values for channel multiplier and mapping layers etc. But it should work. Let me know if you have any troubles though.

**Comment by yuval-alaluf** [comment]
Looks really good. @justinpinkney. Would you want to organize it a bit in a pull request to the repo? I think this could be of interest to a lot of people.

**Comment by markemus** [comment]
@justinpinkney I would use this as well- I'm the author of the previous issue #24 .

Personally I just retrained using rosinality's code, it was easier than trying to refactor p2sp2.

**Comment by JulianPinzaru** [comment]
@justinpinkney  That's awesome!!! Thanks man! I will give it a try as soon as I can!

**Comment by justinpinkney** [comment]
@yuval-alaluf I've actually just created a PR to get the conversion tool into what (as far as I'm aware) is the best maintained community fork of the stylegan2-ada-pytorch repo: https://github.com/dvschultz/stylegan2-ada-pytorch/pull/4

I think it makes sense in the steylgan2-ada-pytorch repo as it depends on the Nvidia libraries to load the .pkl files, but exports a plain old dict so has no actual dependency on the rosinality code.

**Comment by yuval-alaluf** [comment]
> @yuval-alaluf I've actually just created a PR to get the conversion tool into what (as far as I'm aware) is the best maintained community fork of the stylegan2-ada-pytorch repo: [dvschultz/stylegan2-ada-pytorch#4](https://github.com/dvschultz/stylegan2-ada-pytorch/pull/4)
> 
> I think it makes sense in the steylgan2-ada-pytorch repo as it depends on the Nvidia libraries to load the .pkl files, but exports a plain old dict so has no actual dependency on the rosinality code.

Makes sense.  
I'll be sure to keep an eye on your merge request. Hopefully it gets accepted soon and I'll add a link in this repo to your script. 
For now I'll close this issue as I think your notebook and script solve the issue for now.
