### ISSUE TITLE
Question about the LPIPS loss

### ISSUE THREAD

**Issue by zhongzyd** [eladrich/pixel2style2pixel#108]
Hi~
You used ALEX LPIPS loss, had you try VGG LPIPS? Because StyleGAN use VGG LPIPS.
In the paper, you refered "Collaborative Learning for Faster StyleGAN Embedding" for the LPIPS loss. But they didn't public their code. I am wondering whether they use ALEX or VGG.

**Comment by yuval-alaluf** [comment]
We didn't try the VGG LPIPS, but I don't think you will see much of a difference. 
If I remember correctly, I have seen more works using the AlexNet-based variant. According to the official LPIPS implementation (https://github.com/richzhang/PerceptualSimilarity), they write that the AlexNet-based version provides "best forward scores" while the VGG-based version is "closer to traditional perceptual loss, when used for optimization". 

I also checked the Collaborative paper to see which version they used and it seems like they do not specify.

**Comment by zhongzyd** [comment]
I have done some search, but I didn't find other works that use AlexNet-based LPIPS for optimization. 
Could you provide some works that use AlexNet-based LPIPS for optimization?
Thanks!

**Comment by yuval-alaluf** [comment]
I meant to say that I believe AlexNet is typically used for encoder-based techniques. I believe optimization methods typically use VGG. But again, I dont think you will see much difference between the two. Perhaps the original LPIPS paper could provide insights as to when it is preferable to use one or the other.

**Comment by zhongzyd** [comment]
Thank you for the helpful discussion!
