### ISSUE TITLE
how I get output of encoder ? W=dlatens or called W+

### ISSUE THREAD

**Issue by Johnson-yue** [eladrich/pixel2style2pixel#11]
in the funtion of run_on_batch().  it only inversion image and generated fake image but not have output of  image

if I want the dlatens (or W+) in FFHQ model , how I get ?

**Comment by eladrich** [comment]
Hi @Johnson-yue, you can take a look at the arguments for the pSp forward pass
https://github.com/eladrich/pixel2style2pixel/blob/master/models/psp.py#L66 
Specifically in your case, simply setting `return_latents=True` will make the function return a tuple of both the images and latents
```python
images, result_latents = net(...,return_latents=True) 
```

**Comment by Johnson-yue** [comment]
thank you, I got it
