### ISSUE TITLE
A question about trainning duration

### ISSUE THREAD

**Issue by annihi1ation** [eladrich/pixel2style2pixel#110]
Hey, guys,
Thanks for your magnificent work!
You said you train your model only on a P40 GPU. However, when I use the V100 from Colab, it said that I have to run more than 1 month to finish training.
I wonder if there is any thing wrong in my work.

**Comment by yuval-alaluf** [comment]
Hi @annihi1ation ,
I am not sure how Colab estimates how long training will take, but we trained for approximately one week on a P40 GPU. Note also that although the `max_steps` is set to `500,000` by default, our model converged much sooner than that.

**Comment by annihi1ation** [comment]
Thanks for replying so quickly!

I am sorry for misunderstanding your code. The **global_step** increases 1 after every BATCH done, while I thought it increases every EPOCH for the data loader done.

So it is my fault to rewrite your code wrongly 😁
