### ISSUE TITLE
Resolving wget (wget)... failed: Name or service not known. | wget: unable to resolve host address ‘wget’

### ISSUE THREAD

**Issue by LAW-1337** [eladrich/pixel2style2pixel#111]
Hi, as usual on "colab" I execute line by line, and at "**Step 2: Download Pretrained Models**", I have this error, I have only 3.1K downloaded, the 1G of the google doc are not downloaded

```
--2021-04-01 22:11:03--  http://wget/
Resolving wget (wget)... failed: Name or service not known.
wget: unable to resolve host address ‘wget’
--2021-04-01 22:11:04--  https://docs.google.com/uc?export=download&confirm=&id=1VpEKc6E6yG3xhYuZ0cq8D2_1CbT0Dstz
Resolving docs.google.com (docs.google.com)... 172.217.164.142, 2607:f8b0:4004:80a::200e
Connecting to docs.google.com (docs.google.com)|172.217.164.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/content/pixel2style2pixel/pretrained_models/psp_celebs_seg_to_face.pt’

/content/pixel2styl     [ <=>                ]   3.05K  --.-KB/s    in 0s      

2021-04-01 22:11:04 (48.6 MB/s) - ‘/content/pixel2style2pixel/pretrained_models/psp_celebs_seg_to_face.pt’ saved [3127]

FINISHED --2021-04-01 22:11:04--
Total wall clock time: 0.1s
Downloaded: 1 files, 3.1K in 0s (48.6 MB/s)
```

Best Regards.

**Comment by yuval-alaluf** [comment]
This typically occurs when you are unable to successfully fetch from Google Drive because the quota was exceeded. There is a check in the notebook that validates this. Please notice the comment we wrote: 

>We need to verify that the model was downloaded correctly. All of our models should weigh approximately 1.12GB.  
>Note that if the file weighs several KBs, you most likely encounter a "quota exceeded" error from Google Drive. In that case, you should try downloading the model again after a few hours.

**Comment by LAW-1337** [comment]
Okay, that's what I thought. Thanks for the quick answer.
