### ISSUE TITLE
About the frontalization application

### ISSUE THREAD

**Issue by duongquangvinh** [eladrich/pixel2style2pixel#112]
Dear sir,

I need some advice from you for my target FFHQ data.
Initially, My target data is FFHQ that is all asian woman faces with no glasses, no makeup (I filtered it by myself from FFHQ dataset). However, my source data is all front synthetic faces. Therefore, I think I will use your frontalization application in my target FFHQ to frontalize all faces. But I see that after using your pretrained_model on my target FFHQ, all the faces seem to be older even the young (the eyes have many wrinkles).
![01364](https://user-images.githubusercontent.com/59604464/113663800-de323e80-96d4-11eb-9e4f-9be65c9fab9d.jpg)
![01313](https://user-images.githubusercontent.com/59604464/113663824-ea1e0080-96d4-11eb-9292-5ed0de7af405.jpg)
![01309](https://user-images.githubusercontent.com/59604464/113663856-f5712c00-96d4-11eb-802c-a09abc63f3b0.jpg)

So I decided to train a frontalization model with my filtered FFHQ dataset (only contain 1549 images). Because the training time is long, so I think I need your advice before training.

+ Do you think this idea is good? Should I keep all default hyper-parameters in source code or change it? I see that the results using given pre-trained model seems to be not too shaped.
+ All my target FFHQ data is Asian woman, and I want all outputs should be similar to Asian, not a little bit like other races like above images. Do you think this train will improve it?
+ My ffhq data is converted into JPEG format (origin is PNG). I do not know that does this affect inference much?

Thank you, sir.
Best regards.

**Comment by yuval-alaluf** [comment]
Hi @duongquangvinh ,
1. It seems like you want to train frontalization on a small subset of FFHQ. Since you have a small training set, I am unsure how the resulting model will look if trained for scratch. Maybe you will want to continue training from the pre-trained pSp model on your subset? 
2. Maybe training only on subset will help, but it's difficult to say without trying.
3. Should be fine with JPEG.

**Comment by duongquangvinh** [comment]
Oh it is so happy to see your reply, sir.
I will try to retrain and report my results to you after 500,000 iterations. Thank you sir.

**Comment by yuval-alaluf** [comment]
Cool. Please note that for the face frontalization task, we trained for only 80,000 iterations. The model may converge even before that
