### ISSUE TITLE
a way to keep the fidelity

### ISSUE THREAD

**Issue by reason4** [eladrich/pixel2style2pixel#115]
Thanks for releasing your excellcent work! 

I've trained the model and get the expected results as showed below.
![98500](https://user-images.githubusercontent.com/25290238/113992374-fac1a880-9885-11eb-834f-b5c765b40249.jpg)

As we can see, the degraded image can recover very well. But as the paper mentioned, the faces which are not close to frontal can not recover well. It can be seen from the belowing image.
![96300](https://user-images.githubusercontent.com/25290238/113993354-f9dd4680-9886-11eb-9e3c-a3c1035c4bbb.jpg)

The background is also changed. To solve the problem, I implemented the methods introduced in the paper based on pSp framework: [https://xinntao.github.io/projects/gfpgan](url). Its key model is the channel-split spatial feature transform layers.
Some results are good:
![45000_face](https://user-images.githubusercontent.com/25290238/113996587-e54e7d80-9889-11eb-8752-5b6e0e328594.jpg)
The fidelity is good, however, the realness is sometimes bad, especially the teeth and hair.

![image](https://user-images.githubusercontent.com/25290238/113997283-90f7cd80-988a-11eb-83f3-67f0d1518f3a.png)
![image](https://user-images.githubusercontent.com/25290238/113999298-80485700-988c-11eb-875a-010728222b2e.png)

I think the reason is there exist problems in my implementation, but I do not know how to solve it. 

Do you have tried the paper I mentioned?  And  could you please provide some advice to improve it? Thanks!

**Comment by yuval-alaluf** [comment]
We have not tried to implement the paper you linked (it seems like there is no released code even). Therefore, we cannot know if there is a problem in your implementation. 

Overall, the results you obtained are quite impressive in my opinion. Regarding your artifacts, you may want to consider adding a very small weight to the `w_norm` loss (e.g., 0.001). This will push the inversions closer to the average latent code and hopefully help mitigate these artifacts. However, adding this loss may affect the identity preservation of the reconstructed images so note that there is a trade-off here.

**Comment by reason4** [comment]
> We have not tried to implement the paper you linked (it seems like there is no released code even). Therefore, we cannot know if there is a problem in your implementation.
> 
> Overall, the results you obtained are quite impressive in my opinion. Regarding your artifacts, you may want to consider adding a very small weight to the `w_norm` loss (e.g., 0.001). This will push the inversions closer to the average latent code and hopefully help mitigate these artifacts. However, adding this loss may affect the identity preservation of the reconstructed images so note that there is a trade-off here.

Thanks for your advice！I'll try the 'w_norm' loss.
