### ISSUE TITLE
Question about EqualLinear

### ISSUE THREAD

**Issue by diaodeyi** [eladrich/pixel2style2pixel#117]
Hi , Is there any reason for using EqualLinear in styleganV2 instead of default ordinary linear layer?

**Comment by yuval-alaluf** [comment]
The two are very similar and EqualLinear uses the regular Linear layer with some more wrappers. If you want more details this question is best asked in a repository that implemented StyleGAN2, we simply used an existing implementation.

**Comment by diaodeyi** [comment]
thank you
