### ISSUE TITLE
Colab notebook is extremely well-written

### ISSUE THREAD

**Issue by Tylersuard** [eladrich/pixel2style2pixel#120]
This is not an issue.  I just wanted to remark that I have never seen a better-structured Colab notebook.  The code is easily understandable, but also skippable using dropdown boxes and by selecting one line over the other.  Usable by both beginners and experts easily.  Thank you.

**Comment by eladrich** [comment]
Thanks @Tylersuard! 😁 Usability was what we were aiming for when building the colab, so it's really satisfying to hear that we got it right. 

Thanks for taking the time to tell us about your experience, appreciated!

**Comment by signorettif** [comment]
I 100% second this

**Comment by genekogan** [comment]
And you respond to every last question in the issue tracker! A+ 👍

**Comment by duongquangvinh** [comment]
Hope you guys receive more recognition from CVPR
