### ISSUE TITLE
style_mixing

### ISSUE THREAD

**Issue by mzprose** [eladrich/pixel2style2pixel#121]
Hello, I try to input two pictures in the style_mixing operation, input them into psp, get two corresponding latent codes, and then send them as input to psp for reconstruction, I hope to get a fusion image of the two images, But the output is irrelevant pictures, I don't understand a bit, the code is as follows:

`_, latent_to_inject = net(input_image,
						 input_code=False,
						 return_latents=True)
`
`
_, latent_to_inject1 = net(input_image1,
						input_code=False,
					        return_latents=True)
`
`
res = net(latent_to_inject,
		latent_mask=latent_mask,
		input_code = True,
		inject_latent=latent_to_inject1,
		return_latents=True,
		alpha=opts.mix_alpha,
		resize=opts.resize_outputs)`

**Comment by mzprose** [comment]
I have solved it, thanks

**Comment by vishnukool** [comment]
Hi @mzprose 
How did you go about solving it ? Would love if you could share your solution ! 😄

**Comment by mzprose** [comment]
I simply input the two input images into the psp forward function, then get their corresponding latent code, and finally style mixing the two vectors, and then decode them to get the output.The theme modification code is as follows:
In style_mixing.py
`
_, latent_to_inject = net.forward1(input_image,
										  input_code=False,
										  return_latents=True)
				# print(latent_to_inject)
				_, latent_to_inject1 = net.forward1(input_image1,
										  input_code=False,
										  return_latents=True)
# get output image with injected style vector
				res,latent_to_inject2 = net.forward(latent_to_inject,
						  latent_mask=latent_mask,
						  input_code = True,
						  # randomize_noise=False,
						  inject_latent=latent_to_inject1,
						  return_latents=True,
						  alpha=opts.mix_alpha,
						  resize=opts.resize_outputs)`

**Comment by vishnukool** [comment]
Thank you 🙏
