### ISSUE TITLE
running Inference.py  on win10 ltsc

### ISSUE THREAD

**Issue by vbqgyy** [eladrich/pixel2style2pixel#123]
![error01](https://user-images.githubusercontent.com/22383994/115944173-c46f6480-a4e6-11eb-9d67-6507932d29ff.jpg)

win10
GTX3090
CUDA11.1
torch 1.8.1

_libgcc_mutex             0.1                        main    defaults
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py36h9f0ad1d_0    conda-forge
cycler                    0.10.0                    <pip>
dataclasses               0.8                       <pip>
kiwisolver                1.3.1                     <pip>
libffi                    3.2.1             ha925a31_1007    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.2.1                     <pip>
msys2-conda-epoch         20160418                      1    conda-forge
ninja                     1.10.0           py36h7ef1ec2_0    
numpy                     1.18.4                    <pip>
opencv-python             4.2.0.34                  <pip>
openssl                   1.1.1g               he774522_1    
Pillow                    7.1.2                     <pip>
pip                       20.0.2                    <pip>
pip                       21.0.1                    <pip>
pip                       20.0.2                   py36_3    defaults
pyparsing                 2.4.7                     <pip>
pyreadline                2.1             py36ha15d459_1003    conda-forge
python                    3.6.7           he025d50_1008_cpython    conda-forge
python-dateutil           2.8.1                     <pip>
python_abi                3.6                     1_cp36m    conda-forge
scipy                     1.4.1                     <pip>
setuptools                46.4.0                   py36_0    defaults
setuptools                46.4.0                    <pip>
six                       1.15.0                    <pip>
sqlite                    3.31.1               h2a8f88b_1    defaults
tk                        8.6.8             hfa6e2cd_1000    conda-forge
torch                     1.8.1+cu111               <pip>
torchvision               0.9.1+cu111               <pip>
tqdm                      4.46.0                    <pip>
typing-extensions         3.7.4.3                   <pip>
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wheel                     0.34.2                   py36_0    conda-forge
wincertstore              0.2             py36ha15d459_1006    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge

**Comment by yuval-alaluf** [comment]
Have you looked at the other issues related to compiling ninja on windows?  Also, I would recommend trying running with conda environment as this typically resolves most issues. 
You can check out a similar issue here: https://github.com/eladrich/pixel2style2pixel/issues/29

**Comment by vbqgyy** [comment]
Thank you for your reply. I read almost all the relevant content. Then I tried stylegan2-pytorch and it worked well. I have tried this project many times. I will continue to try this. Is a very interesting project. thank you very much .

**Comment by yuval-alaluf** [comment]
I see. If you were able to get stylegan2-pytorch to work on your system, you should be able to get pSp to work as well. You should try seeing how to compile ninja for CUDA 11.

**Comment by vbqgyy** [comment]
I'm trying. Fortunately, I succeeded once, and then I kept failing. Then I deleted the. Lock file and tried again, showing the same error. But I think I'm going to make it. I am grateful for your help.
