### ISSUE TITLE
I want to use psp to make the paired image translation. Which pre-training model should I download?

### ISSUE THREAD

**Issue by zjy9779** [eladrich/pixel2style2pixel#124]

**Comment by yuval-alaluf** [comment]
This depends on what kind of translation you want to perform. There may not be a pre-trained model that is relevant for you and you may need to train from scratch.

**Comment by zjy9779** [comment]
Traceback (most recent call last):
  File "scripts/train.py", line 32, in <module>
    main()
  File "scripts/train.py", line 27, in main
    coach = Coach(opts)
  File "./training/coach.py", line 32, in __init__
    self.net = pSp(self.opts).to(self.device)
  File "./models/psp.py", line 34, in __init__
    self.load_weights()
  File "./models/psp.py", line 63, in load_weights
    self.decoder.load_state_dict(ckpt['g_ema'], strict=False)
KeyError: 'g_ema'

Thank you.I dont't need ID loss because I have conditional images.   I try to use moco pretrained model, but I got this error.

**Comment by yuval-alaluf** [comment]
The error you got is not related to the losses. It seems like your checkpoint to the decoder is invalid. Please make sure it is in the correct format.

**Comment by necococo** [comment]
I want to use paired HR-LR images for super resolution, how do I train them?

**Comment by yuval-alaluf** [comment]
Hi @necococo 
Please take a look at the Readme. We provide a lot of details on how to prepare your data, model paths, and transforms for training custom tasks. If something specific is not clear I will be happy to help.
