### ISSUE TITLE
Using inference for own images problem

### ISSUE THREAD

**Issue by gardiiinc** [eladrich/pixel2style2pixel#13]
Hi @eladrich. Thanks for sharing.
I would like to try inference with own srcs , but maybe i am to stupid or it is not made for.
Am i right,that for input there is an folder which parameter is:
--data_path
this points to folder where my input images are (more than one?)

output folder is:
-exp_dir

i tried with input_img.jpg in folder:
python inference.py --checkpoint_path ../pretrained_models/psp_celebs_super_resolution.pt --exp_dir ../../out --data_path ../../in/ --resize_factors 2 --test_batch_size 2

Loading pSp from checkpoint: ../pretrained_models/psp_celebs_super_resolution.pt
Loading dataset for celebs_super_resolution
Performing down-sampling with factors: [2]
0it [00:00, ?it/s]
/.../anaconda3/envs/pixel2style2pixel/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/.../anaconda3/envs/pixel2style2pixel/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/.../anaconda3/envs/pixel2style2pixel/lib/python3.6/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/.../anaconda3/envs/pixel2style2pixel/lib/python3.6/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/.../anaconda3/envs/pixel2style2pixel/lib/python3.6/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Runtime nan+-nan

Thanks

**Comment by 7khalil** [comment]
I'm also facing the same **ERROR**.

**Comment by yuval-alaluf** [comment]
Hi @gardiiinc ,
I don't see a problem with the command you're trying to run.  
Do you by any chance have only one image in the provided `data_path`? Try running the script where `test_batch_size` is less than or equal to the size of the dataset you are performing inference on.  
If I had to guess, your getting the error here
https://github.com/eladrich/pixel2style2pixel/blob/ac7da535f0dfb88a55666baeba8f0d83827db5ec/scripts/inference.py#L103
where you're trying to take the mean of `global_time` which would be an empty list if your batch size is greater than your dataset. 
Let me know if the issue continues

**Comment by yuval-alaluf** [comment]
@7khalil 
As for your comment, can you please provide more details as to what error you're receiving?  

Also, please check that you were able to successfully download the model from google drive? You may have obtained a "quota exceeded" error due to too many downloads. We are aware of this issue and exploring various solutions to this.  

If this is not the issue, please provide the error you received and we'll look into it!

**Comment by 7khalil** [comment]
Hi @yuval-alaluf,

First Thank you for the response.

I have solved the issue, by providing more images into test_data folder (number of images should be greater than test_batch_size) as you said.

But now i got new error : 
input : 

!python scripts/inference.py \
--exp_dir=./experiment/exp \
--checkpoint_path=./experiment/ckpt/psp_ffhq_encode.pt \
--data_path=./experiment/test_data \
--test_batch_size=4 \
--test_workers=4 \
--couple_outputs


output : 
Loading pSp from checkpoint: ./experiment/ckpt/psp_ffhq_encode.pt
Loading dataset for ffhq_encode
  0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/inference.py", line 133, in <module>
    run()
  File "scripts/inference.py", line 69, in run
    if global_i > opts.n_images:
TypeError: '>' not supported between instances of 'int' and 'NoneType'

**Comment by yuval-alaluf** [comment]
Hi @7khalil , 
I just noticed the issue myself and fixed the issue in the latest commit to master an hour ago :) 
Apologies for the confusion.  Let me know if the issue is fixed

**Comment by 7khalil** [comment]
Yes, everything works fine now, thanks @yuval-alaluf.
