### ISSUE TITLE
About dataset for training/testing

### ISSUE THREAD

**Issue by markduon** [eladrich/pixel2style2pixel#134]
Hi sir,

I do not know that the train set and test set can be the same or different in training GANs? Thank you, sir.

**Comment by yuval-alaluf** [comment]
The train set and test set can be whatever you want :smile: 
For inversion, we trained on FFHQ which is typically done. The evaluation was performed on the CelebA-HQ dataset which gave us an independent dataset to evaluate our model.

**Comment by duongquangvinh** [comment]
Oh that means the source_train and source test can be the same (just duplicate source train and rename it "source test")? I usually see that the train and test set must be different in machine learning.

**Comment by duongquangvinh** [comment]
oh thank you sir! That is so nice to receive your reply so soon
