### ISSUE TITLE
Pretrained Model for 256x256 StyleGAN Inversion

### ISSUE THREAD

**Issue by csyxwei** [eladrich/pixel2style2pixel#135]
Hi, thanks for the awesome work.

I found that the code is updated to support training StyleGANs of different resolutions, and I was wondering if there is a checkpoint for 256x256 StyleGAN Inversion.

Thank you very much!

**Comment by li-car-fei** [comment]
> Ok, thank you.

did you get a chance to train the 256x256 model ?
