### ISSUE TITLE
save latent and later generate image from it

### ISSUE THREAD

**Issue by MaskeZen** [eladrich/pixel2style2pixel#136]
Hello, first of all, good work!
I'm experiment with this encoder, I can save a latent space from a image, but if I save the latent space and later I try to regenerate the image I don't get the same result that I get with the encoder function.

```py
# I get the result_latent (this work fine)
result_image, result_latent = data_utils.run_on_batch(input_image_transform.unsqueeze(0), net, latent_mask)

# I use this code to save the latent (may be I do something wrong here...)
torch_one = result_latent[0]
                numpy_array = torch_one.cpu().data.numpy()
                numpy_array = np.array([numpy_array])
                latent_file_output = "output/"+latent_file_name+".pkl"
                with open(latent_file_output, 'wb') as out_file:
                    pickle.dump(numpy_array, out_file)

# And then with the latent... I invoke this function, but the result is not the same that with the encoder
def image_from_latent(latent_code):
        decoder = Generator(1024, 512, 8)

        result_image = decoder([latent_code], 
            input_is_latent=True,
            randomize_noise=False,
            return_latents=False)

        output_image = tensor2im(result_image[0])

        res = np.array(output_image.resize((256, 256)))
        res_image = Image.fromarray(res)
        return res_image
```

**Comment by duongquangvinh** [comment]
Hi sir!
Could you show me where you put this code block in this repo?

**Comment by MaskeZen** [comment]
Sorry, I make a Frankenstain from your playground, and lost the perspective that it is far a way from the original.
The first line use a function like in the `Step 6: Perform Inference`, and return the result_image, result_latent, then I save the latent, and I can experiment a little with this latent space in [other project](https://github.com/AmarSaini/Epoching_StyleGan2_Setup), but there use tensorflow to generate the image from the latent space.

I try to generate the image from the latent space using this base code, but I am missing something.

I maked the function `image_from_latent(latent_code)` based in the procedure on `models/psp.py`, but I dont understand a lot of things.

**Comment by yuval-alaluf** [comment]
Hi @MaskeZen 
I skimmed through your code and it seems fine so I'm curious why you're getting different results. Do you want to show me an example of the differences?

**Comment by MaskeZen** [comment]
Is funny... this is the stranger guy

![cb00008](https://user-images.githubusercontent.com/13751832/118072852-10445980-b381-11eb-9740-dfb5ad2db337.jpeg)
![flask_latent_to_image_eaac8a08-f3cc-4294-ab60-2d22e5ec959e](https://user-images.githubusercontent.com/13751832/118072845-0e7a9600-b381-11eb-86a0-069c728dbf13.jpg)

but I see that this is when I load the pretrained model "net_ffhq_encode", and the value "input_is_latent" is false, using "models/psp.py", if I change in this file to test the line 92 `input_is_latent=input_is_latent` to `input_is_latent=input_code` the output is the desired.

I go to fix my code, I tell you if I get the trick, thanks for the reply!
