### ISSUE TITLE
No instructions on how to train an inpainting model

### ISSUE THREAD

**Issue by styler00dollar** [eladrich/pixel2style2pixel#14]
pSp Encoder, Frontalization, Sketch to Face, Segmentation Map to Face and Super Resolution do have instructions, but there are none for inpainting. Would it be possible to add instructions to the readme? And I assume there is no mask related code, since I can't find code related to that. How are masks supposed to be used or needs this to be implemented?

**Comment by eladrich** [comment]
Hi @styler00dollar, thank you for your interest! 

The current code release does not support the inpainting application, see issue #1 for more details.

**Comment by styler00dollar** [comment]
Are there plans to release such code?

**Comment by eladrich** [comment]
Not at the moment, but we encourage you to try and train one yourself using our framework and would be happy to share it
