### ISSUE TITLE
Human Skin Tone

### ISSUE THREAD

**Issue by BASSG7** [eladrich/pixel2style2pixel#141]
Hi, I finally Have a good result

![66BCEAEB-6550-4508-9425-366A324C56B5](https://user-images.githubusercontent.com/84246303/118375906-0f036e80-b5c5-11eb-8693-aa3b7f5ee0b8.jpeg)

and I just want to know how can I give this image a human skin tone

I don’t have photoshop and I hope if a Colab exist for this kind of things 

Thansk per advance, sorry for bad English 🙏

**Comment by yuval-alaluf** [comment]
Hi @BASSG7 , 
You can change the skin tone of the resulting image by performing style mixing with other latent codes. While in our paper we only used style mixing for the conditional image synthesis task, this should be relevant for what you are trying to do. You can check out the following section in the README for more details: 
https://github.com/eladrich/pixel2style2pixel#multi-modal-synthesis-with-style-mixing

**Comment by BASSG7** [comment]
Ho okay I see, thanks for response @yuval-alaluf  but where am I suppose to paste the Style-Mixing Script in the Colab ?

**Comment by yuval-alaluf** [comment]
In the colab we provide a small demo of the style mixing. Please note that some adjustments will be needed to get it to work on your image, but the core flow is there for you.
