### ISSUE TITLE
training of stylegan with much larger resolution

### ISSUE THREAD

**Issue by necococo** [eladrich/pixel2style2pixel#143]
I would like to train on data with a much larger resolution than 1024^2. (4096^2 or 2528^2).
Then I need to train the stylegan2 model by myself with the size I want, right?
In that case, which codes in this repository can I use to train stylegan2?

**Comment by yuval-alaluf** [comment]
Yes. You need to train a StyleGAN2 or StyleGAN-ADA generator with the desired size. There are a few options we support: 
1. Using NVIDIA's StyleGAN2 / StyleGAN-ADA TensorFlow implementation.  
   You can then convert the TensorFlow `.pkl` checkpoints to the supported format using the conversion script found in [rosinality's implementation](https://github.com/rosinality/stylegan2-pytorch#convert-weight-from-official-checkpoints).
2. Using NVIDIA's StyleGAN-ADA PyTorch implementation.  
   You can then convert the PyTorch `.pkl` checkpoints to the supported format using the conversion script created by [Justin Pinkney](https://github.com/justinpinkney) found in [dvschultz's fork](https://github.com/dvschultz/stylegan2-ada-pytorch/blob/main/SG2_ADA_PT_to_Rosinality.ipynb).  
      Please note that the conversion script does **not** save the average latent code that is needed for pSp. However, please see the following issue for details on the changes that can be made to save the average code: [converting stylegan-ada-pytorch to rosinality](https://github.com/yuval-alaluf/restyle-encoder/issues/1)

**Comment by dvschultz** [comment]
I’ve added to latent average to exports now, so it should just work out of the box.
