### ISSUE TITLE
Encountered a particularly strange problem，run  scripts/inference.py   Nothing happens

### ISSUE THREAD

**Issue by zhanghongyong123456** [eladrich/pixel2style2pixel#146]
![image](https://user-images.githubusercontent.com/48466610/120054745-52011f80-c064-11eb-994b-07ec21ccfe35.png)
I found the problem here,
![image](https://user-images.githubusercontent.com/48466610/120054759-7b21b000-c064-11eb-8bb3-4f19f3dda7b4.png)
And then tracking is the problem here
![image](https://user-images.githubusercontent.com/48466610/120054802-bfad4b80-c064-11eb-89df-7f0c2bd1f47a.png)

I don't know what to do，Hope to give some suggestions

**Comment by yuval-alaluf** [comment]
I have a hunch of what the problem is. 
Can you please try running the script, then pressing ctrl+c to stop the execution (or the stop command in Pycharm), and send the stack trace?
