### ISSUE TITLE
TINYYY issue with the colab notebook

### ISSUE THREAD

**Issue by ayunami2000** [eladrich/pixel2style2pixel#147]
![image](https://user-images.githubusercontent.com/24785136/120128139-56762700-c18f-11eb-931b-d8f648e1e804.png)
It runs `wget wget <urls>`

fix would be to make it be: `!{download_command}` instead of `!wget {download_command}`

**Comment by yuval-alaluf** [comment]
Thanks! Should be fixed now :)
