### ISSUE TITLE
Some slight differences about "op" , compared with stylegan-v2-pytorch repo

### ISSUE THREAD

**Issue by insomnia250** [eladrich/pixel2style2pixel#149]
Thanks for sharing the amazing work! 
I noticed that there are slight differences in  stylegan's op (./models/stylegan2/op)  compared with the referenced stylegan-v2-pytorch repo. 
For example, in `FusedLeakyReLUFunctionBackward`, [this repo](https://github.com/eladrich/pixel2style2pixel/blob/master/models/stylegan2/op/fused_act.py#L20) and [stylegan2](https://github.com/rosinality/stylegan2-pytorch/blob/master/op/fused_act.py#L20) are different in handling  bias and tensor contiguous. (just name few here)
I am wondering if these differences in ops will lead to different behaviour when loading pretrained generator from stylegan2-repo? Thank you!

**Comment by yuval-alaluf** [comment]
It seems like rosinality made some small changes in the `FusedLeakyReLU` implementation after we published our code here. This would explain the differences.

These changes should not lead to any changes when loading the pre-trained generator in my opinion. I have been able to load models pre-trained from rosinality's repo, NVIDIA's tensorflow repo, and NVIDIA's pytorch repo, all with no problem and they each define these classes differently. 

If you do find issues with this however, please let me know and we'll investigate it further!

**Comment by insomnia250** [comment]
Yeah I got it! Thanks again!
