### ISSUE TITLE
Computing Metrics

### ISSUE THREAD

**Issue by duongquangvinh** [eladrich/pixel2style2pixel#151]
Hi sir!

I see that you give us 3 scripts to compute id loss, LPIPS loss and L2 loss. My question is which loss presents for fidelity/quality of output images? I think all 3 losses are about identity, similarity.

**Comment by yuval-alaluf** [comment]
How do you define fidelity/quality? The three metrics are designed to measure how similar the reconstructed images are to the original source images. 
Are you referring to FID?

**Comment by duongquangvinh** [comment]
Yeah maybe FID is what I want to consider. Could I calculate it from 2 data folders (1 for ground truth, 1 for output images)?

**Comment by yuval-alaluf** [comment]
FID is the best metric I know, but does have its own drawbacks. Although we don't provide code for computing FID, there are many implementations for computing FID in pytorch.

**Comment by duongquangvinh** [comment]
Thank you for your response, sir.
