### ISSUE TITLE
Bug request for help

### ISSUE THREAD

**Issue by yyuu-6** [eladrich/pixel2style2pixel#152]
I try to use your code but have a problem that "No module named 'fused'"
 How can I deal with it?What version of Cuda should I use

**Comment by duongquangvinh** [comment]
Did you use it on colab?

**Comment by yuval-alaluf** [comment]
Hi @yyuu-6 
You should have CUDA >= 10.1. What version do you have?

**Comment by yyuu-6** [comment]
> Hi @yyuu-6
> You should have CUDA >= 10.1. What version do you have?
Thank you for your reply，I upgrade Cuda version and  solve the problem

**Comment by yyuu-6** [comment]
I meet a new problem ,when I run the code, the above modules cannot be used in the code below,e,g,the following picture,how to avoid reintroduce the modules 
![image](https://user-images.githubusercontent.com/60559153/122856957-4bf01d00-d34a-11eb-8366-1eb279f22b00.png)

**Comment by yuval-alaluf** [comment]
> I meet a new problem ,when I run the code, the above modules cannot be used in the code below,e,g,the following picture,how to avoid reintroduce the modules

I am not sure what you mean by the modules cannot be used. Are you unable to import the files?

**Comment by yyuu-6** [comment]
> > I meet a new problem ,when I run the code, the above modules cannot be used in the code below,e,g,the following picture,how to avoid reintroduce the modules
> 
> I am not sure what you mean by the modules cannot be used. Are you unable to import the files?

For example,when I run the above code,I import os,but when I run the follow code ,I need to import os again

**Comment by yuval-alaluf** [comment]
Seems a bit strange. I assume you're working with the notebook? If so, you shouldn't need to re-import modules unless the kernel was restarted from some reason.
