### ISSUE TITLE
another question for computing Metrics

### ISSUE THREAD

**Issue by duongquangvinh** [eladrich/pixel2style2pixel#153]
Hi sir,

When training I have 2 folders, source_A (animated faces) and target_B (FFHQ). Assume that I use source_A to generate images in inference and call it generated_C.

My question is:
+ In computing metrics parts with lpips, l2, identity loss, which folder should I choose for ground truth, source_A or target_B?
+ gt_folder has all 1024x1024 while generated_folder has all 256x256, is it ok? Or we should resize in torch transforms?

Many thanks.

**Comment by yuval-alaluf** [comment]
Are you trying to translate between animated faces to real faces? In that case, computing LPIPS/L2/Identity may not be exactly what you want since you're transferring between two domains rather than reconstructing the images. Did I understand you correctly?

**Comment by duongquangvinh** [comment]
> Are you trying to translate between animated faces to real faces? In that case, computing LPIPS/L2/Identity may not be exactly what you want since you're transferring between two domains rather than reconstructing the images. Did I understand you correctly?

oh yes, that is what I am considering now. I thought it does not make sense with that case.

**Comment by yuval-alaluf** [comment]
Correct. These metrics are more designed to be used for the reconstruction task :)
