### ISSUE TITLE
Runtime Error for id_loss

### ISSUE THREAD

**Issue by zbw0329** [eladrich/pixel2style2pixel#156]
Hi!Thanks for your work!
I use the pretrained sketch model with no errors.But when I  add id_lamda=0.1,an error occurred.

RuntimeError:Give groups=1,weght of size [64,3,3,3],expected input[2,1,112,112] to have 3 chanels,but got 1 instead.

I have turned my sketch data into RGB,but the error occurred still.

**Comment by zbw0329** [comment]
I want to know why the 'label_nc = 1' and the 'input_nc = 1' ?
When I training the sketch model,isn't the input label a color image? So why the label_nc is not equals to 3?
Is it because the input image is a grayscale image so input_nc=1?

**Comment by yuval-alaluf** [comment]
Exactly. Since in our experiments we used a Grayscale image we set them equal to 1. If you converted it to RGB you should set it to 3.

**Comment by zbw0329** [comment]
I set the label_nc=3 and the input_nc=3,and my datasets are 3 channels images.
But It occurred that 'size mismatch for input_layer.0.weight: copying a param with shape torch.Size([64,1,3,3])from checkpoint,the shape om current model is torch.Size([64,3,3,3])

Should I discard the pretrained_model?

**Comment by zbw0329** [comment]
I try to train the encoder,and I set the parameters as you recommended in readme.
But it occurred 'Attribute Error:'pSp' object has no attribute '_psp_load_latent_avg'

**Comment by yuval-alaluf** [comment]
Ah ok, are you using the pre-trained sketch to face model? That model was trained using a single input channel (and therefore you see `copying a param with shape torch.Size([64,1,3,3])from checkpoint`). But now you defined a new encoder receiving a three channel input and you get a mismatch. There are three things you can do: 
1. Not use the pretrained encoder
2. Use the pretrained encoder but don't copy over the input layer
3. When copying the input layer from the checkpoint, replicate it three times so you get a 3 channel input to match your new encoder. 

Since option 3 is a bit more involved, I'd go with option 2 which is also preferable over option 1. 

Does that make sense?

**Comment by zbw0329** [comment]
Yes,I get it.Thanks for your help!

**Comment by zbw0329** [comment]
I can train the pretrained sketch model successfully(input_nc=1 and label_nc=3),but when I added id_lamda=0.1(Because I think the results of trainning),it occurred error immediately.And the error is located in IDLoss file，so I want to know whether it is independent of the size of the input image?

Or can I change the code of idloss to correct the error

**Comment by yuval-alaluf** [comment]
Can you show me what error you got in the IDLoss? If you pass a 3-channel input to the IDLoss you shouldn't see an error, but best if you send me the error you got.

**Comment by zbw0329** [comment]
This is my traceback:
Traceback (most recent call last):
  File "/home/derek/bowen/pixel2style2pixel-master/scripts/train.py", line 32, in <module>
    main()
  File "/home/derek/bowen/pixel2style2pixel-master/scripts/train.py", line 28, in main
    coach.train()
  File "/home/derek/bowen/pixel2style2pixel-master/training/coach.py", line 88, in train
    loss, loss_dict, id_logs = self.calc_loss(x, y, y_hat, latent)
  File "/home/derek/bowen/pixel2style2pixel-master/training/coach.py", line 205, in calc_loss
    loss_id, sim_improvement, id_logs = self.id_loss(y_hat, y, x)
  File "/home/derek/anaconda3/envs/pspgan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/derek/bowen/pixel2style2pixel-master/criteria/id_loss.py", line 24, in forward
    x_feats = self.extract_feats(x)
  File "/home/derek/bowen/pixel2style2pixel-master/criteria/id_loss.py", line 19, in extract_feats
    x_feats = self.facenet(x)
  File "/home/derek/anaconda3/envs/pspgan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/derek/bowen/pixel2style2pixel-master/models/encoders/model_irse.py", line 48, in forward
    x = self.input_layer(x)
  File "/home/derek/anaconda3/envs/pspgan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/derek/anaconda3/envs/pspgan/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/derek/anaconda3/envs/pspgan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/derek/anaconda3/envs/pspgan/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "/home/derek/anaconda3/envs/pspgan/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 350, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[2, 1, 112, 112] to have 3 channels, but got 1 channels instead

and my parameters are as follows:

--dataset_type=celebs_sketch_to_face
--exp_dir=/home/derek/harddisk2T/bowen/exp_dir/
--workers=8
--batch_size=2
--test_batch_size=2
--test_workers=8
--val_interval=2500
--save_interval=5000
--encoder_type=GradualStyleEncoder
--start_from_latent_avg
--lpips_lambda=0.8
--l2_lambda=1
--id_lambda=0.1
--w_norm_lambda=0.005
--label_nc=3
--input_nc=1

my train_dataset is CelebA dataset.The size of the image is 178x218
my train_sketch_datatset is CelebA dataset,but it has been convert into grayscale.
I want to make a model that can painting the old photos

**Comment by yuval-alaluf** [comment]
Thanks for the details. I won't have time today to try and recreate your error, but Im quite certain it is something to do with playing around with the `label_nc` and `input_nc`. 
I think that `label_nc` should equal 0 in this case. When we load the images, we have: 
```
from_im = from_im.convert('RGB') if self.opts.label_nc == 0 else from_im.convert('L')
``` 
And since in your args we have `label_nc=3` the image is set to be a single channel image instead of RGB. If you change the value to 0 you should load the image as an RGB image and then you shouldn't have any size mismatch issues. 
Let me know if this solves the issue. If not I'll try to recreate the error, hopefully tomorrow.

**Comment by zbw0329** [comment]
Yes!
I set the label_nc=0 , input_nc =3 and it seems to work well with this parameters!
And there is no error with the IDLoss!
Thank you for your patient help!
