### ISSUE TITLE
training results issue

### ISSUE THREAD

**Issue by JosephPai** [eladrich/pixel2style2pixel#158]
Hi, 

First of all, thanks for releasing the amazing repo!

I'm trying to use the psp codebase to run on my own dataset.
Basically, I want to train an encoder to encode a set of parameters into the W+ space, and use the pre-trained frozen StyleGAN generator to generate the face image.
So I changed the GradualStyleEncoder into a MLPEncoder implemented by myself.
However, the training result seems abnormal.

![pspresult](https://user-images.githubusercontent.com/25195733/123373552-2405f100-d5b8-11eb-8f47-af87119598bd.png)

Can you help have a look?
Do you have any about this?

Thanks a lot!

**Comment by yuval-alaluf** [comment]
Hi @JosephPai 
If you are training on your own data, why did you need to change the encoder architecture? Or was the change in architecture something unrelated that you're testing? It seems like there may be some issue with your MLPEncoder. 
Did you try training the GradualStyleEncoder on your data?

**Comment by JosephPai** [comment]
Hi @yuval-alaluf ,

Thanks for your response!
I changed the GradualStyleEncoder into MLPEncoder because my input is a vector, but not image.
i.e., I'm trying to control the image generation by a vector, so I encode the vector by a MLPEncoder.
Btw, the input vector is extracted from image, so I use the source image as ground-truth for supervision.
Thanks!

**Comment by yuval-alaluf** [comment]
It seems like you have changed a core part of pSp (the encoder itself). Therefore it is not entirely surprising that the results do not work out-of-the-box. 
I can recommend trying to ovetfit the encoder on a single image to verify that your encoder is able to invert the single image it was trained on. Only then can you really know if your model has the capacity to learn the inversion.

**Comment by JosephPai** [comment]
That's a good suggestion!
I'll try this. Thanks!

Actually I'm trying to increase the Encoder's capacity, I use 8 layers MLP, as what StyleGAN2 do.
The results is getting better, at least the face region is acceptable.
However, the hair and background is still confusing...

![image](https://user-images.githubusercontent.com/25195733/123782737-3a89b080-d908-11eb-80aa-0e759810089d.png)

**Comment by yuval-alaluf** [comment]
The results do look better, but again, since you really changed the core part of pSp you will most likely not be able to get good results right away. You can continue to play with your encoder, but as this is not an issue with the code of pSp I am closing this issue for now.
