### ISSUE TITLE
About connetion between StyleGAN2 and PSP encoder

### ISSUE THREAD

**Issue by diaodeyi** [eladrich/pixel2style2pixel#161]
Hi, Thanks for your great work ! In the code, it seems the Style vector will be fed into the MLP in the StyleGAN2, not the module A affine  layer in the paper’s model diagram.

**Comment by diaodeyi** [comment]
```
 if not input_is_latent:
            styles = [self.style(s) for s in styles]
```
In the model.py

**Comment by yuval-alaluf** [comment]
Please observe that with our encoder, the variable `input_is_latent` will be set to True and will not pass through the mapping network. So everything looks good in the code
