### ISSUE TITLE
not an issue - Were there any efforts to map the output back into a video?

### ISSUE THREAD

**Issue by 8secz-johndpope** [eladrich/pixel2style2pixel#163]
There's a technology called fsgan - and I wonder if it could be repurposed to help here.

https://pbs.twimg.com/media/EIMbqh_XYAAthpA?format=jpg&name=large

**Comment by yuval-alaluf** [comment]
I am a bit unfamiliar with reenactment works so it is hard for me to say. This would definitely be an interesting avenue to explore though.
