### ISSUE TITLE
Using a different generator as base

### ISSUE THREAD

**Issue by Nerdyvedi** [eladrich/pixel2style2pixel#164]
Hi, Can we replace Stylegan generator with some other generator.
What changes would we have to do to support this?

Thanks

**Comment by yuval-alaluf** [comment]
Sure.
You can simply change the definition of the Generator class: 
https://github.com/eladrich/pixel2style2pixel/blob/8cb2e62bbd7de4c4e7040437c9738043c98accd2/models/psp.py#L31
Just note that our encoder outputs a latent of size `18x512` (for the faces domain). If you change your generator, you may need to change the encoder to match the expected input of the generator.
