### ISSUE TITLE
UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by iwellkim** [eladrich/pixel2style2pixel#17]
Hi?

I encountered this error message 
UnpicklingError: invalid load key, '<'.

after I run this cell
model_path = EXPERIMENT_ARGS['model_path']
ckpt = torch.load(model_path, map_location='cpu')

Can someone help me?

I'm trying this in colab notebook.

**Comment by yuval-alaluf** [comment]
Hi @iwellkim ,
Can you please verify that you were able to download the model correctly? Please check that the model is indeed approximately 1.12GB and that you did not receive a "quota exceeded" error from Google Drive.

**Comment by iwellkim** [comment]
@yuval-alaluf Oh sorry. I was lost. Thanks. Will try it again!
