### ISSUE TITLE
about toonifed StyleGAN2 and model blending

### ISSUE THREAD

**Issue by huangfaan** [eladrich/pixel2style2pixel#172]
Hi, may I ask you a question. I have trained 2 stylegan2 models successfully by pytorch, one trained on my own cartoon dataset, another trained on ffhq dataset. They both generate normal 256*256 images. Now I want to get a toonifed StyleGAN2, so I blended the two models (by pytorch, I will paste the blend_models_pytorch.py later). and I tried the blend_models.py (by using .pkl file) the author provided. But I found that my results seem to have some errors. So could you help me??

my results:
![d8f0831a213b7ec1ca4d8f7a93dd04f](https://user-images.githubusercontent.com/54828393/125596078-51f103f0-9a14-4587-bffd-d19b47a9a808.png)

my normal stylegan2 results(trained on my own cartoon dataset)
![e258f837340daa04efb297d3026c08b](https://user-images.githubusercontent.com/54828393/125596422-dc467159-c5f7-4074-95ce-db8cdc1e2bdd.png)

my blend_models_pytorch.py:

import os
import torch
from torchvision import transforms, utils
from model import Generator

def extract_conv_names(model, resolution):

    extract_names = {
        4: [],
        8: ['convs.0.', 'convs.1.', 'to_rgbs.0.'],
        16: ['convs.0.', 'convs.1.', 'to_rgbs.0.', 'convs.2.', 'convs.3.', 'to_rgbs.1.'],
        32: ['convs.0.', 'convs.1.', 'to_rgbs.0.', 'convs.2.', 'convs.3.', 'to_rgbs.1.', 'convs.4.', 'convs.5.', 'to_rgbs.2.'],
        64: ['convs.0.', 'convs.1.', 'to_rgbs.0.', 'convs.2.', 'convs.3.', 'to_rgbs.1.', 'convs.4.', 'convs.5.', 'to_rgbs.2.',
             'convs.6.', 'convs.7.', 'to_rgbs.3.']
    }

    # input    conv1    to_rgb1    convs   to_rgbs
    keys = [key for key, value in model.items()]
    used_names = []
    for key in keys:
        if 'input' in key:
            used_names.append((key, 0))
        elif 'conv1' in key:
            used_names.append((key, 0))
        elif 'to_rgb1' in key:
            used_names.append((key, 0))
        elif 'convs' in key:
            temp_label = True
            for cn in extract_names[resolution]:
                if cn in key:
                    used_names.append((key, 0))
                    temp_label = False
            if temp_label:
                used_names.append((key, 1))
        elif 'to_rgbs' in key:
            temp_label = True
            for cn in extract_names[resolution]:
                if cn in key:
                    used_names.append((key, 0))
                    temp_label = False
            if temp_label:
                used_names.append((key, 1))

    return used_names

def blend_models(model_1, model_2, resolution, blend_width=None):
    # y is the blending amount which y = 0 means all model 1, y = 1 means all model_2

    model_1_names = extract_conv_names(model_1, resolution)
    model_2_names = extract_conv_names(model_2, resolution)

    assert all((x == y for x, y in zip(model_1_names, model_2_names)))

    model_out = model_1.copy()

    model_names = [x[0] for x in model_1_names]
    model_y = [x[1] for x in model_1_names]

    if blend_width:
        # exponent = -x / blend_width
        # y = 1 / (1 + math.exp(exponent))
        print('blend_width 为true 时未实现')
    else:
        for key, y in zip(model_names, model_y):
            model_out[key] = model_1[key] * (1 - y) + model_2[key] * y

    return model_out

def main(ckpt_ffhq, ckpt_cartoon, resolution=8, blend_width=None, output_grid=None, output_pt=None):
    """
    :param ckpt_ffhq:        file from which to take low res layers
    :param ckpt_cartoon:     file from which to take high res layers
    :param resolution:       Resolution level at which to switch between models
    :param blend_width:      None = hard switch, float = smooth switch (logistic) with given width
    :param output_grid:      Path of image file to save example grid (None = don't save)
    :param seed:             seed for random grid
    :param output_pt:       Output path of pickle (None = don't save)
    :return:
    """

    low_res_G, low_res_D, low_res_Gs = ckpt_ffhq['g'], ckpt_ffhq['d'], ckpt_ffhq['g_ema']
    high_res_G, high_res_D, high_res_Gs = ckpt_cartoon['g'], ckpt_cartoon['d'], ckpt_cartoon['g_ema']

    out = blend_models(low_res_Gs, high_res_Gs, resolution=resolution, blend_width=blend_width)

    sample_z = torch.randn(1, 512, device='cuda')

    g_ema = Generator(256, 512, 8).to('cuda')
    g_ema.load_state_dict(out)
    sample, _ = g_ema([sample_z], truncation=1, truncation_latent=None)

    utils.save_image(
        sample,
        output_grid,
        nrow=1,
        normalize=True,
        range=(-1, 1),
    )

if __name__ == '__main__':
    print("ok")

    dir = r'E:\ND\SVN_AI_prj_02_Dev\02-FaceReconstruction_Dev\pixel2style2pixel_wqy\pretrained_models'
    ckpt_cartoon = torch.load(os.path.join(dir, 'stylegan2_cartoon256_420k.pt'), map_location="cpu")
    ckpt_ffhq = torch.load(os.path.join(dir, 'stylegan2_ffhq256_550k.pt'), map_location="cpu")

    gf_blended = torch.load(os.path.join(dir, "stylegan2-ffhq1024-config-f.pt"), map_location="cpu")

    saved = os.path.join(dir, "ffhq_cartoon_blended256.pt")
    main(ckpt_ffhq, ckpt_cartoon, resolution=32, output_pt=saved, output_grid=r'D:\Downloads\blended_pytorch.jpg')

**Comment by yuval-alaluf** [comment]
Is the first pair of images randomly generated samples from your blended generator? It seems like your error is related to the blending on the layers. Therefore your question is better suited for that repository.

**Comment by huangfaan** [comment]
> Is the first pair of images randomly generated samples from your blended generator? It seems like your error is related to the blending on the layers. Therefore your question is better suited for that repository.

Yes, the first pair of images is randomly generated samples from my blended generator. the blending on the layers is not from any repository, I write it by myself. I just want to know if my idea about toonify generator is wrong. Thank you for your reply.

**Comment by yuval-alaluf** [comment]
I believe your understanding is correct, but you may simply have a small error in your implementation. 
From what I recall there is an official layer blending repository and notebook that you can use to create blended generators. I believe this is the repo: 
https://github.com/justinpinkney/toonify

**Comment by huangfaan** [comment]
> I believe your understanding is correct, but you may simply have a small error in your implementation.
> From what I recall there is an official layer blending repository and notebook that you can use to create blended generators. I believe this is the repo:
> https://github.com/justinpinkney/toonify

I don't think it's a error about my layer blending, because I use two official stylegan2 model in my layer blending, it can get correct results. Maybe the error is from my own stylegan2 model.

**Comment by justinpinkney** [comment]
Hello! I haven't checked the blending code, but assuming that is fine it's quite possible for the merging of two networks to not give satisfactory results. I'm assuming that one network has been fine tuned from the other given the results you're seeing, but if the second model has been trained for some time then the weights start to diverge too far from the original and you get bad output images like you've shown above. If you want to try blending the networks I'd suggest using one which has only been fine tuned for a few thousand iterations.

As a warning though I've seen many people try and blend anime and real face models and the results are always a bit rubbish, I think this is mostly because the geometry of anime and real faces is so different.

**Comment by huangfaan** [comment]
> Hello! I haven't checked the blending code, but assuming that is fine it's quite possible for the merging of two networks to not give satisfactory results. I'm assuming that one network has been fine tuned from the other given the results you're seeing, but if the second model has been trained for some time then the weights start to diverge too far from the original and you get bad output images like you've shown above. If you want to try blending the networks I'd suggest using one which has only been fine tuned for a few thousand iterations.
> 
> As a warning though I've seen many people try and blend anime and real face models and the results are always a bit rubbish, I think this is mostly because the geometry of anime and real faces is so different.


ok. thank you for your reply, I think you are right, I will try to do it as you said. Now, I have a blending stylegan2 model which can generate the pictures below:
![image](https://user-images.githubusercontent.com/54828393/125886867-10fab9d0-fdef-489b-b3a7-6a5bace4415e.png)

If I want to get a toonify model to blend anime and real face models, So do I need to train the pSp model in the next step? Should I use real face dataset for training or anime dataset?

**Comment by huangfaan** [comment]
Hello, I'm here again, I still have some confusion about toonification, I feel that my mind has been messed up. Can you help me understand these steps.
![image](https://user-images.githubusercontent.com/54828393/125907933-8d7ab9a0-b529-40bb-ae32-57e4d5fa192e.png)

Now, I have a blended stylegan2 generator, I don'e know how to understand "pSp trained with the FFHQ dataset for toonification using StyleGAN generator.", can you teach me the next specific steps, thank you!

**Comment by yuval-alaluf** [comment]
Sure. Typically, to train an image-to-image model in this case, you would generate pairs of (real image, toon image). That is for each real image, you know its corresponding toon image you want to generate. However, sometimes creating pair data like this is challenging. Therefore, with our toonify model, we trained using only real face images by swapping the FFHQ StyleGAN with the blended toon StyleGAN. Since we swapped the StyleGAN, we were able to naturally translate each real face image to its toon without explicitly requiring the paired data. 

Of course, if you have a wait to generate paired data, then trained with the paired data will probably give you better results. We simply wanted to demonstrate that even in the absence of paired data, pSp was still able to perform the task somewhat nicely. 

If things are still unclear please let me know.

**Comment by huangfaan** [comment]
ok, I understand. I will try to do it, no matter what the result is, I will tell you after a few days.

**Comment by ItchyHiker** [comment]
> ok, I understand. I will try to do it, no matter what the result is, I will tell you after a few days.

Hey, did you manage to generate image using blended model from latent code? I have some problem with this.
Here's my code:
```
latent = torch.load('10075-00.pt')['../dataset/style4/imgs/10075-00.png']['latent']
latent.shape
latent = latent.reshape(1, 1, 512)
sample, _ = g_ema(styles=latent, input_is_latent=True)
utils.save_image(sample, "result.jpg", nrow=1, normalize=True, range=(-1, 1))
```
Here's my result image:
![result](https://user-images.githubusercontent.com/37793513/127284035-27e4a0f2-5fa1-4857-a74f-58665bfec92b.jpg)
I failed to generate a normal image like toonify. Do you have any solution?

**Comment by huangfaan** [comment]
> > ok, I understand. I will try to do it, no matter what the result is, I will tell you after a few days.
> 
> Hey, did you manage to generate image using blended model from latent code? I have some problem with this.
> Here's my code:
> 
> ```
> latent = torch.load('10075-00.pt')['../dataset/style4/imgs/10075-00.png']['latent']
> latent.shape
> latent = latent.reshape(1, 1, 512)
> sample, _ = g_ema(styles=latent, input_is_latent=True)
> utils.save_image(sample, "result.jpg", nrow=1, normalize=True, range=(-1, 1))
> ```
> 
> Here's my result image:
> ![result](https://user-images.githubusercontent.com/37793513/127284035-27e4a0f2-5fa1-4857-a74f-58665bfec92b.jpg)
> I failed to generate a normal image like toonify. Do you have any solution?

I can manage to generate image using blended model from latent code. 

here's my code:
![1627538305](https://user-images.githubusercontent.com/54828393/127439568-042d3a4f-a8c3-43b1-a158-6185c5c5e722.png)

**Comment by ItchyHiker** [comment]
> > > ok, I understand. I will try to do it, no matter what the result is, I will tell you after a few days.
> > 
> > 
> > Hey, did you manage to generate image using blended model from latent code? I have some problem with this.
> > Here's my code:
> > ```
> > latent = torch.load('10075-00.pt')['../dataset/style4/imgs/10075-00.png']['latent']
> > latent.shape
> > latent = latent.reshape(1, 1, 512)
> > sample, _ = g_ema(styles=latent, input_is_latent=True)
> > utils.save_image(sample, "result.jpg", nrow=1, normalize=True, range=(-1, 1))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's my result image:
> > ![result](https://user-images.githubusercontent.com/37793513/127284035-27e4a0f2-5fa1-4857-a74f-58665bfec92b.jpg)
> > I failed to generate a normal image like toonify. Do you have any solution?
> 
> I can manage to generate image using blended model from latent code.
> 
> here's my code:
> ![1627538305](https://user-images.githubusercontent.com/54828393/127439568-042d3a4f-a8c3-43b1-a158-6185c5c5e722.png)

Thanks for your reply! Seems like your latent code is in numpy format, my latent code is in pytorch format. How do you generate you latent code? I used the projector.py is this repo to generate latent code and got a '.pt' file and an image.

**Comment by huangfaan** [comment]
> Sure. Typically, to train an image-to-image model in this case, you would generate pairs of (real image, toon image). That is for each real image, you know its corresponding toon image you want to generate. However, sometimes creating pair data like this is challenging. Therefore, with our toonify model, we trained using only real face images by swapping the FFHQ StyleGAN with the blended toon StyleGAN. Since we swapped the StyleGAN, we were able to naturally translate each real face image to its toon without explicitly requiring the paired data.
> 
> Of course, if you have a wait to generate paired data, then trained with the paired data will probably give you better results. We simply wanted to demonstrate that even in the absence of paired data, pSp was still able to perform the task somewhat nicely.
> 
> If things are still unclear please let me know.

Thanks for your help. I have successfully mixed the models and can get the correct outputs. However now I have some questions, I want to know about the 'psp_ffhq_toonify.pt' clearly. Can you tell me the detailed process of getting it? The more detailed the better, is it trained using the ffhq dataset and based on the mixed stylegan2 model? thaknk you, I am look forward to receiving your response.

**Comment by yuval-alaluf** [comment]
> > Sure. Typically, to train an image-to-image model in this case, you would generate pairs of (real image, toon image). That is for each real image, you know its corresponding toon image you want to generate. However, sometimes creating pair data like this is challenging. Therefore, with our toonify model, we trained using only real face images by swapping the FFHQ StyleGAN with the blended toon StyleGAN. Since we swapped the StyleGAN, we were able to naturally translate each real face image to its toon without explicitly requiring the paired data.
> > Of course, if you have a wait to generate paired data, then trained with the paired data will probably give you better results. We simply wanted to demonstrate that even in the absence of paired data, pSp was still able to perform the task somewhat nicely.
> > If things are still unclear please let me know.
> 
> Thanks for your help. I have successfully mixed the models and can get the correct outputs. However now I have some questions, I want to know about the 'psp_ffhq_toonify.pt' clearly. Can you tell me the detailed process of getting it? The more detailed the better, is it trained using the ffhq dataset and based on the mixed stylegan2 model? thaknk you, I am look forward to receiving your response.

Sure. Training the psp_ffhq_toonify model is much more straightforward than it sounds. All we did was: 
1. Changed the FFHQ StyleGAN generator to the mixed StyleGAN generator. 
2. Changed the loss weights a bit. 
We still trained using only real images from FFHQ (since we didn't have any paired data). If you have paired data (which should be possible to obtain in most cases), you can train your model using the paired data for supervision.

**Comment by huangfaan** [comment]
> > > Sure. Typically, to train an image-to-image model in this case, you would generate pairs of (real image, toon image). That is for each real image, you know its corresponding toon image you want to generate. However, sometimes creating pair data like this is challenging. Therefore, with our toonify model, we trained using only real face images by swapping the FFHQ StyleGAN with the blended toon StyleGAN. Since we swapped the StyleGAN, we were able to naturally translate each real face image to its toon without explicitly requiring the paired data.
> > > Of course, if you have a wait to generate paired data, then trained with the paired data will probably give you better results. We simply wanted to demonstrate that even in the absence of paired data, pSp was still able to perform the task somewhat nicely.
> > > If things are still unclear please let me know.
> > 
> > 
> > Thanks for your help. I have successfully mixed the models and can get the correct outputs. However now I have some questions, I want to know about the 'psp_ffhq_toonify.pt' clearly. Can you tell me the detailed process of getting it? The more detailed the better, is it trained using the ffhq dataset and based on the mixed stylegan2 model? thaknk you, I am look forward to receiving your response.
> 
> Sure. Training the psp_ffhq_toonify model is much more straightforward than it sounds. All we did was:
> 
> 1. Changed the FFHQ StyleGAN generator to the mixed StyleGAN generator.
> 2. Changed the loss weights a bit.
>    We still trained using only real images from FFHQ (since we didn't have any paired data). If you have paired data (which should be possible to obtain in most cases), you can train your model using the paired data for supervision.


OK, thank you for your reply. It turns out that what I understood before is correct, I used the mixed StyleGAN generator and paired data, and finally I got the result I wanted. But I trained using only real images from FFHQ, I couldn't, it may be due to insufficient training, I don't know, I'll try again, more time.

**Comment by yuval-alaluf** [comment]
> I used the mixed StyleGAN generator and paired data

Training with paired data is almost always preferred so its nice to hear that it works for you. 
I think that we have solved this issue so I'm closing this for now. If you find any other issues or if you have additional questions, feel free to reopen.

**Comment by huangfaan** [comment]
> > I used the mixed StyleGAN generator and paired data
> 
> Training with paired data is almost always preferred so its nice to hear that it works for you.
> I think that we have solved this issue so I'm closing this for now. If you find any other issues or if you have additional questions, feel free to reopen.

ok, thank you for your help!

**Comment by seawater668** [comment]
> > > > 当然。通常，要在这种情况下训练图像到图像模型，您将生成成对的（真实图像、卡通图像）。也就是说，对于每个真实图像，您都知道要生成其对应的卡通图像。但是，有时创建这样的配对数据具有挑战性。因此，在我们的 toonify 模型中，我们通过将 FFHQ StyleGAN 与混合 toon StyleGAN 交换，仅使用真实面部图像进行训练。由于我们交换了 StyleGAN，我们能够自然地将每张真实人脸图像转换成它的卡通形象，而无需明确要求配对数据。
> > > > 当然，如果您等待生成配对数据，那么使用配对数据进行训练可能会给您带来更好的结果。我们只是想证明，即使在没有配对数据的情况下，pSp 仍然能够在某种程度上很好地执行任务。
> > > > 如果事情仍然不清楚，请告诉我。
> > > 
> > > 
> > > 感谢您的帮助。我已经成功地混合了模型并且可以获得正确的输出。但是现在我有一些问题，我想清楚地了解'psp_ffhq_toonify.pt'。能说说详细的获取过程吗？越详细越好，是使用ffhq数据集训练，基于mixed stylegan2模型训练的吗？谢谢你，我期待着收到你的回复。
> > 
> > 
> > 当然。训练 psp_ffhq_toonify 模型比听起来简单得多。我们所做的只是：
> > 
> > 1. 将 FFHQ StyleGAN 生成器更改为混合 StyleGAN 生成器。
> > 2. 稍微改变了损失权重。
> >    我们仍然只使用来自 FFHQ 的真实图像进行训练（因为我们没有任何配对数据）。如果你有配对数据（在大多数情况下应该可以获得），你可以使用配对数据训练你的模型进行监督。
> 
> 好的，谢谢你的回复。事实证明我之前理解的是对的，我使用了混合的StyleGAN生成器和配对数据，终于得到了我想要的结果。但是我只用FFHQ的真实图片训练，我做不到，可能是训练不够，我不知道，我再试一次，更多时间。
Hello, can you share how you transformed the real face into a cartoon face? How is the effect?

**Comment by watertianyi** [comment]
> > > > 当然。 ，要在种到到图像图像模型。。，有时创建的配对具有挑战性因此。，在我们具有挑战性，toonify toonify toonify toonify模型，ffhq styleth styletan styletan styletan styletan toon stylegan交换，仅地将每人图像成成的，而的卡通的的卡通需明确要求要求要求配对数据数据数据数据数据当然配对配对配对配对要求要求要求要求要求要求要求要求要求要求要求要求要求配对配对配对要求要求要求要求要求要求要求要求要求配对配对配对配对
> > > > 要求配对想证明，即使在没有配数据的情况下，pSp仍然能够在某种程度上很好地执行任务。
> > > > 如果事情仍然不清晰，请告诉我。
> > > 
> > > 
> > > 感谢您。我成功地混合模型并且并且可以可以获得获得正确。。但是但是现在现在但是我我现在现在我我我我我我我有有有有有有有一些一些问题问题问题一些一些一些问题问题但是但是但是但是但是。但是但是。。。但是。。。。。。。。但是但是但是但是但是但是但是，是使用ffhq数据集训练，基于mixed stylegan2模型训练的吗？谢谢你，我等着收你的回复。
> > 
> > 
> > 当然。训练psp_ffhq_toonify模型比听起来简单得多。我们所做的只是：
> > 
> > 1. 将 FFHQ StyleGAN 生成器更改为混合 StyleGAN 生成器。
> > 2. ffhq ffhq的
> >    使用使用的的的进行进行训练因为因为我们我们没有没有没有没有没有任何任何没有任何没有任何没有没有没有任何没有没有没有。。。。。。。如果如果你你你有有配对数据配对数据数据数据（（在（在在在在在在在在大多数在在在在在在在大多数在在在在在在在在在在在在在在在在在在在在在在在在在在模型进行监督。
> 
> 好的，谢谢的回复证明证明之前理解对的的对对对是是对的的对的的的了使用使用了了了了混合的混合混合混合的混合的混合混合的混合的混合生成器生成器生成器生成器生成器生成器生成器配对生成器和和数据，终于做不到，可能是训练不够，我不知道，我再试一次，更多时间。

Hello, can you share how you transformed the real face into a cartoon face? How is the effect?
