### ISSUE TITLE
Alignment script error

### ISSUE THREAD

**Issue by czarekkwasny** [eladrich/pixel2style2pixel#173]
Hello,

Thank you very much for providing the implementation of the paper for experimenting.

I'm not sure if it's the issue of the script or understanding how the alignment method works but I'm getting an error while trying to align some of the input data. Happened so far with two examples, both the face is visible from the side. Here's an example:
![asian_girl](https://user-images.githubusercontent.com/13907673/125646538-d326cea2-d0f4-4353-87e9-37ca377e3f17.jpg)
The script returns error:
UnboundLocalError: local variable 'shape' referenced before assignment
If I change it to another picture of a face (especially with more upfront angle) the alignment and inference work just fine...

I'm using the provided environment, however I run experiments on Fedora 34 (providing GCC 11), which required me to compile GCC 9.3.0 and use it with CUDA 11.3.

**Comment by yuval-alaluf** [comment]
This error can occur when `dlib` could not accurately detect the face landmarks. I believe in this case, your input image is too non-frontal and the model can not accurately return the landmarks.

**Comment by czarekkwasny** [comment]
Thank you very much for the feedback. I haven't explored the algorithm in depth, however do you think in such corner case  would it be a viable solution to provide the landmark map manually or simply try to align the face in photo editing tool (centering the nose location, leveling the eyes, lips) and skip the alignment process altogether?

**Comment by yuval-alaluf** [comment]
Thats a good question. I too haven't really had the opportunity to explore the alignment algorithm in depth and haven't had a chance to manually align images so I don't really have a good answer for you. I would like to think others have come across this issue as well in other repos so you may find some more useful tips elsewhere. If you do try it out or find a useful resource it would be great if you could share.

**Comment by czarekkwasny** [comment]
Hello,
Sorry for late reply. So eventually as it turned out it wasn't the angle that was the issue but that in this specific case the majority of the face is covered with hair which made it impossible for the algorithm to detect the forehead and jawline shapes and therefore perform the alignment.

The solution to the problem was to skip the alignment and provide the algorithm with pre-aligned data. I simply ran an alignment on another face profile and used the Photoshop Puppet Warp Tool to align the features to the desired location (this of course can introduce distortions so has to be performed carefully). It resulted in an inference, not the prettiest one, but seems correct:

![asian_girl_frontalized](https://user-images.githubusercontent.com/13907673/127157000-2f121cc7-9918-4ce8-933b-8fc9305eb779.jpg)

I noticed that frontalization algorithm tends to age the faces as well as "gravitate" towards a particular shape, especially of the lower part of the face (lips, cheeks). Is it something that can be corrected through training data set or manipulation of the latent mask like in case of inferences based on sketch or segmentation maps input?

**Comment by yuval-alaluf** [comment]
Yea the result does look correct with respect to the alignment. The challenge with the face normalization is that we trained it with no paired data, so while the results were good in some cases, generalizing onto more challenging images like yours still remains a challenge. 
This could be improved by using paired data. 
One thing I thought about doing is generating synthetic data by generating images from StyleGAN and then altering the pose with InterFaceGAN. Then you have paired data of the same individual at different poses. The problem with this is that you are training only on synthetic data so this may not generalize to well to real images. 
As you mentioned, you could also try to play around with the latent mask and perform style mixing on some fine layers to get better colonization. 
Hope this helps!

**Comment by czarekkwasny** [comment]
Thank you very much, interesting ideas. I'm relatively new to GANs so it might be a very nice exercise to try out your suggestions. Would it be appropriate to share the results here if I come up with interesting solutions or examples?

**Comment by yuval-alaluf** [comment]
Of course! We're always excited to see what people come up with! Feel free to reach out if you have any other questions 😄
