### ISSUE TITLE
Question abt the output size

### ISSUE THREAD

**Issue by LightingMc** [eladrich/pixel2style2pixel#179]
Hey, so correct me if I am wrong, StyleGAN's decoder has 18 layers, and you are using the first 14 layers to get an output at size 256 * 256 and the entire 18 layers to get the output at a size of 1024 * 1024? I thought the output was supposed to be at a size of 1024 * 1024 and then u just downsample it to the required size.

The reason for the confusion is that I am playing around with the latent space and models with an output size of 256 * 256 give a latent space of shape [b,14,512] but the default inference PSP model given by you gives an output size of 1024 * 1024 and its latent space is [b,18,512].

**Comment by yuval-alaluf** [comment]
In StyleGAN, the number of latent vectors is dependent on the output resolution. In pSp, we used the StyleGAN generator for faces which outputs a resolution of 1024x1024 and hence you see the 18 style codes in this repo. 
For smaller generators which output a resolution of 256x256, you'll see that they work on 14 style codes. 
The exact calculation for the number of style codes for a given resolution can be found here: 
https://github.com/eladrich/pixel2style2pixel/blob/3e2ebd82bb3e3719507898f365abcec16597061a/models/psp.py#L27-L28

Note that the parameter `--output_size` is used to specify the output resolution of the StyleGAN generator, not the output size you wish to work with. So if you are working with a 1024x1024 generator, you should specify `--output_size=1024` and if you are working with a 256x256 generator, the flag should be set of `--output_size=256`. The code will then automatically compute the correct number of style codes to work with
