### ISSUE TITLE
Is it possible to run inference on cpu?

### ISSUE THREAD

**Issue by justmaulik** [eladrich/pixel2style2pixel#18]
I tried it to make it work(with beginner knowledge) but I keep getting different errors.

**Comment by yuval-alaluf** [comment]
Hi @justmaulik 
This may be possible, but it may be challenging to make the changes to the code as ninja requires CUDA. 
However, if you plan on only running inference (and don't have access to a GPU), maybe running on Google colab will suit your needs. 
In case you missed it, we have a Google colab linked in the README that can help you get started.

**Comment by justmaulik** [comment]
I already tried on colab and also modified some of the code(few lines) where it required CUDA but it's more complex than just a few lines. and I can train it on GPU but I am planning to host inference as API so CPU is the only way the fits my budget.

Replacing ninja to support CPU inference is anywhere on the to-do list? :)  or you could just point me in a direction what I need to do to run just the inference on CPU.

**Comment by yuval-alaluf** [comment]
If I had to guess, you're probably getting an exception when trying to load the FusedLeakyReLU?   
We are not sure when we will have time to add CPU inference support, but you may find the following issue from rosinality helpful: 
https://github.com/rosinality/stylegan2-pytorch/issues/89
The commit linked in the issue above should be a good starting point, but some more modifications will most likely be needed.

**Comment by justmaulik** [comment]
Thanks @yuval-alaluf
