### ISSUE TITLE
Recommended CUDA version?

### ISSUE THREAD

**Issue by LightingMc** [eladrich/pixel2style2pixel#181]
Also, I think the given torch and torchvision versions in the env. are incompatible. Myself I have it like this:

    - torch==1.6.0
    - torchvision==0.7.0

**Comment by yuval-alaluf** [comment]
You need CUDA >= 10.1. 
You may be right about the torch and torchvision versions. Whats important is that you have torch >= 1.6.0 so looks good

**Comment by LightingMc** [comment]
I am having a lot of difficulty with here with version control. I don't know why but it is only working on one of my servers and not the others. I have been able to trace down the issue to some failures to compile for the files at **models/stylegan2/op**. 

Below is the error output. It is from a jupyter notebook in the relevant folder:
![image](https://user-images.githubusercontent.com/42900802/128582451-7a4e8e15-42df-44a8-97ba-2bc89a77bed1.png)
![image](https://user-images.githubusercontent.com/42900802/128582462-07c40ffb-8cfb-46d9-8032-85e2d308d956.png)

It specifically says **cicc not found**. I have been unable to resolve this error. CUDA version 11.1 and Pytorch version is '1.9.0+cu111'.

**Comment by yuval-alaluf** [comment]
> I have been able to trace down the issue to some failures to compile for the files at **models/stylegan2/op**.

There's a good handful of other issues regarding the compilation of the CUDA extensions and ninja. Please take a loot at those to see if they answer your question.
