### ISSUE TITLE
Failed to save `latent_avg` in  `rosinality/stylegan2-pytorch`

### ISSUE THREAD

**Issue by onefish51** [eladrich/pixel2style2pixel#183]
I trained StyleGAN2 by [rosinality/stylegan2-pytorch](https://github.com/rosinality/stylegan2-pytorch) . I found rosinality does not save the `latent_avg`in checkpoint
```Python 
torch.save(
                    {
                        "g": g_module.state_dict(),
                        "d": d_module.state_dict(),
                        "g_ema": g_ema.state_dict(),
                        "g_optim": g_optim.state_dict(),
                        "d_optim": d_optim.state_dict(),
                        "args": args,
                        "ada_aug_p": ada_aug_p,
                    },
                    f"checkpoint/{str(i).zfill(6)}.pt",
                )
```
I try to save latent_avg from [restyle-encoder/issues/1](https://github.com/yuval-alaluf/restyle-encoder/issues/1) :
```Python 
latent_avg = torch.from_numpy(g_ema.mapping["w_avg"].value().eval())
# or 
latent_avg = torch.from_numpy(g_ema.vars["dlatent_avg"].value().eval())
```
but I failed !

how to save `latent_avg` in  [rosinality/stylegan2-pytorch](https://github.com/rosinality/stylegan2-pytorch)?

**Comment by yuval-alaluf** [comment]
If you are unable to save the latent average you can easily estimate it using the following snippet: 
```python
self.net.latent_avg = self.net.decoder.mean_latent(int(1e5))[0].detach()
```
You can verify that you get the correct result by saving the corresponding image and seeing if it makes sense.

**Comment by onefish51** [comment]
ok
