### ISSUE TITLE
What is the difference between label_nc and input_nc?

### ISSUE THREAD

**Issue by LightingMc** [eladrich/pixel2style2pixel#184]

**Comment by yuval-alaluf** [comment]
Hmm. I don't really remember why we used both :)
Basically, if you are working on RGB images you should set `input_nc=3` and `label_nc=0`. 
If you are working on segmentation maps as the input you should set `input_nc = label_nc = n_channels` where `n_channels` is the number of semantic labels. 
And for sketches you should set `input_nc = label_nc = 1`
