### ISSUE TITLE
[bug] Colab notebook missing dep. upfirdn2d.so

### ISSUE THREAD

**Issue by wiryfuture** [eladrich/pixel2style2pixel#185]
The last cell before selecting the experiment type is missing dep upfirdn2d.so where it imports pSp;

```python
from argparse import Namespace
import time
import sys
import pprint
import numpy as np
from PIL import Image
import torch
import torchvision.transforms as transforms

sys.path.append(".")
sys.path.append("..")

from datasets import augmentations
from utils.common import tensor2im, log_input_image
from models.psp import pSp

%load_ext autoreload
%autoreload 2
```

![image](https://user-images.githubusercontent.com/50517631/128501706-17e31d39-6d79-4259-ac11-36de2b3275c3.png)

**Comment by yuval-alaluf** [comment]
I just ran the notebook myself and could not reproduce the error.  Are you running the notebook locally or using Google Colab?

**Comment by wiryfuture** [comment]
> I just ran the notebook myself and could not reproduce the error.  Are you running the notebook locally or using Google Colab? 

I ran it in Google Colab, hm. It might be a supply chain issue with one of the dependencies of a dependency. 🤷🏼‍♀️

**Comment by yuval-alaluf** [comment]
Definitely weird. I would make sure that all the previous cells ran successfully and that you didn't install anything else by mistake. But other than that I'm not really sure where the difference could come from 🤔

**Comment by wiryfuture** [comment]
I'm gonna close this issue because if it can't be replicated then it should be fine 😆
