### ISSUE TITLE
Latents Portability

### ISSUE THREAD

**Issue by 5agado** [eladrich/pixel2style2pixel#19]
I was interested to pick your brain regarding the portability of the generated latent representation, especially across models and frameworks.

I did extensive experiments with StyleGAN, mostly in its Tensorflow version, and have seen code like the [rosinality one](https://github.com/rosinality/stylegan2-pytorch), meant to convert model checkpoints.

To train a new psp model I need to specify a previously trained Pytorch StyleGAN2 model, and then I can simply obtain projected/encoded latents from the psp model and use them in my original Pytorch one. However these latents don't seem to be portable to a Tensorflow model, say one I converted to Pytorch with a utility as mentioned above.

Did you do any experiments regarding this? Would you suggest me to simply move my latents-editing setup to Pytorch or do you have any ideas?

**Comment by yuval-alaluf** [comment]
Hi @5agado 
All of our experiments were performed using Pytorch so we have not come across the portability issue you mentioned.  
However, [rosinality's converions script](https://github.com/rosinality/stylegan2-pytorch/blob/master/convert_weight.py) has a test at the end to verify that the images generated from the Pytorch model are identical to those generated by the Tensorflow model (see lines 256 to 279).  
Based on this I believe it should not be a problem training our pSp model in Pytorch, saving the projected latents, and feeding them to a Tensorflow model.

**Comment by 5agado** [comment]
Thank you @yuval-alaluf.
I just did some tests, and it seems indeed that the latents are portable to Tensorflow models too. Previously I just made an error on the latent fetching and exporting script.

Thanks again for the reply and great repo. 
Btw, for me all works smoothly on Windows too (just need to have the proper Visual Studio setup for C++ compiling).

**Comment by yuval-alaluf** [comment]
Awesome! Happy to hear!
