### ISSUE TITLE
chinese coder can not download StyleGAN Inversion

### ISSUE THREAD

**Issue by wxzy666** [eladrich/pixel2style2pixel#190]
hello,chinese coder can not download StyleGAN Inversion from https://drive.google.com/file/d/1bMTNWkh5LArlaWSc_wa8VKyq2V42T2z0/view?usp=sharing
can you give a aliyundrive 's link address ,
https://www.aliyundrive.com/
thank you very much !

**Comment by yuval-alaluf** [comment]
We are unfamiliar with aliyundrive and can't really use it since we don't know the language. 
I will be happy to upload the file to Dropbox if that helps.

**Comment by wxzy666** [comment]
No, thanks , I've downloaded it from Google Drive ,It's just too slow
