### ISSUE TITLE
Checkpoint resume!

### ISSUE THREAD

**Issue by scj0709** [eladrich/pixel2style2pixel#192]
Hello! I read your thesis so impressively and tried to train it. 
However, it stopped at 135,000 iterations. So, to resume, use checkpoint_path again to resume, and the step starts from 0. 
If I do this again, is it correct to keep learning?
![image](https://user-images.githubusercontent.com/40060713/132824799-ea804669-6cd1-4473-aaa6-c92c8c1ed395.png)

**Comment by yuval-alaluf** [comment]
It should be fine. We should've probably stored `self.global_step` when saving the checkpoint and then used the saved step when reloading so that it would start at step `135000`. But in any case the training should work fine; the logs will just start at 0 instead of 135,000.
