### ISSUE TITLE
Hi, about this awesome work, I have a question I want to ask.

### ISSUE THREAD

**Issue by meiguoofa** [eladrich/pixel2style2pixel#198]
Since I want to train psp on my sketchtoface dataset different from your training, I should trained it start from scratch or load your pretrained model to train？

**Comment by meiguoofa** [comment]
And How long for trained it from scratch? Looking forward to your reply!!

**Comment by yuval-alaluf** [comment]
Hi @meiguoofa ,
If your sketch data is somewhat similar to the sketch data we used, you should definitely start training from our pre-trained model. It should save you a good amount of time. 
For our published sketch-to-face model, we trained for approximately 3 days if I remember correctly (we trained for a total of 80,000 iterations)

**Comment by meiguoofa** [comment]
Thank you, your reply helped me too much!!

**Comment by meiguoofa** [comment]
@yuval-alaluf  If I want to load your pretrained model to train, but my gpu memory only 12GB,  so it will be affect the final results if I reduce the batch size?

**Comment by yuval-alaluf** [comment]
You can reduce the batch size and it may affect the final results, but probably not by too much. You can reduce the LPIPS lambda according to your batch size. For example, if you are using a batch size of 2, you should set the lambda value to be 0.2.

**Comment by meiguoofa** [comment]
Thanks again, you are so nice, your reply is very helpful to me！！！
