### ISSUE TITLE
Colab Error

### ISSUE THREAD

**Issue by junhyukso** [eladrich/pixel2style2pixel#2]
Hi!
Thanks for your wonderful work.

But, I founded that an error occurs when i execute your colab example, even i did not touch any code.
Error :
![image](https://user-images.githubusercontent.com/41286195/95284340-f3025680-0898-11eb-8fef-1e76d7a4a577.png)

can you please check it?

**Comment by ak9250** [comment]
seems the google drive links arent working to fetch the model anymore also tried gdown with no luck, making a copy of the models to your own drive should work though

**Comment by yuval-alaluf** [comment]
Hi @junhyukso 
The error you received typically occurs when you are unable to fetch the model correctly as @ak9250 noted as well. 
(As a sanity check, verify that the model weighs 1.12GB)
I just tried fetching the celebs_seg_to_face to face model and I was able to load the model successfully so perhaps this was a temporary issue with google drive. 
Please let me know if the problem persists and we'll continue looking into it in the meantime.

**Comment by junhyukso** [comment]
Problem solved. Thanks!

**Comment by Johnson-yue** [comment]
Hi， I still have this problem when `experiment_type = 'toonify'`

**Comment by yuval-alaluf** [comment]
Hi @Johnson-yue 
Can you please verify that you were able to download the model correctly? Please check that the model is indeed approximately 1.12GB and update.

**Comment by yuval-alaluf** [comment]
I just ran the notebook myself and got that the quota was exceeded. At this time, there is no quick solution to this problem as this is a problem with Google Drive itself. I recommend trying to download the model in an hour or two and hopefully you will not get this issue.

**Comment by Johnson-yue** [comment]
yes , the model is only 43k so , I will try downloaded and test again, thank you @yuval-alaluf
