### ISSUE TITLE
Find the latent code of the synthetic image which is identical to the real image in some region?

### ISSUE THREAD

**Issue by tommy-qichang** [eladrich/pixel2style2pixel#204]
Thank you for your great work.
We are doing some experiments based on your code. But we need to find the latent code that the synthetic images are identical to the original one in some regions (we need the latent code of course). So far the PSP model provides a very similar images overall, but we could easily find the differences for the ROI. 

I think there are several options(1. disable noises for each level in generator-stylegan. 2.put more weight on the ROI region, etc), but not sure if I missed any, or it's an impossible mission. 
Could you please shed some light for me?
Thanks.

**Comment by yuval-alaluf** [comment]
The results seem very good to be honest. You could try optimization techniques to try to achieve slightly better reconstruction, but overall I am not sure how much more improvement you will be able to achieve
