### ISSUE TITLE
Training with tag "learn_in_w" returns encoder, which projects to w+ space

### ISSUE THREAD

**Issue by EgorSevriugov** [eladrich/pixel2style2pixel#205]
Thank you for very good implementation. But I have a reason with training PSP model in "learn_in_w" mode. To train I have used dataset_type = ffhq_encode ; encoder_type=GradualStyleEncoder; learn_in_w=True. Other parameters were taken from the example presented in this git repository. The result of training is encoder model which projects images to w+ space instead of w space. Here I mean that output of model is of shape [N_images, n_styles, style_dim] (instead of [N_images, style_dim]) and each of the styles have different values (not simply repeated). As I understand use of encoder_type=GradualStyleEncoder eliminates ability to project to w space?

**Comment by yuval-alaluf** [comment]
You are correct. If you wish to learn in `w` you should used the `BackboneEncoderUsingLastLayerIntoW` encoder type. The `GradualStyleEncoder` is designed specifically to output multiple latent codes.

**Comment by EgorSevriugov** [comment]
Thank you for your answer.
