### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Turtle-hi** [eladrich/pixel2style2pixel#210]
python scripts/train.py \
--dataset_type=celebs_sketch_to_face \
--exp_dir=/path/to/experiment \
--workers=8 \
--batch_size=8 \
--test_batch_size=8 \
--test_workers=8 \
--val_interval=2500 \
--save_interval=5000 \
--encoder_type=GradualStyleEncoder \
--start_from_latent_avg \
--lpips_lambda=0.8 \
--l2_lambda=1 \
--id_lambda=0 \
--w_norm_lambda=0.005 \
--label_nc=1 \
--input_nc=1

**Comment by yuval-alaluf** [comment]
If this is an issue, please provide more details. Otherwise I will close this.
