### ISSUE TITLE
Running on 3090 gpu

### ISSUE THREAD

**Issue by JeonMinkyu** [eladrich/pixel2style2pixel#212]
Hi, thank you for sharing your code.

Can I run this code on rtx-3090 gpu?

My CUDA version is 11.1

I just tried to use environment that you uploaded and made a new environment for pytorch=1.8, python=3.7.

But both of them are not working at all.

In models/stylegan2/op/fused_act.py, 

fused = load(
    'fused',
    sources=[
        os.path.join(module_path, 'fused_bias_act.cpp'),
        os.path.join(module_path, 'fused_bias_act_kernel.cu'),
    ],
)

is not working.

Do you have any idea?

Thank you

**Comment by yuval-alaluf** [comment]
This is a common problem with Ninja. Unfortunately, I do not have a clear solution for how to solve it. From my understanding, there are certain combinations of CUDA and torch that you need for compiling Ninja. Were you able to get it working without updating pytorch?

**Comment by LiUzHiAn** [comment]
Maybe you have to upgrade your g++ version.
