### ISSUE TITLE
Inpainting / Unmasking

### ISSUE THREAD

**Issue by Boyyeo** [eladrich/pixel2style2pixel#213]
Thanks for sharing this excellent work!!
Since I am trying to use psp encoder to reproduce unmasked face with masked face dataset
I think it is similar with the inpainting work but unfortunately the result is not good at all

--lpips_lambda=0.8 \
--l2_lambda=1 \
--id_lambda=0 \
--w_norm_lambda=0.005 \
--input_nc=3 \

I am using the parameter above to train my model, does it suitable for my unmasked project?
Or unmasked project is unsolvable within psp encoder?
Thanks a lot for answering!!

**Comment by yuval-alaluf** [comment]
The parameters in general seem fine and its hard to tell if you have an issue somewhere else. How does your data look like?

**Comment by Boyyeo** [comment]
Thanks for answering my question!!!

######Trained Image#########
![5000](https://user-images.githubusercontent.com/87563842/139875774-e4c78a45-0aad-4d3a-9382-712b0578e344.jpg)

########Tested Image########
![0009_5000](https://user-images.githubusercontent.com/87563842/139875141-2ab4343b-bb2c-4e37-9548-2bd59dd7827b.jpg)

model is trained with almost 50k iteration but using batch_size =2 due to the limitation using google colab
It seems still has a long way to go for predicting the face under the masked dataset

**Comment by yuval-alaluf** [comment]
I do believe solving this with pSp is possible. 
Something with the inputs seems weird. I believe this is contributing to the poor results. Perhaps something strange is happening in your transforms?
