### ISSUE TITLE
can it support for mutil-gpu training ?

### ISSUE THREAD

**Issue by vicentowang** [eladrich/pixel2style2pixel#219]
my gpu memory is 8G and cannot run it even for batch size of 1 with 512x512 resolution. now i got 2 gpu of 8G，how can i get for training? thanks a lot.

**Comment by yuval-alaluf** [comment]
We do not support multi-gpu training but adding this feature should be possible.
Please take a look at: https://github.com/eladrich/pixel2style2pixel/issues/154

**Comment by vicentowang** [comment]
still GPU memory is not enough for two GPU of 8G.
![image](https://user-images.githubusercontent.com/49265512/144568804-7d9c8631-455e-4dae-9e30-1bb63938cb2d.png)
