### ISSUE TITLE
Use own images Sketch to face Notebook?

### ISSUE THREAD

**Issue by Anonymud** [eladrich/pixel2style2pixel#220]
Hello,
first of all great work!!
i have a question on how to use an own sketch in sketch to face. because your image is in a .dat format and i dont know how to use it.
thank you

**Comment by yuval-alaluf** [comment]
Hi, what do you mean by `dat` format? The input images should be standard image files such as jpg and png

**Comment by Anonymud** [comment]
Sorry wrong repo
