### ISSUE TITLE
how to change model

### ISSUE THREAD

**Issue by Le-Cong-Hieu** [eladrich/pixel2style2pixel#222]
hi, thanks for your great article. 
I will need your post to solve my problem. I read that I will have to train a styelgan or stylegan2 model before it can be used in pSp. I am looking for a way to change the default model in your post with my stylegan model. my stylegan model is not about the human face. can you guide me on how to change my existing model ? Thanks for your great contribution.

**Comment by yuval-alaluf** [comment]
The code will load the pre-trained StyleGAN2 generator that is passed using the argument `--stylegan_weights`. You can set this command-line argument to the path for your model. In addition, you can set `--output_size` to the output resolution of your generator. Everything else should remain the same.

**Comment by Le-Cong-Hieu** [comment]
thank you very much. Thank you for your help.
