### ISSUE TITLE
error run train file

### ISSUE THREAD

**Issue by kovalepskaia** [eladrich/pixel2style2pixel#225]
![image](https://user-images.githubusercontent.com/13298750/143670256-0cd0fa1f-89e7-4985-98db-5225c6750ee0.png)

**Comment by yuval-alaluf** [comment]
It seems like you are running on Windows and we do not have built-in support for windows. I know some other people were able to get it up and running on Windows so you could try looking into other issues related to running on Windows.
Hope this helps.
