### ISSUE TITLE
Could I get the "sketch-face" dataset you mentioned in your article?

### ISSUE THREAD

**Issue by gzhhhere** [eladrich/pixel2style2pixel#236]
Hi! Thank you for your excellent work.   Could you please  share the  "sketch-face" data set with me, in whatever way is convenient to you?

**Comment by yuval-alaluf** [comment]
Unfortunately, I am unable to share the sketch dataset due to licensing. However, you can use the following script for recreating the data: 
https://github.com/eladrich/pixel2style2pixel/blob/master/scripts/generate_sketch_data.py

**Comment by gzhhhere** [comment]
> 

Thanks for your quick reply, it will save me a lot of time.  I didn't even notice the script existed.

**Comment by gzhhhere** [comment]
I can run the script on CPU slowly , but when i try it on GPU, it just stuck at line 59 'pred = model.cuda().forward(data.cuda()).float()'.
Have you ever had a similar problem?

**Comment by yuval-alaluf** [comment]
I do remember that problem. Did you make sure you have the torch version specified in the script?

**Comment by gzhhhere** [comment]
yes, i am sure. When i wait it run on GPU, i get "runtimeerror: cublas runtime error : the gpu program failed to execute at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/thc/thcblas.cu:249" ... have no idea about it,

**Comment by gzhhhere** [comment]
i solve the problem by choice a v100 server,  i was using a 3090 before the time.
