### ISSUE TITLE
About the 'Figure 11: Visual comparison of super resolution results on CelebA-HQ.'

### ISSUE THREAD

**Issue by gzhhhere** [eladrich/pixel2style2pixel#237]
Hi!
Could you please tell me how do you train the pix2pixHD model in super resolution tasks? Do you perform random bi-cubic down-sampling or fixed a down sampling factor?  
Thank you !

**Comment by yuval-alaluf** [comment]
We perform a random bi-cubic down-sampling. We provide a command for reproducing the results: 
https://github.com/eladrich/pixel2style2pixel#super-resolution-1
