### ISSUE TITLE
Using Colab playground

### ISSUE THREAD

**Issue by Adjasont256** [eladrich/pixel2style2pixel#238]
Hi, I cannot figure out an error I received while running the code in Colab. I apologize if I made some really basic mistake, I am just starting to learn this field. 
![ErrorStep3](https://user-images.githubusercontent.com/38476723/147722296-3dc36d03-b0d6-4ddb-8bd0-37a2136f86e9.png)

**Comment by yuval-alaluf** [comment]
Seems like there was a problem trying to download the pretrained model. You try running again the previous cells that download the actual model.

**Comment by Adjasont256** [comment]
Ah, thank you. I restarted the runtime and made sure to run the right cells. Apologies for the trouble.
