### ISSUE TITLE
About experiment_type = 'ffhq_frontalize'

### ISSUE THREAD

**Issue by LLFabiann** [eladrich/pixel2style2pixel#239]
The face picture is from this project which locates in notebooks/images/input_img.jpg,
but the face frontalization test result in the right is total black. I guess it's the incorrect weight of pre-training. Can the author check the validity of the Face Frontalization's weight file? Thank you!
![input_img](https://user-images.githubusercontent.com/86837424/148174165-e8a4817c-e837-4e74-834b-6aee2fa2c651.jpg)

**Comment by LLFabiann** [comment]
Can the author check the validity of the Face Frontalization's weight file?Thank you!

**Comment by yuval-alaluf** [comment]
I just ran it and got the correct result. Please verify that everything ran successfully on your end. 
![download](https://user-images.githubusercontent.com/37438467/148505763-374bd037-dfdc-4bce-acdc-335823041e88.png)
