### ISSUE TITLE
using a different stylegan weights

### ISSUE THREAD

**Issue by jis478** [eladrich/pixel2style2pixel#24]
Hi, thanks for the awesome work. 

I'd like to train an encoder using a pre-trained 256x256 stylegan model (https://github.com/rosinality/stylegan2-pytorch) but I'm not sure using this model would be okay for your training code. Since in my case the resolution only goes up to 256, there should be 14x512 latent vectors which are less than your latent vector size, 18x512. My question is, can I still use 256x256 stylegan pre-trained model for this work? 

Thanks in advance.

**Comment by yuval-alaluf** [comment]
Hi @jis478 ,
Yes this is definitely possible!  
Notice that in `psp_encoder.py` we have the following line: 
https://github.com/eladrich/pixel2style2pixel/blob/89935c49f9187e632148dc62a902ab3dfbe4205d/models/encoders/psp_encoders.py#L57

You can change this line to have whatever number of latents you need.  

Just make sure that if you load the average latent, you repeat the vector the correct number of times. That is, you need to adjust the following line: 

https://github.com/eladrich/pixel2style2pixel/blob/89935c49f9187e632148dc62a902ab3dfbe4205d/models/psp.py#L64

There may be some other small modifications that you may need to do, but this should help you get started.

**Comment by berylsheep-up** [comment]
Hello, @yuval-alaluf ! What if I want to use another stylegan weights ranther than the specific stylegan2 weights? Because I found the code is only for stylegan2 model. Would I use the official stylegan weights to train the psp?

**Comment by yuval-alaluf** [comment]
The StyleGAN model that you use must be compatible with [rosinality's](https://github.com/rosinality/stylegan2-pytorch) StyleGAN implementation. Therefore, you may use models that are trained using either: 
1. rosinality's pytorch repository
2. NVIDIA's official tensorflow respository (https://github.com/NVlabs/stylegan2 or https://github.com/NVlabs/stylegan2-ada) and are then converted to pytorch using rosinality's conversion script.

**Comment by xjw00654** [comment]
I have tested another [stylegan2](https://github.com/Tetratrio/stylegan2_pytorch) implementation by [Tetratrio](https://github.com/Tetratrio). It just take a little modification of the codes (just replace the `Generator` class).

**Comment by yuval-alaluf** [comment]
Thanks for the input @xjw00654 !  
Based on this, you may find it possible to use weights from different sources by making the necessary adjustments to the code.  
I am closing this issue for now as I believe the question has been answered.

**Comment by rafaelbou** [comment]
Hi everyone!
I'm also trying to train pSp on my own dataset (not faces). 
@jis478 how did you calculate the number of the style count, why for 256 image size the style count is 14?

In general, I'll be happy for any conclusions form your training experience.

Thanks :)

**Comment by yuval-alaluf** [comment]
Note that the number of style vectors can be computed by 
```n_styles = int(math.log(self.opts.output_size, 2)) * 2 - 2``` 
For example, for a 1024x1024 output resolution we have 18 style vectors while for a resolution of 256x256 we have 14 style vectors.

**Comment by markemus** [comment]
The final missing piece here; do you also support the more recent Pytorch implementation of [Stylegan2-ADA-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch)? The authors indicate that it is compatible with pickles from the old repo but I don't know if it works the other way around.

**Comment by yuval-alaluf** [comment]
> The final missing piece here; do you also support the more recent Pytorch implementation of [Stylegan2-ADA-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch)? The authors indicate that it is compatible with pickles from the old repo but I don't know if it works the other way around.

Sure. Just like you can convert the official tensorflow StyleGAN2 weights using rosinality's pytorch repository, you can do the same with stylegan-ada and it should work as is. 
Heres the script: 
https://github.com/rosinality/stylegan2-pytorch#convert-weight-from-official-checkpoints
Let us know if you come across any issues.

**Comment by yuval-alaluf** [comment]
> The final missing piece here; do you also support the more recent Pytorch implementation of [Stylegan2-ADA-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch)? The authors indicate that it is compatible with pickles from the old repo but I don't know if it works the other way around.

I realized I misread your original post where you mentioned that you used the recent pytorch implementation. We actually haven't tried it, but I feel like it won't work out-of-the-box because the names of the model parameters will most likely be different than what is used in rosinality's pytorch stylegan implementation (which is what we use here).  
However, if you replace the `Generator` class used in this repository with the `Generator` used in  [Stylegan2-ADA-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch) I believe it should work.

**Comment by markemus** [comment]
I tested a stylegan2-ada-pytorch pickle and it doesn't work with rosinality's conversion script unfortunately- it crashes trying to load from `torch_utils` (which only exists in the stylegan2-ada-pytorch repo). Oh well :) 

I will see if I can get the Generator approach working instead.

**Comment by yuval-alaluf** [comment]
> I tested a stylegan2-ada-pytorch pickle and it doesn't work with rosinality's conversion script unfortunately- it crashes trying to load from `torch_utils` (which only exists in the stylegan2-ada-pytorch repo). Oh well :)
> 
> I will see if I can get the Generator approach working instead.

Right. The conversion script will work on the tensorflow code for StyleGAN2 and ADA. But for the new pytorch code more changes will be needed. Looking forward to an update if you get it to work!
