### ISSUE TITLE
Can I use different output image resolution?

### ISSUE THREAD

**Issue by vgthengane** [eladrich/pixel2style2pixel#241]
I am working on a car shadow generation and I have an image of size 1200x1600 pixel. Can I use the same model for the shadow generation task on a 1200x1600 pixel image?

**Comment by yuval-alaluf** [comment]
If you want to generate a `1200x1600` resolution image with StyleGAN, all you need is a StyleGAN generator that outputs images at that resolution. Our pSp encoder should be compatible with any resolution generator.

**Comment by vgthengane** [comment]
Hi @yuval-alaluf Thank you for your reply. 

Since I am working on a non-facial domain and by following your comment [here](https://github.com/yuval-alaluf/restyle-encoder/issues/48), I am trying out the Restart-Encoder for the image-to-image translation task. What are the necessary changes I need to make in order to use it for the image-to-image translation tasks? 

I started with changing source and target data (car image with and without shadow), But I ran into the following error. At the moment I am using `256x256` image size.

```
File "./training/coach_restyle_psp.py", line 111, in perform_train_iteration_on_batch
    y_hats[idx].append([y_hat[idx], id_logs[idx]['diff_target']])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by vgthengane** [comment]
Update: I found the issue with the error, It was because I did `--id_lambda=0` and did not set `--moco_lambda=0.5`. It is solved. 
 
Now, I just want to know I am on the right path to do the image-to-image translation.

**Comment by yuval-alaluf** [comment]
You seem to be on the right track for performing the image-to-image translation. Pretty much the only difference you need to make is in the data that you define during training, which seems like you have done. 
> Also, How to get a latent_avg for transparent image i.e num_channels == 4?  

To obtain the latent average, you can use the following line:
```
self.net.latent_avg = self.net.decoder.mean_latent(int(1e5))[0].detach()
```
The latent average is dependent on the generator and not the number of input channels of your data.

**Comment by vgthengane** [comment]
Since StyleGAN produce 3 channel output, does it mean I will not be able to generate images of 4-channels with a restyle-encoder? I am bit confused here.

**Comment by yuval-alaluf** [comment]
You can generate images that StyleGAN knows how to generate. If StyleGAN can only generate 3-channel images then you will be able to generate 3 channel outputs.
