### ISSUE TITLE
Colab Pre-Trained Model Download

### ISSUE THREAD

**Issue by Eyvaz27** [eladrich/pixel2style2pixel#246]
When running colab notebook, download Command ( " !{download_command} " ) is giving the following error:

--2022-01-21 10:06:50--  https://docs.google.com/uc?export=download&confirm=&id=1bMTNWkh5LArlaWSc_wa8VKyq2V42T2z0
Resolving docs.google.com (docs.google.com)... 173.194.196.100, 173.194.196.101, 173.194.196.113, ...
Connecting to docs.google.com (docs.google.com)|173.194.196.100|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-01-21 10:06:50 ERROR 404: Not Found.

**Comment by guialbquerque** [comment]
I have the same error: https://docs.google.com/uc?export=download&confirm=&id=1bMTNWkh5LArlaWSc_wa8VKyq2V42T2z0
Resolving docs.google.com (docs.google.com)... 173.194.196.100, 173.194.196.101, 173.194.196.113, ...
Connecting to docs.google.com (docs.google.com)|173.194.196.100|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-01-21 10:06:50 ERROR 404: Not Found.

Please, release the downloads, i really need for a project in college!

**Comment by Lucas-Rufino** [comment]
I've run the `download-weights.sh` script, and only the `shape_predictor_68_face_landmarks` pre-trained model has downloaded correctly. 😢 

```
(base) ➜  pixel2style2pixel git:(master) sudo bash download-weights.sh
--2022-01-21 21:06:28--  https://docs.google.com/uc?export=download&confirm=&id=1lB7wk7MwtdxL-LL4Z_T76DuCfk00aSXA
Resolving docs.google.com (docs.google.com)... 142.250.79.14
Connecting to docs.google.com (docs.google.com)|142.250.79.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-01-21 21:06:29 ERROR 404: Not Found.

--2022-01-21 21:06:30--  https://docs.google.com/uc?export=download&confirm=&id=1_S4THAzXb-97DbpXmanjHtXRyKxqjARv
Resolving docs.google.com (docs.google.com)... 142.250.79.14
Connecting to docs.google.com (docs.google.com)|142.250.79.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-01-21 21:06:30 ERROR 404: Not Found.

--2022-01-21 21:06:31--  https://docs.google.com/uc?export=download&confirm=&id=1ZpmSXBpJ9pFEov6-jjQstAlfYbkebECu
Resolving docs.google.com (docs.google.com)... 142.250.79.14
Connecting to docs.google.com (docs.google.com)|142.250.79.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-01-21 21:06:31 ERROR 404: Not Found.

--2022-01-21 21:06:32--  https://docs.google.com/uc?export=download&confirm=&id=1YKoiVuFaqdvzDP5CZaqa3k5phL-VDmyz
Resolving docs.google.com (docs.google.com)... 142.250.79.14
Connecting to docs.google.com (docs.google.com)|142.250.79.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-01-21 21:06:32 ERROR 404: Not Found.

--2022-01-21 21:06:32--  http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
Resolving dlib.net (dlib.net)... 107.180.26.78
Connecting to dlib.net (dlib.net)|107.180.26.78|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64040097 (61M)
Saving to: ‘shape_predictor_68_face_landmarks.dat.bz2’

shape_predictor_68_face_landm 100%[=================================================>]  61.07M  16.1MB/s    in 3.8s

2022-01-21 21:06:40 (16.1 MB/s) - ‘shape_predictor_68_face_landmarks.dat.bz2’ saved [64040097/64040097]
```

**Comment by yuval-alaluf** [comment]
Hi everyone, it seems like Google blocked the account temporarily, but it should be fixed now. I was just able to download one of the pre-trained models.
If the issue persists, please let me know.

**Comment by Eyvaz27** [comment]
I think it is working smoothly now.

**Comment by Lucas-Rufino** [comment]
It's working! Thanks for all! 🌟

**Comment by guialbquerque** [comment]
Thank you sir, it’s working!
