### ISSUE TITLE
How to use stylegan2-ada-pytorch model?

### ISSUE THREAD

**Issue by fugokidi** [eladrich/pixel2style2pixel#247]
Thank you for the interesting work.
I tried to use a pretrained model from [stylegan2-ada-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch).
I converted .pkl file to work with legacy networks according to the instructions.
The loaded generator module is different from the stylegan2 decoder in psp.
May I know what to modify to make psp work with stylegan2-ada-pytorch.
Thank you.

**Comment by yuval-alaluf** [comment]
Please see the details provided here on correctly preparing your generator:
https://github.com/yuval-alaluf/restyle-encoder#preparing-your-generator
(The same details also apply here to pSp)

**Comment by fugokidi** [comment]
@yuval-alaluf Thank you. It works perfectly.
