### ISSUE TITLE
Conda environment error

### ISSUE THREAD

**Issue by spamfold3r** [eladrich/pixel2style2pixel#25]
Hello

I am receiving an error when running this via jupyter notebook. I have installed the specified torch/torchvision versions from the .yaml (along with everything else) to my conda environment and even uninstalled/reinstalled to check. Is this error something to do with the conflicting and 'incompatible' versions listed in the .yaml or have I missed out something when installing them into the conda environment? I am new to both linux and gan/ml work.

Cheers!

![Screenshot from 2020-11-02 10-53-44](https://user-images.githubusercontent.com/73826746/97860241-b855d780-1cf9-11eb-8da0-4a5a123a5752.png)

**Comment by yuval-alaluf** [comment]
Hi @spamfold3r , 
My guess is that you did not activate the conda environment when starting the jupyter notebook. As a quick sanity check, can you please run 
```
!which python
```
in a cell in the notebook.  
Let's check that you are indeed using the conda environment you installed.

**Comment by spamfold3r** [comment]
Hello @yuval-alaluf , thanks for the reply!

I have been careful to install things inside the environment as I go along.

![Screenshot from 2020-11-02 11-33-19](https://user-images.githubusercontent.com/73826746/97863696-4da79a80-1cff-11eb-9d85-bd978123bd05.png)

**Comment by yuval-alaluf** [comment]
Yea looks good...
I did a quick search and it seems like one possibility for the issue you're having is that you need to install jupyter inside your conda environment.  
Can you try activating you're psp_env and run `conda install jupyter` and try re-running jupyter.   
I personally have not come across the issue in the past, but if the above doesn't work we can look into other potential solutions.

**Comment by spamfold3r** [comment]
Brilliant, thanks for your help! I've got it up and running.
I ran into a few issues with CUDA and then with dlib and cmake but all worked out in the end. :smile:
