### ISSUE TITLE
Training a toonify model with unpaired data

### ISSUE THREAD

**Issue by leslie-ds** [eladrich/pixel2style2pixel#251]
Thanks for the excellent work. 
How to train a toonify model with unpaired data?
![Screenshot from 2022-02-09 14-37-00](https://user-images.githubusercontent.com/72796432/153135445-de6abf30-9308-468f-86a2-faf5cb525a3f.png)

**Comment by yuval-alaluf** [comment]
Please take a look at the readme: https://github.com/eladrich/pixel2style2pixel#toonify
