### ISSUE TITLE
Couple of question about pair image training

### ISSUE THREAD

**Issue by olegkorshunov** [eladrich/pixel2style2pixel#253]
Thank for your excellent work!
 I am generated pairs image use generator from stylegan2(stylegan2-metfaces-1024x1024.pkl). I have 3800 images in training dataset and 100 images in testing dataset I use ffhq and celebia dataset respectively.
1) Is this amount of data enough? or I need to generate more data? and as I understand when we saved the best model we look at test data and for it I need generate more than 100 images?

My source images have resolution 256x256 and target 4680x4680,

I added this transofrms
```python
        transforms_dict = {
            "transform_gt_train": transforms.Compose(
                [
                    transforms.Resize((256, 256)),
                    transforms.ToTensor(),
                    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
                ]
            ),
            "transform_source": transforms.Compose(
                [
                    transforms.Resize((256, 256)),
                    transforms.ToTensor(),
                    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
                ]
            ),
            "transform_test": transforms.Compose(
                [
                    transforms.Resize((256, 256)),
                    transforms.ToTensor(),
                    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
                ]
            ),
            "transform_inference": transforms.Compose(
                [
                    transforms.Resize((256, 256)),
                    transforms.ToTensor(),
                    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
                ]
            ),
        }
```
2) Are these transformations normal? or I should change transform_gt_train and transform_inference to 1024x1024? and can I add some augmentation for example noise? 
3) and can you look at my learning parameters should I change anything? 
```
python scripts/train.py \
--dataset_type=metaface \
--exp_dir=./experiment \
--workers=2 \
--batch_size=2 \
--test_batch_size=2 \
--test_workers=2 \
--val_interval=2500 \
--save_interval=5000 \
--encoder_type=GradualStyleEncoder \
--start_from_latent_avg \
--lpips_lambda=0.08 \
--l2_lambda=0.001 \
--lpips_lambda_crop=0.8 \
--l2_lambda_crop=0.01 \
--id_lambda=1 \
--w_norm_lambda=0.025 \
--stylegan_weights=./pretrained_models/stylegan2-metfaces-1024x1024.pt 
```
after 20000 steps I have this result I think this is not bad but maybe you can give me some advice about training params
![1855_20000](https://user-images.githubusercontent.com/44620818/153500956-3eeeefcf-13b1-4a90-b524-17394e42631e.jpg)

**Comment by yuval-alaluf** [comment]
> Is this amount of data enough? 

You should probably want more data. if you're generating it with randomly generated samples of StyleGAN, couldn't you technically generate an endless collection of paired samples? 

> Are these transformations normal?

These look like standard transforms. They look fine. 

> can I add some augmentation for example noise?

Sure. You can add any augmentations you'd like.

> can you look at my learning parameters should I change anything?

The L2 lambda is quite low. Try increasing the lambda and retrying. My best advice is to try to overfit a small set of images (e.g., 10) to find the parameters. And then training on all your data.
