### ISSUE TITLE
About cosine similarity

### ISSUE THREAD

**Issue by sicong-li** [eladrich/pixel2style2pixel#254]
In your code :https://github.com/eladrich/pixel2style2pixel/blob/master/criteria/id_loss.py#L33 
as is well-know: `Similarity = (A.B) / (||A||.||B||) `
why there have not divided by `norm(y_hat_feats[i]) * norm(y_feats[i]) ?`

**Comment by yuval-alaluf** [comment]
The vectors are already normalized before computing their dot product
