### ISSUE TITLE
Training time for the provided pretrained models

### ISSUE THREAD

**Issue by shivangi-aneja** [eladrich/pixel2style2pixel#255]
I was wondering if you could provide me with some statistics about how much time it took for you to train these models. More specifically, if you could provide GPU hours and hardware architecture used for training the pSp (SyleGAN Inversion) on the FFHQ dataset, it would be really helpful. I already wrote an email regarding this, feel free to revert there.

**Comment by yuval-alaluf** [comment]
We ran our inversion experiments with a single P40 GPU for 300,000 iterations. I don't recall how many days this turns out to be.

**Comment by shivangi-aneja** [comment]
Many thanks for quick response :)
