### ISSUE TITLE
Generated pair images

### ISSUE THREAD

**Issue by simplecode123** [eladrich/pixel2style2pixel#256]
Hi, if I used pretrained model from [stylegan2-ada-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch) what is better way to generated pair images for training psp model?

**Comment by yuval-alaluf** [comment]
Depends on what you mean by paired images. Can you provide an example of what you're trying to do?

**Comment by simplecode123** [comment]
I want to train psp model on pair image use uses ---stylegan_weights, like in issue #39, but when I use this script 
```
projector.py --outdir=out --target=~/mytargetimg.png \
    --network=https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/ffhq.pkl 
```
from [stylegan2-ada-pytorch](https://github.com/dvschultz/stylegan2-ada-pytorch) it is work too slow :disappointed:

**Comment by yuval-alaluf** [comment]
But this projector script is running optimization to reconstruct your input image. What kind of paired data are you trying to generate here by using optimization?

**Comment by simplecode123** [comment]
Yes, you are right and therefore I think that I am not using the optimal approach for generating paired images, for example, I also tried to generate paired images using models from this repository [Cartoon-StyleGAN](https://github.com/happy-jihye/Cartoon-StyleGAN)
```
python projector.py --ckpt networks/Disney_StructureLoss.pt --file 000129.jpg
```
and got this result
![000132-project-interpolation](https://user-images.githubusercontent.com/89580113/154351764-1f1665e0-7ce3-4f85-9046-7b5cc026c033.png)
![000132](https://user-images.githubusercontent.com/89580113/154351797-81f62550-83f3-4efd-bdee-0d042d103f47.jpg)

**Comment by yuval-alaluf** [comment]
I am not too familiar with the repo you linked above, but why not randomly sample a latent code and then pass the same latent code to the FFHQ generator and your cartoon generator? This will generate paired images in the two "styles"
