### ISSUE TITLE
How to adapt pSp framework towards gansformer generator with different z input_shape ?

### ISSUE THREAD

**Issue by lxj616** [eladrich/pixel2style2pixel#258]
Hi, there are other stylegan-like models eg. gansformer (github.com/dorarad/gansformer) assumed suitable for pSp framework

But after some research, I found some currently incompatible stuff

1. gansformer generator has a z of [1, 9, 64] input_shape, not 512
2. the above shape is caused by `Add an additional global latent (--style) to the k latent components, such that first the global latent modulates all the image features uniformly, and then the k latents modulate different regions based on the bipartite transformer's attention.` , I assume they divide the original 512 size into 8 component groups then add one global to a total of [1, 9, 64]
3. so if the z is not any longer a global 512 size, does pSp encoder still works in the same way ?

I found it hard for me to directly modify the network and test it without help (I am not sure replace every 512 with 576 then passing [1, 9, 64] to the generator is a good idea), could you share some expertise on how to make it work ?

thanks

**Comment by yuval-alaluf** [comment]
I am unfamiliar with the inner workings of ganformer so if you want to adjust pSp to ganformer, you're most likely on your own here. 

Basically, if you understand what the generator's expected input is, you can change the last layer of the encoder to match this expected input size. Other than that, everything else could more or less stay the same (other than some minor tweaks). 

That is how I would try to go about this: understand what the generator is supposed to get and then modify the last encoder layer accordingly.

**Comment by lxj616** [comment]
Thank you for the reply, I'll give it a try accordingly
