### ISSUE TITLE
Question about Toonificaiton

### ISSUE THREAD

**Issue by jsaisagar** [eladrich/pixel2style2pixel#261]
Hi,

There are many starting points to generate cartoon from input image. I was wondering, can we do reverse i.e. cartoon to real images? What issues we might need to address this problem? A cartoon image can have artifacts like large eyes and smooth textures. However, real image might not! 
Is going from cartoon to real domain, a similar problem to going from real to cartoon domain?

**Comment by yuval-alaluf** [comment]
It's definitely possible and some people have tried this. 
The simplest approach requires no training at all. Just pass your aligned cartoon face image to the pretrained encoder and you will get the closest realistic face resembling the cartoon. To do this, I would recommend even trying to use the e4e encoder from here: https://github.com/omertov/encoder4editing
e4e encodes images closer to W and will therefore lead to some more realistic faces compared to doing the same procedure with pSp.
