### ISSUE TITLE
when i run the inference_playground.ipynb, the program is stuck

### ISSUE THREAD

**Issue by caskr** [eladrich/pixel2style2pixel#265]
when i run the inference_playground.ipynb, the program is stuck in the code
"from models.psp import pSp"
i think is the problem on the op, but i don't know how to solve with it.

**Comment by yuval-alaluf** [comment]
Are you running this on Colab or on your own computer?

**Comment by caskr** [comment]
On my school's server. i didn't meet with the problem at first, but after running it for some times, it stuck there.

**Comment by yuval-alaluf** [comment]
Try seeing if this can help solve your problem: 
https://github.com/eladrich/pixel2style2pixel/issues/80#issuecomment-778637066

**Comment by caskr** [comment]
> Try seeing if this can help solve your problem: [#80 (comment)](https://github.com/eladrich/pixel2style2pixel/issues/80#issuecomment-778637066)

This works for me!! Thanks a lot for helping!!!
