### ISSUE TITLE
Error loading the model in Colab

### ISSUE THREAD

**Issue by Ihsin-Chen** [eladrich/pixel2style2pixel#267]
The notebook could work properly about a month ago, but it failed to load the model today.
![image](https://user-images.githubusercontent.com/76651020/165561930-1c2ef811-07c8-46ab-9729-192305bb4aee.png)

The error occurs when I simply run all cells at a time.

**Comment by yuval-alaluf** [comment]
I just range this myself. If you try to open the`pt` file that was downloaded, you will see that it contains the following text: 
```
<!DOCTYPE html><html><head><title>Google Drive - Quota exceeded</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="XDMu4JrsMcHJzcR0gdWQ7Q">/* Copyright 2022 Google Inc. All Rights Reserved. */
...
p class="uc-error-subcaption">Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.</p></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
```
Unfortunately, too many people have tried downloading the model recently and the quota has been exceeded. There is nothing we can really do here since Google Drive has blocked any additional downloads.

One possible option is to try downloading the model with `gdown` instead of using the `wget` command that is currently used in the notebook.

**Comment by Ihsin-Chen** [comment]
Thanks for replying so quickly！ How long does it usually take to recover from exceeding the quota ？

**Comment by yuval-alaluf** [comment]
Hard to say. Sometimes it's an hour and sometimes it's a day. I would try using gdown instead for now. That should work I believe

**Comment by Ihsin-Chen** [comment]
Actually I've changed the download command from `wget` to `gdown` but still got same error. : 

![image](https://user-images.githubusercontent.com/76651020/165779890-4a428a4c-47a0-4e6d-a6f2-33936a619611.png)

**Comment by yuval-alaluf** [comment]
That command is not related to the downloading of the model.  
If `gdown` doesn't work, you can also try downloading with `pydrive` or save the model to your own Drive account.

**Comment by Ihsin-Chen** [comment]
It can work properly now ! 
Thank you very much for the help !
