### ISSUE TITLE
About customizing datasets

### ISSUE THREAD

**Issue by Luffffffy** [eladrich/pixel2style2pixel#268]
Hi, thank you for sharing such a great job

I encountered some questions during the use：

1，Can this framework only work on face images? can it be other images? such as cat and dog.

2，If I can, I should build training and test datasets, and how should they be structured.
      for example, I have some sketches and real images of dogs. which training method should I use in this tutorial.
      choose "Training pSp", or "Training the pSp Encoder", or something else.

Thank you in advance

**Comment by yuval-alaluf** [comment]
> 1，Can this framework only work on face images? can it be other images? such as cat and dog.

In the paper we showed results on different domains including cats and dogs. In general, pSp is generic. If you have a high-quality SG generator for a specific domain, you can train an encoder for that domain. 

> If I can, I should build training and test datasets, and how should they be structured.

This depends on the image-to-image task you want to solve. If you said that you have pairs of (real dog, sketch dog) then you should train a sketch-to-image model.  And you can follow the idea here to get started: https://github.com/eladrich/pixel2style2pixel#sketch-to-face

**Comment by Luffffffy** [comment]
This is my task：from sketched package image to real image

![image](https://user-images.githubusercontent.com/49063302/165878437-3afc0425-6389-4e03-aa2a-9dc13d328a5f.png)

started here： https://github.com/eladrich/pixel2style2pixel#sketch-to-face

But I got this situation. It looks a little abnormal

**Comment by yuval-alaluf** [comment]
Are you using a SG generator for faces? You need to first train a SG generator for your real handbag images.

**Comment by Luffffffy** [comment]
Thank you for your reply
