### ISSUE TITLE
Have you tried multi-GPU training successfully?

### ISSUE THREAD

**Issue by yangzhaojason** [eladrich/pixel2style2pixel#27]

**Comment by yuval-alaluf** [comment]
Yes. We have tried training with multiple GPUs and while this is definitely possible with minimal modifications of the code, we find that training with multiple GPUs doesn't provide much added benefit in terms of training time. For example, we found that training with 2 GPUs for example is only slightly faster than training with 1 GPU.  
With that said, we tried using `DataParallel` for multi-GPU training. There may be better options available, but we have not explored them thoroughly.  
You are welcome to try to implement this feature and open a pull request 😄

**Comment by yangzhaojason** [comment]
> Yes. We have tried training with multiple GPUs and while this is definitely possible with minimal modifications of the code, we find that training with multiple GPUs doesn't provide much added benefit in terms of training time. For example, we found that training with 2 GPUs for example is only slightly faster than training with 1 GPU.
> With that said, we tried using `DataParallel` for multi-GPU training. There may be better options available, but we have not explored them thoroughly.
> You are welcome to try to implement this feature and open a pull request 😄

haha,ok. I'm trying to use Apex to speed up training, and when it's stable, I can share.

**Comment by yuval-alaluf** [comment]
Awesome

**Comment by cyprian** [comment]
@yangzhaojason were you able to successfully implement APEX?

**Comment by mmiaz** [comment]
@yangzhaojason Hi, also curious here, were you able to successfully implement APEX?
