### ISSUE TITLE
ninja

### ISSUE THREAD

**Issue by Transformer-man** [eladrich/pixel2style2pixel#270]
/bin/sh: 1: :/usr/local/cuda-11.6/bin/nvcc: not found
ninja: build stopped: subcommand failed.

**Comment by yuval-alaluf** [comment]
Please take a look at the numerous similar issues related to ninja.

**Comment by Transformer-man** [comment]
I would like to ask whether the code base can be in rtx3090, cuda11 6？You can write an example of what the environment needs requirements.txt so that we can easily install relevant libraries, such as 
pip install -r requirements.txt

**Comment by Transformer-man** [comment]
my torch==1.8.1 and torchvision==0.9.1,I've been having problems and I'm about to cry

**Comment by yuval-alaluf** [comment]
We provided a complete anaconda environment with the repo. We use CUDA 11.1 so your GPU and CUDA should be fine.

**Comment by Transformer-man** [comment]
Because I'm a novice, can you tell me how to install your environment? Thank you.

**Comment by Transformer-man** [comment]
This problem is so stupid that I have solved it. thank you

**Comment by yuval-alaluf** [comment]
To create the environment you can run:
`conda env create --file environment/psp_env.yaml`

**Comment by Transformer-man** [comment]
Thank you for your reply

**Comment by jiazhiguan** [comment]
> This problem is so stupid that I have solved it. thank you

Hi, I have the same problem but am still stuck here ...  Could you help me out?

**Comment by Transformer-man** [comment]
@jiazhiguan 
conda env create --file environment/psp_env.yaml 
you can use this

**Comment by jiazhiguan** [comment]
> @jiazhiguan conda env create --file environment/psp_env.yaml you can use this

Thx. I figure out the problem is related to the $CUDA_HOME in ~/.bashrc

change from `export CUDA_HOME="$CUDA_HOME:/usr/local/cuda"` to `export CUDA_HOME="/usr/local/cuda"` works for me.
