### ISSUE TITLE
Images plotted when training for super-resolution task does not look like downsampled

### ISSUE THREAD

**Issue by catherineyeh** [eladrich/pixel2style2pixel#272]
Hi all,
I've tried to perform the super-resolution task with a trained stylegan2-ada-pytorch as the generator. However when training, the images stored in the checkpoints folder look like this below:
![sr_1200](https://user-images.githubusercontent.com/33914784/169121678-cabe77c7-358a-41fd-a290-190de25700fa.jpg)

I'm not entirely sure if the image under "Inputs" are downsampled correctly when training. Could it be that the transformations/preprocessing steps need to be modified? The training images were greyscale 256x256.

**Comment by yuval-alaluf** [comment]
> Could it be that the transformations/preprocessing steps need to be modified?

I believe that it could be that the `BilinearResize` assumes the image has three channels and you are giving it a single channel input. You can try converting your grayscale images to RGB (using something like `Image.open("image.png").convert("RGB")` and if that doesn't work, you could try replacing the `BilinearResize` with a different downsampling function that behaves correctly.
