### ISSUE TITLE
adout inference

### ISSUE THREAD

**Issue by Luffffffy** [eladrich/pixel2style2pixel#274]
I observed that using the same sketch cat image, the verification output in training and the inference results are different

![image](https://user-images.githubusercontent.com/49063302/170650138-d849b043-6561-48c2-b996-2e72de000399.png)
![image](https://user-images.githubusercontent.com/49063302/170650220-a2c1cf33-118a-478c-97fe-9e3925d5d09b.png)

I guess it may be that the training and inference use different hyperparameters. 
How can I get the same result as the verification set when inference.
Thanks!!!

**Comment by yuval-alaluf** [comment]
The difference is that in training there is no style mixing performing during training while in inference style mixing is performed. If you want to get similar results in training and inference you can either add the style mixing to training (which I don't recommend), or remove it from the inference script to verify that you get the same results as in the training script.

**Comment by Luffffffy** [comment]
Thanks for your reply, I understand
