### ISSUE TITLE
How to finetune the encoder pretrained on ffhq by other face dataset?

### ISSUE THREAD

**Issue by 3maoyap** [eladrich/pixel2style2pixel#275]

**Comment by yuval-alaluf** [comment]
After you have set up your new dataset, you can simply run the training script and add the flag `--checkpoint_path` to the pretrained encoder.
For details on how to prepare your data for training see here: 
https://github.com/eladrich/pixel2style2pixel#preparing-your-data

**Comment by li-car-fei** [comment]
> After you have set up your new dataset, you can simply run the training script and add the flag `--checkpoint_path` to the pretrained encoder. For details on how to prepare your data for training see here: https://github.com/eladrich/pixel2style2pixel#preparing-your-data


If my data set is only a few, maybe about ten, can I finetune the psp model so that it can complete the inversion ？
