### ISSUE TITLE
get error when I run inference, the problem maybe about ninja ?

### ISSUE THREAD

**Issue by li-car-fei** [eladrich/pixel2style2pixel#276]
`RuntimeError: Error building extension 'fused': [1/2] /usr/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/bishe/anaconda3/envs/LJH_psp_env/lib/python3.6/site-packages/torch/include -isystem /home/bishe/anaconda3/envs/LJH_psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/bishe/anaconda3/envs/LJH_psp_env/lib/python3.6/site-packages/torch/include/TH -isystem /home/bishe/anaconda3/envs/LJH_psp_env/lib/python3.6/site-packages/torch/include/THC -isystem /home/bishe/anaconda3/envs/LJH_psp_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/bishe/LJH/pixel2style2pixel/models/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/usr/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/bishe/anaconda3/envs/LJH_psp_env/lib/python3.6/site-packages/torch/include -isystem /home/bishe/anaconda3/envs/LJH_psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/bishe/anaconda3/envs/LJH_psp_env/lib/python3.6/site-packages/torch/include/TH -isystem /home/bishe/anaconda3/envs/LJH_psp_env/lib/python3.6/site-packages/torch/include/THC -isystem /home/bishe/anaconda3/envs/LJH_psp_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/bishe/LJH/pixel2style2pixel/models/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
nvcc fatal   : Value 'c++14' is not defined for option 'std'
ninja: build stopped: subcommand failed.`

**Comment by yuval-alaluf** [comment]
Hi, this could be a mismatch between your pytorch version and cuda version. Can you provide more details regarding your pytorch version and environment?

**Comment by li-car-fei** [comment]
> Hi, this could be a mismatch between your pytorch version and cuda version. Can you provide more details regarding your pytorch version and environment?

when I use the environment you provided, I get error like this:
`AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.`
