### ISSUE TITLE
About Image interpolation

### ISSUE THREAD

**Issue by JNash123** [eladrich/pixel2style2pixel#277]
Sorry, I have checked all the issues, but no one asked this question, I wonder how to do image interpolation? Thank u

**Comment by yuval-alaluf** [comment]
To interpolate two vectors `a` and `b` you can define their interpolation as: 
`alpha * a + (1 - alpha) * b` for various values of `alpha`.
You can take a look at the animations notebook in the ReStyle repo for an example: 
http://colab.research.google.com/github/yuval-alaluf/restyle-encoder/blob/master/notebooks/animations_playground.ipynb

**Comment by JNash123** [comment]
thank u, i got it
