### ISSUE TITLE
About Image quality

### ISSUE THREAD

**Issue by JNash123** [eladrich/pixel2style2pixel#279]
I use the FFHQ dataset for training and the CelebA-HQ dataset for evaluation. But the results aren't good enough. Can u give me some advices
![000025](https://user-images.githubusercontent.com/29653541/174561918-9078cd9e-6c01-4672-b846-32b944448b32.jpg)

**Comment by yuval-alaluf** [comment]
How do you define "good enough"?

**Comment by yuval-alaluf** [comment]
The results looks very reasonable for pSp. If you are not satisfied you can try running inference using ReStyle, HyperStyle, or PTI
