### ISSUE TITLE
Colab Sketch To Face not working as expected

### ISSUE THREAD

**Issue by etienneshrdlu** [eladrich/pixel2style2pixel#28]
I've been playing with the Google Colab notebook and everything seems to be working fine with the celebs_sketch_to_face model, but if I change the sketch image path to my own source image, the output is always the same default image and doesn't seem to bear any resemblance to the source sketch. Is this maybe a file naming issue? I've tried various combinations of file names, and JPG or PNG formats, and nothing seems to resolve it.

**Comment by yuval-alaluf** [comment]
Hi @etienneshrdlu , 
Would you mind sending an example of a source image you tried and the result you got?

**Comment by etienneshrdlu** [comment]
Sure thing - whatever source image I use, it always ends up on some variant of the output here.
![Unknown-1](https://user-images.githubusercontent.com/73829148/97997102-853a4380-1de0-11eb-9774-ba462e086cb7.png)

**Comment by yuval-alaluf** [comment]
A few things: 
1. You may need to align the image you are running on.   
2. More importantly, the sketch you showed here is quite different than the data that the sketch-to-image model was trained on. Therefore, you may not get satisfiable results using this model. 

With that said, the sketch you provided may obtained better results if you pass it through the regular encoder model (ffhq_encode), but this too is not necessarily true as the data is again quite different than what the encoder was trained on, but you are welcome to give it a try.

**Comment by etienneshrdlu** [comment]
Brilliant, thanks for the advice :)
