### ISSUE TITLE
About face_pool

### ISSUE THREAD

**Issue by zhongtao93** [eladrich/pixel2style2pixel#281]
Hi, thank for sharing great work~
I have some question about psp final resize, which is show as below:
https://github.com/eladrich/pixel2style2pixel/blob/334f45e43335e92822744849a546c82e1cc47bb3/models/psp.py#L32
Why use torch.nn.AdaptiveAvgPool2d instead of torch.nn.functional.interpolate.
Hoping for your reply!

**Comment by yuval-alaluf** [comment]
The difference two should probably be negligible so you could use either.
We simply used `AdaptiveAvgPool2d` since that is what is most commonly used from my experience. 
You just need to make sure that the function is differentiable.
