### ISSUE TITLE
How to train face frontalized  model with compressed size , How much FFHQ data is needed for training the same

### ISSUE THREAD

**Issue by abdul756** [eladrich/pixel2style2pixel#285]

**Comment by yuval-alaluf** [comment]
I am not sure what you mean by compressed size. 
For training the frontalization task, we used the entire FFHQ dataset which is 70,000 images. You could probably use less and still get reasonable results.

**Comment by abdul756** [comment]
Thanks yuval for your quick reply, I mean how to reduce the size of facefrontalisation model from 1GB to atleast 500 MB.

**Comment by yuval-alaluf** [comment]
Compressing our model is out of the scope of this work. If you want to compress this, you can look at different techniques to reducing model sizes such as pruning and distillation. 
You can also take a look at where most model parameters are and try to redesign the architecture a bit to match your constraints.
