### ISSUE TITLE
 Model parameters at other resolutions

### ISSUE THREAD

**Issue by li-car-fei** [eladrich/pixel2style2pixel#288]
Can you provide the model parameters trained on the dataset FFHQ with a resolution of 256?

**Comment by yuval-alaluf** [comment]
We don't have such a model available. SG2 generators trained on FFHQ at a resolution of 256 are available on the official SG2 repo from nvidia.

**Comment by li-car-fei** [comment]
> We don't have such a model available. SG2 generators trained on FFHQ at a resolution of 256 are available on the official SG2 repo from nvidia.

Can an encoder with a resolution of 1024*1024 be used for stylegan2 with a resolution of 256*256?

**Comment by yuval-alaluf** [comment]
No since the latent spaces are different. You will need to retrained your encoder, although you could try starting from the pretrained encoder rather than training from scratch.
