### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by cloudweather** [eladrich/pixel2style2pixel#29]
Hi,
Is it possible to run the codes on Windows 10?

**Comment by yuval-alaluf** [comment]
We have not tried running on Windows, but this seems possible if you are able to compile the cuda extensions that are used in the StyleGAN implementation. You may find the following issues from rosinality's github helpful:

https://github.com/rosinality/stylegan2-pytorch/issues/63
https://github.com/rosinality/stylegan2-pytorch/issues/47

**Comment by cloudweather** [comment]
Thank you! I'll check those out
