### ISSUE TITLE
Reverse-Toonification for Beginners

### ISSUE THREAD

**Issue by EugenusRex** [eladrich/pixel2style2pixel#290]
Hello and sorry, in advance, for the ignorance included in this message.

I do a lot of work in the restoration and colourisation of photographic portraits of historical figures. After discovering artist Nathan Shipley's work using your code to 'reverse-toonify' historical portraits, I am quite desperate to have a go myself.

Whilst I am experienced in using photo manipulation software, I have no grounding in coding and am struggling, rather pitiably, to perform the basic setup of your code. I have come as far as downloading Anaconda and Python, cloning the repository and downloading the StyleGAN Inversion model set. From this point onward, I am rather stumped as to how next to proceed. 

Is there any chance that you could provide instruction, including very basic walk-throughs for command prompts, that will get me into a position where I can submit an image into the engine? Alternatively, could you recommend any articles or videos (suitable for dummies) that might give me the grounding I need to finish setting up your code?

Thank you for your time, any help will be greatly appreciated and I apologise for marring this forum of great expertise with my ignorance.

Kind regards.

**Comment by yuval-alaluf** [comment]
Hi @EugenusRex 
The easiest way to get started with the code would be to use the Google Colab notebook in the repo. 
You can run through the cells in the notebook and there are (I believe) only two changes you will need to make. 

First, when selecting which Experiment Type you want, you should select`ffhq_encode`: 
<img width="630" alt="Screen Shot 2022-10-01 at 14 16 04" src="https://user-images.githubusercontent.com/37438467/193406910-940a7a94-6494-48c3-8868-38f29c86efc1.png">

Then, when defining your input path, you should change the line `"image_path": "notebooks/images/input_img.jpg",` to the path to your desired image. That is, change `notebooks/images/input_img.jpg` to `notebooks/images/my_input_image.jpg` where `my_input_image.jpg` is the image that you uploaded to the Colab under the folder `notebooks/images`. 
<img width="572" alt="Screen Shot 2022-10-01 at 14 16 57" src="https://user-images.githubusercontent.com/37438467/193406945-022dd13f-1fc0-4cac-84e3-dd1d04065a05.png">

Then you should be able to continue through the notebook as usual, until you get the output result.

IMPORTANT NOTE: 
I will note that there is something a bit tricky that you should be aware of. To work on human faces, StyleGAN needs the images to be aligned. This basically means that the face and eyes should be in a particular place in the image. There is a code that automatically does this. However, it may not work on images that are not of human faces or images that are for examples paintings. Therefore, if you are trying to run on images that are portraits of historical figures, this alignment may fail. From my understanding, Nathan overcame this by doing the alignment manually, but I myself have not tried doing manual alignment. If the alignment doesn't work, then the reverse toonification process will not work. 

I hope this helps a bit :)

**Comment by EugenusRex** [comment]
Hi Mr. Alaluf.

I do apologise: I never thanked you for providing these instructions. I was dealing with some personal matters and unable to experiment with P2S2P, until recently. 

It has taken me a while to suss out, but I have finally managed to generate an output image through the FFHQ encoder. I know how to generate an output image in 256x256p, but how do I manage to generate an output image in significantly greater resolution? I did try running the output image through the super-resolution model but again, could only work out how to download the result, again, in 256x256. 

All the images that I want to run through the engines are of high quality. Is there a way that I can change the output resolution or would I need to do something more drastic, such as changing the data sets? 

Again, I apologise for being an idiot in these kinds of matters. I will appreciate any advice you can give. 

Kind regards.
