### ISSUE TITLE
Can large batchsize accelerate convergence?

### ISSUE THREAD

**Issue by caopulan** [eladrich/pixel2style2pixel#292]
I tried large batch-size (i.e., 16 and 64) with linearly increasing learning rate lr=1e-4*(bs/8).
However, it can not accelerate the convergence, both happening in pSp and e4e.
Have you ever tested performance in large batchsize or can you give me some suggestions?

**Comment by yuval-alaluf** [comment]
We did not test performance with larger batch sizes. If you do change the batch size, you should adjust the loss lambdas accordingly. This could explain why you are not seeing accelerated convergence.
