### ISSUE TITLE
I want to ask a little bit about style mixing,5 different angles of the same face

### ISSUE THREAD

**Issue by D-Mad** [eladrich/pixel2style2pixel#294]
I want to ask a little bit about style mixing.
If I input 5 pictures of a person's face at 5 different angles
If I use your style mixing it produces 5 ouputs will it be continuous? I mean those 5 faces refer to the same style, even though it's 5 different angles of the same face.
Ex: input 5 different angles of the same face.
![Screenshot 2022-10-14 183526](https://user-images.githubusercontent.com/8207507/196925618-e064b37f-0ab1-476b-81b2-d2e3266243d6.png)

**Comment by yuval-alaluf** [comment]
Hi @D-Mad ,
I am not sure I completely understand what you are trying to do. What task are you trying to solve? Are you trying to output a picture of the same person in different poses?

**Comment by D-Mad** [comment]
![Screenshot from 2022-10-21 14-44-43](https://user-images.githubusercontent.com/8207507/197143367-b75902ac-bac6-420a-b1a3-2fedd1e142ca.png)

yes, i am  trying to output a picture of the same person in different poses
You are mixing with multiple randomly of W latents .
My method is to choose 1 W, not random
Then I applied it to 5 poses of the same person.
I want to ask you, is it possible to output 5 poses with the same style? Similar to my input is 1 person, but 5 poses, output is exactly the same? I thank you very much, I am new and I am learning every day, I am a bit confused…

**Comment by yuval-alaluf** [comment]
If you want the same person in 5 different poses, I would use latent space editing to achieve this rather than style mixing. I would take a look at InterFaceGAN. You can also check out my ReStyle repo and edit faces that way. Take a look here for more details: https://github.com/yuval-alaluf/restyle-encoder#editing

**Comment by D-Mad** [comment]
Thank you very much,I thought if using latent space editing how to correct the original 5 pose input, I have rendered 5 poses ,5 angles from 1 human face, and I want to blend the skin with another skin, but have to keep the texture facial structure of the original 5 poses, because these 5 poses belong to 1 person.Can I do it the way you say?

**Comment by yuval-alaluf** [comment]
If I understood you correctly, this is a bit tricky. If you want to blend the skin color with another skin color, you probably need to do something more similar to style mixing. You can play around with which layers to use when performing the mixing.
