### ISSUE TITLE
ninja compilation error

### ISSUE THREAD

**Issue by AkhileshV** [eladrich/pixel2style2pixel#296]
What are the visual studio and CUDA versions required for successful ninja compilation? I have visual studio 2019 and CUDA 11.2!
Ninja compilation throws an error saying 

"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx86\x86/link.exe" fused_bias_act.o fused_bias_act_kernel.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\akhil\anaconda3\envs\anc_project\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\akhil\anaconda3\envs\anc_project\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\lib/x64" cudart.lib /out:fused.pyd
FAILED: fused.pyd
"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx86\x86/link.exe" fused_bias_act.o fused_bias_act_kernel.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\akhil\anaconda3\envs\anc_project\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\akhil\anaconda3\envs\anc_project\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\lib/x64" cudart.lib /out:fused.pyd
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
ninja: build stopped: subcommand failed.

Also does the project not work on windows? I saw the prerequisites as Linux/macOS

**Comment by yuval-alaluf** [comment]
Regarding the question about windows, there are some people that got the code working on windows. Take a look at some of the older issues for clarification on that. Although I will say that I have never tried to run it on windows myself. 

I believe that your working on windows is resulting in the ninja compilation problem. Therefore, try to see what others did to get the code working on ninja and hopefully this will also resolve your issue.

**Comment by AkhileshV** [comment]
Okay! Thank you!

**Comment by NithinJangid** [comment]
Hello @AkhileshV did you solved the problem? if yes, would you tell me how did you solve it
