### ISSUE TITLE
Request for pre-trained models of competitors in Figure 8 and Figure 9

### ISSUE THREAD

**Issue by Yikai-Wang** [eladrich/pixel2style2pixel#298]
Hi there,
Thanks for your great work! I am very interested in your method and want to do some follow up work. Some competitors in your paper do not provide the corresponding pre-trained models, for example pix2pixHD in sketch2image task, and pix2pixHD, SPADE, CC FPSE for label2image task. I wonder if you could share those checkpoints so we can run some generation results and compare.
Look forward to your reply!

**Comment by yuval-alaluf** [comment]
I don't believe we still have those models available, but all data details are provided in the paper. We used the default parameters for all competitors so re-creating the models should be fairly straightforward.

**Comment by Yikai-Wang** [comment]
Thanks for your reply.
