### ISSUE TITLE
class EncodeTransforms  in transfroms_config.py 

### ISSUE THREAD

**Issue by jays0606** [eladrich/pixel2style2pixel#3]
In configs/transforms_config.py line 16, I was wondering why no transformation is applied in the transform_source part. Is this part deleted by some chance? 

def get_transforms(self):
		transforms_dict = {
			'transform_gt_train': transforms.Compose([ 
				transforms.Resize((256, 256)),
				transforms.RandomHorizontalFlip(0.5),
				transforms.ToTensor(),
				transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])]),
			**'transform_source': None,**
			'transform_test': transforms.Compose([ 
				transforms.Resize((256, 256)),
				transforms.ToTensor(),
				transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])]),
			'transform_inference': transforms.Compose([ 
				transforms.Resize((256, 256)),
				transforms.ToTensor(),
				transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])])
		}
		return transforms_dict

**Comment by yuval-alaluf** [comment]
Hi @jays0606! 
Setting `transform_source` to `None` is done intentionally in this case.  
If you go to `datasets/images_dataset.py` on line `28`, you will see that we check if `self.source_transform` is `None`. If it is, we set `from_im` equal to `to_image` on line `31`.  
In other words, if there is no `transform_source` defined, we will set the input image (i.e. `from_im`) equal to the target image (i.e. `to_im`). Intuitively, for the encoding problem this makes sense as we wish to set the input image equal to the target image. 
Is this clear?

**Comment by jays0606** [comment]
Now I understand the flow. Thank you very much for your reply!! I really appreciate it !!

**Comment by yuval-alaluf** [comment]
Always happy to help!
