### ISSUE TITLE
image-to-sketch

### ISSUE THREAD

**Issue by hahachocolate** [eladrich/pixel2style2pixel#300]
If I want to use your model to do a image-to-sketch task, should I pretrain the StyleGAN with my sketch datasets, then train your encoder with real facial image?

**Comment by yuval-alaluf** [comment]
Exactly. You should train your generator to generate sketch images. You can then train an encoder that maps real images to their corresponding sketch (i.e., by defining the pairs exactly the opposite of what we did for the sketch-to-image task).
