### ISSUE TITLE
error when testing with a different image

### ISSUE THREAD

**Issue by At-Walid** [eladrich/pixel2style2pixel#301]
Hello,

I tried uploading my segmentation mask to test the code but I get the following error:

`IndexError: index 26 is out of bounds for axis 2 with size 19`

When I change the number of channels I get this error:

`RuntimeError: Given groups=1, weight of size [64, 19, 3, 3], expected input[1, 200, 256, 256] to have 19 channels, but got 200 channels instead`

Here is my segmentation mask:
![MASK_23](https://user-images.githubusercontent.com/63915243/211822587-744d6dab-b325-4d57-896c-d9e099659ddd.png)

thanks

**Comment by yuval-alaluf** [comment]
You need to make sure that your segmentation mask has exactly 19 channels, one for each class. Is this the case in your example?

**Comment by At-Walid** [comment]
Thank you for your answer. I finally made it work using another DNN to create the segmentation masks.
