### ISSUE TITLE
Is it possible to get more details in the images?

### ISSUE THREAD

**Issue by chrisgaig** [eladrich/pixel2style2pixel#302]
Hello, 
I have tried to re-train the e4e on a dataset from production. In doing so, I found that the model is able to reproduce the dimensions of my images very well, but important details regarding the defects of the parts are not represented at all or only weakly. Is there perhaps a way in the settings to improve the quality of the images to get more detail?

Would be great if you can clarify this for me. Thank you very much in advance for your help.

**Comment by yuval-alaluf** [comment]
If you are missing details in your reconstructions, then you may need to find a different method for performing the inversion. Either optimization-based methods or more advanced encoder-based methods.
