### ISSUE TITLE
 How to train on paired data?

### ISSUE THREAD

**Issue by watertianyi** [eladrich/pixel2style2pixel#305]
If I train on the following data pairs, how should I set the training parameters and training configuration? What pre-trained model do I need to use?
![image](https://user-images.githubusercontent.com/29244715/225227537-9e0dbef4-fb6a-45e8-a415-d43c948689d6.png)

**Comment by yuval-alaluf** [comment]
You can take a look at our parameters for the sketch-to-image task and change `--label_nc=3` and `--input_nc=3`. You can start with these parameters and adjust as needed.
