### ISSUE TITLE
About celebs_seg_to_face

### ISSUE THREAD

**Issue by diamond0910** [eladrich/pixel2style2pixel#307]
Thank you for your great work.

In the paper, you show you can encode the mask to the first seven w+ latant, and you random latent for the rest layers. But I see your code. The code directly encodes the mask to the whole w+ latent. Why? This will lead that the style-mixing operation generates different masks.

![image](https://user-images.githubusercontent.com/43036573/229703289-5c24dd24-83bc-40ae-aba5-34bf6a14e179.png)

Thank you.

**Comment by yuval-alaluf** [comment]
I am not sure I fully understand the question. When we encode the segmentation map into StyleGAN's latent space, we are in a sense mapping the segmentation map to an encoding of a real face image. The output of the task is a real image, not a segmentation map.
