### ISSUE TITLE
Inference.py error

### ISSUE THREAD

**Issue by spamfold3r** [eladrich/pixel2style2pixel#31]
Hello again

I've moved from working in the jupyter notebook to working via terminal in the conda environment. I have been using style_mixing.py with no problems and with good results. However, when trying to run inference.py (which worked fine in the jupyter notebook) I am getting the following error: 

![inference-error](https://user-images.githubusercontent.com/73826746/98139577-44aff800-1ebc-11eb-9027-34a33cca3570.png)

Apologies for asking again!

**Comment by yuval-alaluf** [comment]
No need to apologize :)   
I think I see the issue. Did you by any chance run the inference script without the argument `--couple_outputs`?

**Comment by yuval-alaluf** [comment]
In any case, I tested it myself and it appears we had a bug when `couple_outputs` was False since `out_path_coupled` was `None`!  
I fixed this now and hopefully inference works when `couple_outputs` is False.   
Thanks for brining it to our attention!   
A small side note: I personally like running with `--couple_outputs` so you can see the inputs and outputs side by side 😄

**Comment by spamfold3r** [comment]
Ah brilliant! I thought it was an optional parameter so that's reassuring that it was only a bug. Yes, for some reason I thought it would be good for simplicity just to render out single images but to be honest it isn't that much effort to crop them out afterwards!

Another question but still related to inference.py: the quality of output produced by the jupyter notebook's inference (the image to GAN function) is far cleaner than the outputs that I am getting from doing the psp_ffq_encode.py via terminal. Could this be due to settings that I have not yet specified or configured, or is this an expected difference?

**Comment by yuval-alaluf** [comment]
Very strange as they use the same logic. Now by default `inference.py` should return 1024x1024 images while the notebook returns images at 256x256.   
Do you want to send an example?  
Also, are you running the same images using the same model in both cases?

**Comment by spamfold3r** [comment]
![ryu_notebook](https://user-images.githubusercontent.com/73826746/98149985-da03ba00-1ec5-11eb-88e1-479f85b8b0df.png)
![ryu-terminal](https://user-images.githubusercontent.com/73826746/98149988-db34e700-1ec5-11eb-81f8-1a812d32f882.jpg)

Top being notebook, bottom being terminal.

Both times I have used/specified the `ffhq_encode` operation and used the corresponding psp model. Given that the second image is so misaligned, could it be an issue with accessing `shape_predictor_68_face_landmarks`?

**Comment by yuval-alaluf** [comment]
Yes.  The notebook has an alignment step before running inference while the `inference.py` script assumes the images have been aligned previously. If you input the top left image into `inference.py` you should get the same result.

**Comment by spamfold3r** [comment]
Awesome, thank you! This has been a really useful learning experience so thanks for taking the time to answer my many questions.

**Comment by yuval-alaluf** [comment]
Really happy to hear you're enjoying working with pSp!  
Please feel free to keep asking questions (you may help us find more bugs 😄 )
