### ISSUE TITLE
Is it possible  video2anime  train？ like  this  project？

### ISSUE THREAD

**Issue by zhanghongyong123456** [eladrich/pixel2style2pixel#310]
https://github.com/Sxela/ArcaneGAN（like this project）
![image](https://user-images.githubusercontent.com/48466610/231075831-cf4e7787-e5ce-46fd-a3bb-9114bc534f44.png)
Compared with this project（pix2pix-HD）, which one is more suitable for video conversion animation

Is there any project related to converting video to animation? I hope you can recommend it

**Comment by yuval-alaluf** [comment]
The problem with using StyleGAN out of the box for video generation is that it will not be temporally consistent. Therefore, if you want to work with something simple, I would recommend using something that is based on pix2pixHD. There are some StyleGAN-based works for video/animation generation but they require a lot of tricks to get temporally consistent results.

**Comment by zhanghongyong123456** [comment]
> pix2pixHD

OK. iTry it,can you give me a  methods of producing data(a Pair of data),like  this:
![image](https://user-images.githubusercontent.com/48466610/231427915-e0270ec4-a6fd-4116-947c-8dddd1fa07ec.png)  (It's a bit of a mismatch)

**Comment by yuval-alaluf** [comment]
Maybe something like AnimeGAN is something that you are looking for. For example: 
https://github.com/TachibanaYoshino/AnimeGANv3#art-face-to-usa-cartoon-style
Other than that, I am not too familiar with stylization works.
