### ISSUE TITLE
Some error reporting problems encountered during operation

### ISSUE THREAD

**Issue by LittleStarZz** [eladrich/pixel2style2pixel#318]
Brother, I’m a newbie. I haven’t run through a few codes. I encountered some errors when I reproduced your code. I hope you can reply when you have time. Thank you very much.
Look at the error report directly:

Your compiler (c++ 4.8) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.

I have been looking for related solutions for a long time. The first one also reduced GCC to 4.9 as required, but it had no effect.
Because it is my first time to run a project using Linux, I don’t understand it very well. When my brother saw it, I kindly ask him to teach me how to solve it. Thank you.

**Comment by yuval-alaluf** [comment]
You should first make sure that you're environment is able to run torch with CUDA. After that you can try installing our conda environment for running our code.
