### ISSUE TITLE
Does this support 1024*1024?

### ISSUE THREAD

**Issue by eEhyQx** [eladrich/pixel2style2pixel#32]
Hi, thanks again for the great work.
I'm trying to train a Toonify model on it. But I just notice that the default resolution is 256*256 according to the provided transforms_config.py. Can I train this model under 1024*1024 resolution by simply changing the transforms_config.py settings?

**Comment by yuval-alaluf** [comment]
This is definitely possible. The first step is as you say to update the `transforms_config.py` file to change the resize to (1024,1024). In addition to this, you may need to make slight changes in the model (in the file `psp_encoders.py`) since the current code expects inputs of 256.  
I invite you to try this out yourself and if you get stuck along the way, you are welcome to ask questions.

**Comment by hs1227** [comment]
> This is definitely possible. The first step is as you say to update the `transforms_config.py` file to change the resize to (1024,1024). In addition to this, you may need to make slight changes in the model (in the file `psp_encoders.py`) since the current code expects inputs of 256.
> I invite you to try this out yourself and if you get stuck along the way, you are welcome to ask questions.

I changed `transforms_config.py`.
could you explain about psp_encoders.py more in detail?
how can I change `psp_encoders.py` for 1024*1024?

Plus, do I need to change other code to get testing results for 1024*1024?

**Comment by yuval-alaluf** [comment]
Before you dive into making the changes into the encoder itself, may I ask if you **need** to train on full 1024x1024 images? We find that using 256x256 inputs and a 1024x1024 StyleGAN generator provide the same quality outputs with much less computational overhead (i.e. 256x256 inputs allow for larger batch size, faster training, etc.).  
Even when training on 256x256 images, the inference code generates images at the full 1024x1024 resolution by default so no changes are needed.

**Comment by hs1227** [comment]
> Before you dive into making the changes into the encoder itself, may I ask if you **need** to train on full 1024x1024 images? We find that using 256x256 inputs and a 1024x1024 StyleGAN generator provide the same quality outputs with much less computational overhead (i.e. 256x256 inputs allow for larger batch size, faster training, etc.).
> Even when training on 256x256 images, the inference code generates images at the full 1024x1024 resolution by default so no changes are needed.

Sorry, I thought the model training had to be the same resolution to get the test results at 1024*1024 resolution.
Now I've changed `resize=True` to `resize=False` in `psp.py` , line 66.
Then I can get 1024*1024 resolution. Thanks for the great work.

**Comment by yuval-alaluf** [comment]
Great!   
Notice that in the most updated code, there is not need to make changes to `psp.py`. You should be able to control whether to generate the full 1024x1024 or resized 256x256 outputs using the flag `--resize_outputs `.

**Comment by qo4on** [comment]
> the inference code generates images at the full 1024x1024 resolution by default

Your [Colab example](http://colab.research.google.com/github/eladrich/pixel2style2pixel/blob/master/notebooks/inference_playground.ipynb) generates 256x256 images in `toonify` mode even when `opts['output_size'] = 1024` was added before:
```
with torch.no_grad():
    tic = time.time()
    result_image = run_on_batch(transformed_image.unsqueeze(0), net, latent_mask)[0]
    toc = time.time()

result_image.shape
#torch.Size([3, 256, 256])
```
What should I do to get 1024 output?

**Comment by yuval-alaluf** [comment]
Hi @qo4on 
You're correct. The notebook is a bit outdated and resizes the images to 256x256. But as you mentioned, 1024x1024 resolution outputs are naturally supported. 
I hope to update the notebook in the near future with support for outputting full resolution by default instead of 256x256.
