### ISSUE TITLE
can you please share an example in colab to train.

### ISSUE THREAD

**Issue by molo32** [eladrich/pixel2style2pixel#33]
I have a set of images.
can you share an example in colab to train a set of images

**Comment by yuval-alaluf** [comment]
Hi @molo32 ,
We do not plan on adding an example for training in the colab notebook as this was designed mainly to help people get started with running inference. If you have data and are ready to train, please refer to the "Training" section in the README:
https://github.com/eladrich/pixel2style2pixel#training
It will provide you with an example command for training each of our available applications.
