### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Aspie96** [eladrich/pixel2style2pixel#34]
I know it's licensed under MIT.

However, would you consider adding a license file (which can be parsed automatically) and a copyright notice? The MIT license is confusing without a copyright notice.

In addition, users of this might not immediately be aware of the restrictions of those files under the Nvidia Source Code License-NC: using this repo as if it was wholly MIT-licensed isn't safe.

It'd be nice to put a mention about these files in the readme.

I think there are other files with third-party rights associated with them.

In general, the licensing status of this project is quite unclear. Would you consider clarifying it a bit?

**Comment by yuval-alaluf** [comment]
Hi @Aspie96 ,  
Thanks for letting us know! 
I uploaded a license file to this repository.  
Regarding the third-party licenses, we will look into it and update as soon as possible.

**Comment by Aspie96** [comment]
That is awesome, thanks!

**Comment by yuval-alaluf** [comment]
Hi @Aspie96 ,
I just got to updating the licenses of the other open-source projects we used here. You will find them all in the folder `licenses`: 
https://github.com/eladrich/pixel2style2pixel/tree/master/licenses

In addition, to remove any ambiguity, I added a Credits section in the README with explicitly links to each of the resources along with details and links to their licenses:
https://github.com/eladrich/pixel2style2pixel#credits

I hope this answers your question and helps clarify the ambiguity.

**Comment by Aspie96** [comment]
@yuval-alaluf I know this issue is old, but look at https://github.com/eladrich/pixel2style2pixel/blob/master/models/stylegan2/op/fused_bias_act_kernel.cu

It is released under a non commercial license.
Such license is not mentioned in the readme, but it is the most important one for the user to be aware of because it is the only one restricting commercial use.
This project cannot be used commercially according to that license. This should be noted in the readme (at least listing such license among the others)

**Comment by yuval-alaluf** [comment]
Please see the latest commit: https://github.com/eladrich/pixel2style2pixel/commit/0c83c42a913adc42d0ba0dabfa7d5b25b8f10ffd

**Comment by Aspie96** [comment]
@yuval-alaluf I think this solves the issue.
Thank you!
