### ISSUE TITLE
stylegan2 pytorch weights

### ISSUE THREAD

**Issue by Nickzhangkaiyu** [eladrich/pixel2style2pixel#35]
that's so excellent result for image encoding. And i want to kown how convert stylegan2 weights from official tensorflow implement to pytorch? thanks!

**Comment by yuval-alaluf** [comment]
We converted the official tensorflow StyleGAN2 weights from rosinality's repository:
https://github.com/rosinality/stylegan2-pytorch#convert-weight-from-official-checkpoints

**Comment by Nickzhangkaiyu** [comment]
thanks a lot!

**Comment by markemus** [comment]
If I understand this correctly, this means that I can train stylegan2 in Tensorflow and convert that checkpoint to work for your model?

**Comment by yuval-alaluf** [comment]
@markemus 
Exactly. You can train your StyleGAN2 models using the official tensorflow repos (including the more recent StyleGAN-ADA repo) and then convert the checkpoints using rosinality's script. The resulting `.pt` files are compatible with our code.
