### ISSUE TITLE
why our model generate a image suround by a block shadow

### ISSUE THREAD

**Issue by maxrumi** [eladrich/pixel2style2pixel#38]
The Source Domain data of stylegan2, the pre-training model we adopted, is FFHQ dataset, while the target Domain dataset is some cartoon images. Stylegan2, on the other hand, produces good cartoon images. When we use this Stylegan2 to train the PSP model, both the Source Domain and target Domain datasets of the PSP model are FFHQ data. Something weird happens, and all the generated images are surrounded by a shadow of a square. We don't know if you have encountered this problem or if you have any solutions?

**Comment by yuval-alaluf** [comment]
Hi @maxrumi ,
Just show I better understand the setting, you are training a real-to-cartoon task in a similar setting to that used in the toonify model we trained, correct? Using only real data and swapping the FFHQ StyleGAN with a cartoon StyleGAN?   

In any case, to better understand the issue, can you please send an example of what you mean by "a shadow of a square".

**Comment by maxrumi** [comment]
Hi, you are quite right, we use your toonify model training setting and we just replace the pretrained stylegan2 model with a cartoon styl
egan, then we retrain the psp model, and we get the results like this:
![00002](https://user-images.githubusercontent.com/17705768/99221506-a9a01200-281b-11eb-932a-c8c8e89a3f2c.jpg)

**Comment by yuval-alaluf** [comment]
What do outputs of your StyleGAN look like? Can you show me some randomly generated samples?  
Also, what is your training setting (e.g. losses)

**Comment by maxrumi** [comment]
The stylegan2 outputs look like this:
![‘Breaking Bad’ inspira al arte](https://user-images.githubusercontent.com/17705768/99224471-5630c280-2821-11eb-9bf5-bd06c7eac4ab.jpg)
The losses, and training setting is just the same as your toonify model setting, we did not change anything.

**Comment by yuval-alaluf** [comment]
The image you attached above was randomly generated from StyleGAN? Or was it used to train the generator?  
Could please send some examples of random images generated from your StyleGAN?

**Comment by yangzhaojason** [comment]
> The image you attached above was randomly generated from StyleGAN? Or was it used to train the generator?
> Could please send some examples of random images generated from your StyleGAN?
> 
> A few more questions:
> 
> 1. How many iterations did you run to obtain the result you sent above?
> 2. Can you output the input image along-side the output image (you can do this by running inferece.py with --couple_outputs)

1.We use the inferences of about 55,000 iterations of model training.
2.This parameter (--couple_outputs) has been added to ensure that the output image resolution is 224 x 224.

**Comment by yuval-alaluf** [comment]
Training for 55,000 iterations with no paired data may be too long for this task (for a comparison we train for 6,000 iterations). But I do not believe that this is causing your problems.  
1. It would really help if you could send a few examples that you generated from StyleGAN as it is hard to tell what your generator is capable of outputting. 
2. I don't understand what you mean by --couple_outputs ensuring that your output is 224x224? Using this flag will output the input image alongside the generated image when running inference.
3. What is the output resolution of your generator? What is the size of your input?

**Comment by maxrumi** [comment]
> Training for 55,000 iterations with no paired data may be too long for this task (for a comparison we train for 6,000 iterations). But I do not believe that this is causing your problems.
> 
> 1. It would really help if you could send a few examples that you generated from StyleGAN as it is hard to tell what your generator is capable of outputting.
> 2. I don't understand what you mean by --couple_outputs ensuring that your output is 224x224? Using this flag will output the input image alongside the generated image when running inference.
> 3. What is the output resolution of your generator?
> 4. What is the size of your input?
1, our stylegan2's generate images like this:
![‘21 Savage’ by DANIEL COLE](https://user-images.githubusercontent.com/17705768/99247259-ac156280-2841-11eb-9d27-8cfdfc6de1f9.jpg)
![0d35b1bc-0962-45e2-bc42-de41cb50b88b](https://user-images.githubusercontent.com/17705768/99247271-b20b4380-2841-11eb-9f14-ffe79dd4753b.jpg)
2, he is wrong about this parameter. And yes, --couple_outputs is used to inference, the size is not what he said 224, actually it is 256, you can ignore this question.
3, The output resolution of stylegan2 is 256*256.
4, the size of our input images is 256*256 too(during training).

**Comment by yuval-alaluf** [comment]
I am quite surprised that your StyleGAN is able to perfectly output perfect text as part of the output image. Were these images maybe used to **train** the StyleGAN model instead?

**Comment by maxrumi** [comment]
This is some training data, but stylegan2 can actually generate image like this, this is the image stylegan2 generate
![000002](https://user-images.githubusercontent.com/17705768/99252726-5ee9be80-284a-11eb-8fe2-ca7d846e8ad0.png)

**Comment by yangzhaojason** [comment]
Hello, here I'd like to confirm a few questions:
1. Check whether the source domain data and target domain data for PSP training are consistent. Currently, we are all real FFHQ face data sets. However, the source domain should be the real face of FFHQ and the target domain should be the cartoon data?

2. We changed the ps.py   self.decoder = Generator(256, 512, 8) resolution from 1024 to 256.

**Comment by yuval-alaluf** [comment]
@yangzhaojason 
Your two points are correct.  

@maxrumi  I now understand what images your StyleGAN is capable of generating.  
The StyleGAN that you trained seems to output images in a domain that is very different than the domain of facial images.  Notice that the image you randomly generated is quite different than the images you will find in FFHQ. Therefore, trying to train pSp using **only** FFHQ images on your StyleGAN model may not be optimal and may explain the poor results you've obtained.  
Therefore, if you are trying to create a "real-to-cartoon" pSp model, you should try perhaps training a StyleGAN that better matches the inputs you wish to train pSp on.

**Comment by maxrumi** [comment]
Thanks a lot! We will try your recommendation.
