### ISSUE TITLE
data set used in this work?

### ISSUE THREAD

**Issue by molo32** [eladrich/pixel2style2pixel#42]
How to get the training data(front faces, sketches) to train the psp encoder?

**Comment by yuval-alaluf** [comment]
You can download the FFHQ and CelebAMask-HQ datasets from: 
- https://github.com/NVlabs/ffhq-dataset
- https://github.com/switchablenorms/CelebAMask-HQ 
     - Here you can find the original CelebA-HQ dataset along with the segmentation maps for performing segmentation-to-image.

**Comment by Radium98** [comment]
Hello，I'm a greenhand in DL, so I want to ask you some naive questions:
1.First,it seems that you use the FFHQ and CelebAMask-HQ datasets, but I found FFHQ is too large for me to download(I am in China, so it has some difficulties for me to download it from Google Drive. And I also don't have enough harddisk room for so big data). If all data in it  is used in your project?And if it should be processed properly?
2.How to run the jupyter script you offered in your project? I opened it in jupyter online, but it failed to run properly.Should I do it in linux os?
Lastly, your work is fantastic, sorry to bother you! I'm waiting for your earlist reply sincerecely, thanks.

**Comment by yuval-alaluf** [comment]
> Hello，I'm a greenhand in DL, so I want to ask you some naive questions:
> 1.First,it seems that you use the FFHQ and CelebAMask-HQ datasets, but I found FFHQ is too large for me to download(I am in China, so it has some difficulties for me to download it from Google Drive. And I also don't have enough harddisk room for so big data). If all data in it is used in your project?And if it should be processed properly?
> 2.How to run the jupyter script you offered in your project? I opened it in jupyter online, but it failed to run properly.Should I do it in linux os?
> Lastly, your work is fantastic, sorry to bother you! I'm waiting for your earlist reply sincerecely, thanks.

Hi @Radium98 , 
Regarding your questions: 
1. In our work we used all 70,000 FFHQ images. The original data is in a resolution of 1024x1024 and is therefore quite large. During training we resized the images to 256x256 anyway so there is really need to download the original data. Therefore, you may be able to download the dataset from the following link: https://www.kaggle.com/xhlulu/flickrfaceshq-dataset-nvidia-resized-256px
There, the entire dataset is only 2GB so hopefully it is easier to work with. 

2. The jupyter script can either be run using Google Colab ([here's the link](http://colab.research.google.com/github/eladrich/pixel2style2pixel/blob/master/notebooks/inference_playground.ipynb)) or locally if you have a compatible GPU. We have only tried running it on linux, but running on windows should be possible with a few adjustments. In any case, colab is easier in my opinion.
