### ISSUE TITLE
File not compiling

### ISSUE THREAD

**Issue by CJPJ007** [eladrich/pixel2style2pixel#43]
I have run model before it was compiling and working fine but after that immediately next day it stopped working model is not compiling I have to again again interrupt compiling and sometimes even GPU gets lost. But model does not compile or file does not compile and solution to this.

**Comment by yuval-alaluf** [comment]
Hi.  
Please provide more information.
What script are you running?  
What is the error/message you are getting when you are interrupting the script?  
On what environment are you running?

**Comment by CJPJ007** [comment]
![Screenshot (93)](https://user-images.githubusercontent.com/45278375/100076180-e8ab1480-2e66-11eb-9d26-4c0739731af0.png)
I am running inference.py
This is the error I have see after keyword interrupt.
Environment I have created is same as provided in github repo with psp_env.yaml file.

**Comment by CJPJ007** [comment]
![Screenshot (95)](https://user-images.githubusercontent.com/45278375/100076910-bcdc5e80-2e67-11eb-96d1-df0ebfbf928d.png)
This remains like this for a long time then I have to interrupt the file.

**Comment by yuval-alaluf** [comment]
Ok. We are familiar with this problem. It sometimes occurs with ninja where the compilation process is locked by a process. To fix this, try looking at the paths: 
```
~/.cache/torch_extensions/fused/
~/.cache/torch_extensions/upfirdn2d/
```
(Or wherever your cache for the torch extensions is) 
There, see if you have a file that ends with `.lock` or something of that nature. If so, delete the file and try re-running the script.

**Comment by CJPJ007** [comment]
I checked but there is no such file for cache for torch extensions.

**Comment by yuval-alaluf** [comment]
There should be a `torch_extension` directory saved somewhere. It may not necessarily be in the exact path I noted above.  Can you try to find it using
```
find / -name "torch_extensions"
```

**Comment by CJPJ007** [comment]
Yes I found torch_extensions's named folder but there is no .lock file in that folder.

**Comment by yuval-alaluf** [comment]
There is no filename containing the word "lock" in the folder `torch_extension/fused/` or `torch_extension/upfirdn2d`?

**Comment by CJPJ007** [comment]
Changed environment means created another new environment and then this error is popping. Can you please help with this???


RuntimeError: Error building extension 'fused': [1/1] c++ fused_bias_act.o fused_bias_act_kernel.cuda.o -shared -L/home/sathish/anaconda2/envs/psp_env_new/lib/python3.7/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda-9.0/lib64 -lcudart -o fused.so
FAILED: fused.so
c++ fused_bias_act.o fused_bias_act_kernel.cuda.o -shared -L/home/sathish/anaconda2/envs/psp_env_new/lib/python3.7/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda-9.0/lib64 -lcudart -o fused.so
/usr/bin/ld: cannot find -lcudart
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by yuval-alaluf** [comment]
It appears that you are using CUDA 9, which is causing the problem. Please see issue #4 for more details.

**Comment by CJPJ007** [comment]
Is this compilation problems solution same for a docker container???

**Comment by CJPJ007** [comment]
Is this compilation problem's solution same for a model running in a docker container???

**Comment by yuval-alaluf** [comment]
You need to make sure you have the correct environment requirements, regardless of if you're running with docker or not. This includes having CUDA > 10.1. Please refer to similar issues in this repository and in [rosinality's StyleGAN2 repository](https://github.com/rosinality/stylegan2-pytorch) for more details on setting up a correct environment.

**Comment by CJPJ007** [comment]
Thank you so much. It is working fine now.
