### ISSUE TITLE
Toonify model seems not work

### ISSUE THREAD

**Issue by brightmart** [eladrich/pixel2style2pixel#44]
I used notebook of Inference_playground.ipynb and try various experiment type with default settings. All other experiment type work well except  type of "toonify": 
   it seems that no matter which kinds of image i used, the results are all similar like this:
![result](https://user-images.githubusercontent.com/19634224/100516510-63ee2c80-31bf-11eb-9c67-6a3e1768e24f.jpeg)

**Comment by yuval-alaluf** [comment]
Hi @brightmart 
Any chance you can send an example of an image you tried?   
Since you said the other applications worked find, I assume you performed alignment prior to running inference, correct?

**Comment by brightmart** [comment]
Hi yuval-alaluf, 
Alignment is used before inference.

Input image:
![input_img_2 jpg](https://user-images.githubusercontent.com/19634224/100517094-4d49d480-31c3-11eb-8ac3-34a3c794007b.jpeg)

Output:
![b-output](https://user-images.githubusercontent.com/19634224/100517115-6ce0fd00-31c3-11eb-83f5-a296b0bd19d4.png)

**Comment by yuval-alaluf** [comment]
It appears that when you read the image, PIL automatically rotates the image. Therefore, when feeding the image to pSp, you are actually feeding the rotated image and getting an undesired result.  

I did some digging, and it appears that when a picture is taller than it is wide, PIL may automatically rotate the image. Feel free to read more about it here to find how to handle this case: 
https://stackoverflow.com/questions/4228530/pil-thumbnail-is-rotating-my-image

Also note that your input image is quite large (1079x1437) and therefore, the alignment process will not work. You should resize the image to a small size (e.g. 256x256) and try rerunning the inference notebook. 

After making these two changes, inference should work.

**Comment by brightmart** [comment]
Hi Yuval-alaluf,
Thanks for you quick reply. 
After resize the image to 256x256,  i got better results:
![result_resize_b](https://user-images.githubusercontent.com/19634224/100518926-a15ab600-31cf-11eb-916a-9f3ce1adc1d9.png)

By the way, which kinds of methods can be taken to achieve a better result?

**Comment by yuval-alaluf** [comment]
Looks better.  
Our toonify model was trained with no labeled data using only real face images. Therefore, like you said, the identity may not always be well-preserved. To achieve better results, you should consider training the toonify model using paired data.  
I also discussed training a toonify model here: 
https://github.com/eladrich/pixel2style2pixel/issues/39#issuecomment-728749239
I hope you find the recommendations useful.

**Comment by brightmart** [comment]
Thank you!
