### ISSUE TITLE
Latent representation of the encoded image

### ISSUE THREAD

**Issue by ahmetdadak** [eladrich/pixel2style2pixel#46]
Hello,
I am a newbie. How can I find the latent representation of the encoded image? I want to play around with it but I really don't know where to find it.

**Comment by yuval-alaluf** [comment]
Please see #36 where I explain how to extend `inference.py` to add support for saving the latent codes of the encoded images. You can then save these latent codes to use them elsewhere.

**Comment by ahmetdadak** [comment]
Thank you, I appreciate that.
