### ISSUE TITLE
dependency install issue

### ISSUE THREAD

**Issue by tomtomtong** [eladrich/pixel2style2pixel#47]
Hello. I just use the following command in Window 10 64bit home edition
**conda env create -f C:\Users\User\Downloads\pixel2style2pixel\environment\psp_env.yaml**

And I get the following error
**ResolvePackageNotFound:
  - ncurses==6.2=he6710b0_1
  - python==3.6.7=h0371630_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - readline==7.0=h7b6447c_5
  - sqlite==3.31.1=h62c20be_1
  - zlib==1.2.11=h7b6447c_3
  - libedit==3.1.20181209=hc058e9b_0
  - xz==5.2.5=h7b6447c_0
  - libffi==3.2.1=hd88cf55_4
  - ninja==1.10.0=hc9558a2_0
  - tk==8.6.8=hbc83047_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - openssl==1.1.1g=h516909a_0**

How would I solve this issue? Thank you for any reply.

**Comment by yuval-alaluf** [comment]
From what I can tell, the error indicates that you do not have openssl installed (or at least it is not in your %PATH%). Can you please verify this?

**Comment by tomtomtong** [comment]
Thank for your quick response. 
I try to move these packages under pip
But U get this error

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement xz==5.2.5=h7b6447c_0 (from -r C:\Users\User\Downloads\pixel2style2pixel\environment\condaenv.epffu2lb.requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for xz==5.2.5=h7b6447c_0 (from -r C:\Users\User\Downloads\pixel2style2pixel\environment\condaenv.epffu2lb.requirements.txt (line 1))

failed

CondaEnvException: Pip failed

**Comment by yuval-alaluf** [comment]
Since you are working on Windows and this seems to be an environment related issue, I feel like your best bet is to look into this issue through other forums that will probably be far more familiar with these types of issues.  
With that, our conda environment today has many unused dependencies. We will try making a cleaner conda environment which may help reduce the potential issues in the future. However, I am not sure exactly when we will get to doing this task.

**Comment by yuval-alaluf** [comment]
Although this may not necessarily help solve your issue above, please refer to the updated conda environment uploaded yesterday which can be found here: https://github.com/eladrich/pixel2style2pixel/commit/38300fae448a8cb4cc47694dce6cd6e61c3ba2ca 

I am closing this issue for now. Please feel free to reopen or open a new issue if needed.
