### ISSUE TITLE
Decreasing PSP model size with a stylegan2 model trained on smaller resolution

### ISSUE THREAD

**Issue by cyprian** [eladrich/pixel2style2pixel#52]
My goal is of optimization of the PSP model for much faster inference.
My logic is to use a stylegan2 model trained on a smaller resolution.

Initially I trained my PSP model using a stylegan2 model trained on 1024x1024 images.
Using that stylegan model the resulting PSP model has a size of 1.2 GB

Given I don't need a large output size of 1024x1024 I decided to train a stylegan on 256x256 image set
I am using that smaller stylgan model (256x256) to train a new PSP model.

My issue: 

The resulting PSP model trained with the Stylegan (256x256) is still 1.2 GB.
Shouldn't the PSP model size be smaller given I trained it with Stylegan(256x256) instead of Stylegan(1024x1024)?

My setup:
Both PSP models were trained on 256x256 datasets, the only difference is stylegan2 model
When I train the 256x256 PSP model I am using a checkpoint from my 1024x1024 PSP model.

**Comment by yuval-alaluf** [comment]
Yes. The model should be smaller. To try to find the problem, let's verify a few things: 
1. Did you change the following line to define a generator with size 256x256? 
https://github.com/eladrich/pixel2style2pixel/blob/38300fae448a8cb4cc47694dce6cd6e61c3ba2ca/models/psp.py#L28
That is, you should have something like `Generator(256, 512, 8)`. 
2. You said that to trained the 256x256 pSp model, you loaded your 1024x1024 checkpoint. When doing so, did you load just the encoder weights? Since you're using a different generator, I don't think you want (or can) load the decoder checkpoint:
https://github.com/eladrich/pixel2style2pixel/blob/38300fae448a8cb4cc47694dce6cd6e61c3ba2ca/models/psp.py#L47-L49
That is, you want to comment out line 49 above and replace it with the loading of your 256x256 StyleGAN.

**Comment by cyprian** [comment]
After implementing your recommended changes like below I get a size mismatch error.
There is a chance that my below code for loading weights of my own 256 stylegan is wrong.

```
	def load_weights(self):
		if self.opts.checkpoint_path is not None:
			print('Loading pSp from checkpoint: {}'.format(self.opts.checkpoint_path))

			encoder_ckpt = torch.load(self.opts.checkpoint_path, map_location='cpu')
			self.encoder.load_state_dict(get_keys(encoder_ckpt, 'encoder'), strict=True)
			#self.decoder.load_state_dict(get_keys(ckpt, 'decoder'), strict=True)

			#Load my stylegan2 256x256 decoder weights
			ckpt = torch.load(self.opts.stylegan_weights)
			self.decoder.load_state_dict(ckpt['g_ema'], strict=False)
			if self.opts.learn_in_w:
				self.__load_latent_avg(ckpt, repeat=1)
			else:
				self.__load_latent_avg(ckpt, repeat=18)

			#self.__load_latent_avg(ckpt)
```

I get the following size mismatch issue: 

```
Traceback (most recent call last):
  File "scripts/train.py", line 32, in <module>
    main()
  File "scripts/train.py", line 27, in main
    coach = Coach(opts)
  File "./training/coach.py", line 32, in __init__
    self.net = pSp(self.opts).to(self.device)
  File "./models/psp.py", line 31, in __init__
    self.load_weights()
  File "./models/psp.py", line 51, in load_weights
    self.decoder.load_state_dict(ckpt['g_ema'], strict=False)
  File "/home/paperspace/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
	size mismatch for convs.6.conv.weight: copying a param with shape torch.Size([1, 256, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 512, 512, 3, 3]).
	size mismatch for convs.6.activate.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for convs.7.conv.weight: copying a param with shape torch.Size([1, 256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 512, 512, 3, 3]).
	size mismatch for convs.7.conv.modulation.weight: copying a param with shape torch.Size([256, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for convs.7.conv.modulation.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for convs.7.activate.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for convs.8.conv.weight: copying a param with shape torch.Size([1, 128, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 256, 512, 3, 3]).
	size mismatch for convs.8.conv.modulation.weight: copying a param with shape torch.Size([256, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for convs.8.conv.modulation.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for convs.8.activate.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for convs.9.conv.weight: copying a param with shape torch.Size([1, 128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 256, 256, 3, 3]).
	size mismatch for convs.9.conv.modulation.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for convs.9.conv.modulation.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for convs.9.activate.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for convs.10.conv.weight: copying a param with shape torch.Size([1, 64, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 128, 256, 3, 3]).
	size mismatch for convs.10.conv.modulation.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for convs.10.conv.modulation.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for convs.10.activate.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for convs.11.conv.weight: copying a param with shape torch.Size([1, 64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 128, 128, 3, 3]).
	size mismatch for convs.11.conv.modulation.weight: copying a param with shape torch.Size([64, 512]) from checkpoint, the shape in current model is torch.Size([128, 512]).
	size mismatch for convs.11.conv.modulation.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for convs.11.activate.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for to_rgbs.3.conv.weight: copying a param with shape torch.Size([1, 3, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
	size mismatch for to_rgbs.3.conv.modulation.weight: copying a param with shape torch.Size([256, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for to_rgbs.3.conv.modulation.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for to_rgbs.4.conv.weight: copying a param with shape torch.Size([1, 3, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 256, 1, 1]).
	size mismatch for to_rgbs.4.conv.modulation.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for to_rgbs.4.conv.modulation.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for to_rgbs.5.conv.weight: copying a param with shape torch.Size([1, 3, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 128, 1, 1]).
	size mismatch for to_rgbs.5.conv.modulation.weight: copying a param with shape torch.Size([64, 512]) from checkpoint, the shape in current model is torch.Size([128, 512]).
	size mismatch for to_rgbs.5.conv.modulation.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
```

**Comment by justinpinkney** [comment]
One thing to note is that the vast majority of the size (~1gb) is for the encoder (iirc). The decoder even at 1024 is only just over 100mb, using a 256 output decoder makes very little difference to the overall size.

**Comment by yuval-alaluf** [comment]
So a few things: 
1. @justinpinkney is indeed correct that using a smaller generator will probably only save about 100MBs (from what I tested). And the visual quality you'll obtain will be substantially lower from my experience. 
2. If you still want to work with a 256x256 model, there are two things that I would try: 
    - There should be 14 latents instead of 18 latents (the number of latents is calculated by `log(image_size) * 2 - 2`. 
       (This shouldn't be causing the error, but just something to note)
    - The other thing that I could think about as something to check is the `channel_multiplier`. By default this is equal to 2. But perhaps your model uses a multiplier of 1? Indeed, it seems like the param channels in your checkpoint are half of the channels in the model's state dict.

**Comment by acc557** [comment]
Will apex  help in decreasing the model size in the memory?

**Comment by yuval-alaluf** [comment]
> Will apex help in decreasing the model size in the memory?

I haven't had a chance to work a lot with apex/amp, but from my understanding using amp should help reduce the model size and memory consumption during training.

**Comment by obravo7** [comment]
I had a similar request but instead of opening a new issue I thought I would comment it here since my question is essentially the same. 

Saw we have a stylegan2 model trained on a custom dataset, of which the resolution of the images was 512x512 (so the latent vector is expected to be (1x16x512)). When I use the pSp encoder, the resulting latent vector is always (18, 512). I tried making the changes listed above but the same error arises. also tried changing `self.style_count = 16` in: 

https://github.com/eladrich/pixel2style2pixel/blob/0730e33dc7f2aeafc67579c4e66dd7a5df0ceeb1/models/encoders/psp_encoders.py#L57

but no luck.

Any ideas?

**Comment by yuval-alaluf** [comment]
Hi @obravo7 , 
I believe you made the correct change in `psp_encoders.py`.  Are you by any chance using the flag `--start_from_latent_avg`?

**Comment by obravo7** [comment]
@yuval-alaluf 

So I found the issue:

For some reason I had to change this line:

https://github.com/eladrich/pixel2style2pixel/blob/master/models/psp.py#L48

to `self.encoder.load_state_dict(get_keys(encoder_ckpt, 'encoder'), strict=False)`

And it gave me the expected results. Thank you for your prompt response.

**Comment by Mo-Irene** [comment]
@cyprian Hello, sorry to bother you, I have the same problem as you, how did you solve it? I'm also training my own 256*256 generator and trying to use it with --stylegan_weights. If you can give me some advice, it will help me a lot.
