### ISSUE TITLE
About the generator

### ISSUE THREAD

**Issue by wty-ustc** [eladrich/pixel2style2pixel#56]
Dear Sir:
   I have read you code, it's really a nice job! I find you used StyleGANv2 as your generator, did you attempt to use StyleGANv1 as the decoder and which one performed best for inversion?

**Comment by yuval-alaluf** [comment]
Hi, we did not try out StyleGAN1 in our experiments. However, if you wish to do so, this is possible by changing the `Generator()` object from a StyleGAN2 model to a StyleGAN1 model.

**Comment by wty-ustc** [comment]
Okay! Thank you!
