### ISSUE TITLE
About start_from_latent_avg

### ISSUE THREAD

**Issue by wty-ustc** [eladrich/pixel2style2pixel#57]
Dear Sir:
  I notice there is a latent_avg(512) in your stylegan2-ffhq-config-f.pt, and I am wondering if it is inherent in the official pre-trained 
tensorflow model or if you added it yourself in order for the encoder to learn the residual. Looking forward to your reply!

**Comment by yuval-alaluf** [comment]
Hi, The average latent vector is saved as part of the official StyleGAN model. We did not add it ourselves.

**Comment by wty-ustc** [comment]
Thank you!
