### ISSUE TITLE
Different PSP Encoder results comparison

### ISSUE THREAD

**Issue by XD666** [eladrich/pixel2style2pixel#59]
Hi there,

When I dive into the psp_encoders,  I found there are three encoders provided. I am just curious which shots the best results? 

It looks to me that both BackboneEncoderUsingLastLayerIntoW and BackboneEncoderUsingLastLayerIntoWPlus don't apply fully convolutional layers but only take features from Arcface? 

Can you also explain a little the differences between these three? For I don't find any descriptions regarding which one should apply for these?

Many thanks,

**Comment by yuval-alaluf** [comment]
The official pSp architecture with the FPN backbone is given by `GradualStyleEncoder`.
For the explanations of the three architectures please refer to the ablation study in the paper for an explanation of their architectures.
As we show, the FPN-based architecture achieves the best results of the three.
