### ISSUE TITLE
how to test toonify

### ISSUE THREAD

**Issue by ChengBinJin** [eladrich/pixel2style2pixel#6]
Thank you for your great work and share the codes.
Can you supply a brief explanation about how to test the Toonify?

**Comment by yuval-alaluf** [comment]
Hi @ChengBinJin, 
First, notice that with this repo we provide a Google Colab notebook that takes you through the inference flow of all our applications. At a high level, for each desired application, the notebook will download the relevant pre-trained model and apply the model on a given input image. Therefore, I would recommend starting with the inference notebook.  

Other than this notebook, you can download all our pretrained models using the links provided in the README. Once you have downloaded the model, you can use the script `inference.py` to apply the model on a desired set of images. The inference script receives multiple parameters, the most import of which are:
1. the model path (`--checkpoint_path`)
2. the path to a directory holding the images you wish to perform inference (`--data_path`)
3. the output path of where to save the results (`--exp_dir`)

Finally, note that like all StyleGAN models, the inputs should be aligned. To assist with this, we provide an alignment script in `scripts/align_all_parallel.py` that you can use if needed.

**Comment by ChengBinJin** [comment]
@yuval-alaluf 
Thank you for your prompt reply, and I found the notebook that you said and I figured out how to use it now. Thank you again!
