### ISSUE TITLE
segmentation generation test

### ISSUE THREAD

**Issue by diaodeyi** [eladrich/pixel2style2pixel#62]
File "./datasets/augmentations.py", line 27, in __call__
    one_hot = self.onehot_initialization(img)
  File "./datasets/augmentations.py", line 17, in onehot_initialization
    out[self.__all_idx(a, axis=2)] = 1
IndexError: index 32 is out of bounds for axis 2 with size 19

there is some issures with the segmentation generation test.
with  inference orders:
CUDA_VISIBLE_DEVICES=0 python scripts/inference.py \
--exp_dir=./outputs_seg_test_FFHQ1024 \
--checkpoint_path=./experiment/checkpoint/psp_celebs_seg_to_face.pt \
--data_path=/data1/facedata/segdemo \
--test_batch_size=4 \
--test_workers=4 \
--couple_outputs \
--resize_outputs \
--latent_mask=8,9,10,11,12,13,14,15,16,17

**Comment by yuval-alaluf** [comment]
Our segmentation-to-image application is trained using the CelebAMask-HQ dataset, which contains 19 semantic labels. How does your data in the given `data_path` look like? Is this data given in the same format with the same 19 classes?

**Comment by diaodeyi** [comment]
i use the same dataset(celebreMaskHQ) to test with your trained weight, but can't run

**Comment by diaodeyi** [comment]
By the way , the class in celebAmaskHQ is 15 , doesn't it?

**Comment by yuval-alaluf** [comment]
I just ran a test using the Google Colab notebook in this repo and everything seems to be working fine with the code itself. Do you want to send an example of an image you're trying to run on?

**Comment by diaodeyi** [comment]
thank you , My problem is solved
