### ISSUE TITLE
colab error 

### ISSUE THREAD

**Issue by r00tsyst3m** [eladrich/pixel2style2pixel#63]
i alr test sketch to face and works normally but when try seg to face got this error on step 6

IndexError Traceback (most recent call last)
in ()
1 img_transforms = EXPERIMENT_ARGS['transform']
----> 2 transformed_image = img_transforms(input_image)

2 frames
/content/pixel2style2pixel/datasets/augmentations.py in onehot_initialization(self, a)
15 self.n_classes = len(np.unique(a))
16 out = np.zeros(a.shape + (self.n_classes, ), dtype=int)
---> 17 out[self.__all_idx(a, axis=2)] = 1
18 return out
19

IndexError: index 253 is out of bounds for axis 2 with size 19

**Comment by yuval-alaluf** [comment]
Is the example image you're using an image of a segmentation map? Our segmentation-to-image application is trained using the CelebAMask-HQ dataset, which contains 19 semantic labels. You need to make sure your data is in the same format.

**Comment by r00tsyst3m** [comment]
> Is the example image you're using an image of a segmentation map? Our segmentation-to-image application is trained using the CelebAMask-HQ dataset, which contains 19 semantic labels. You need to make sure your data is in the same format.

im using anime character as image source

**Comment by yuval-alaluf** [comment]
For the segmentation-to-image task, you need to input a **segmentation map** following the same labeling scheme as CelebAMask-HQ . Notice that the segmentation-to-image task takes an input segmentation mask and outputs an RGB image. Therefore, inputing an anime image does not make sense in this case.
