### ISSUE TITLE
Generating images from random latent vectors

### ISSUE THREAD

**Issue by genawass** [eladrich/pixel2style2pixel#64]
Hi, I want to generate images from random latent vectors as is performed in stylegan2, without the encoding step. How it can be done with pSp? Thanks

**Comment by yuval-alaluf** [comment]
Please see issue https://github.com/eladrich/pixel2style2pixel/issues/12

**Comment by genawass** [comment]
> Please see issue #12

Yeah, I see and if I want to use previously projected latent vectors - they are 8x512 and not 1x512 as appear in:

**Comment by yuval-alaluf** [comment]
If you mean `18x512`, then this is similar to simply calling the `forward` function of pSp without passing through `self.encoder` first. Then, the codes should simply be passed through `self.decoder` to generate the image.

**Comment by genawass** [comment]
OK, got it, thanks.
