### ISSUE TITLE
train dataset for the inversion task

### ISSUE THREAD

**Issue by wty-ustc** [eladrich/pixel2style2pixel#65]
In your paper, you wrote as follow
![image](https://user-images.githubusercontent.com/55389940/103480174-b699b480-4e0d-11eb-9c80-81bc0848f6a4.png)
So your training dataset for inversion is 70000FFHQ + 24000CelebA-HQ, resulting in about 94000 images, right?

**Comment by yuval-alaluf** [comment]
Good question. The sentence is confusing. The inversion task uses **only** the FFHQ dataset so a total of 70,000 images are used for the inversion task.

**Comment by wty-ustc** [comment]
Thank you!



---Original---
