### ISSUE TITLE
Continue training a custom dataset model after pause

### ISSUE THREAD

**Issue by hs1227** [eladrich/pixel2style2pixel#67]
I am training my custom model using a custom dataset.
Now the iteration is about 30000. 
But, I want to add more dataset images. Then, I will stop training to add them.
Is there any way for me to **pause training the network**? 
Plus, Is there any way to **continue training using the last pre-trained model(best_model.pt)** after adding the dataset?

**Comment by yuval-alaluf** [comment]
Yes. If you wish, you may stop training, add more data, and continue training. To pause training, you can simply stop the kill the training process (just make sure you saved a checkpoint). After you added the data, you can resume training using the saved checkpoint by adding the flag `--checkpoint_path`.

**Comment by hs1227** [comment]
> Yes. If you wish, you may stop training, add more data, and continue training. To pause training, you can simply stop the kill the training process (just make sure you saved a checkpoint). After you added the data, you can resume training using the saved checkpoint by adding the flag `--checkpoint_path`.

**Comment by hs1227** [comment]
> 예. 원하는 경우 훈련을 중지하고 데이터를 더 추가하고 훈련을 계속할 수 있습니다. 훈련을 일시 중지하려면 훈련 프로세스를 중지하기 만하면됩니다 (체크 포인트를 저장했는지 확인). 데이터를 추가 한 후 플래그를 추가하여 저장된 체크 포인트를 사용하여 훈련을 재개 할 수 있습니다 `--checkpoint_path`.

Thank you for your comment :)
