### ISSUE TITLE
About Conditional Image Synthesis

### ISSUE THREAD

**Issue by pnbao** [eladrich/pixel2style2pixel#74]
Can we use Conditional Image Synthesis technique to mix styles of 3 different images (A, B, C)?
For example, with latent_mask=8,9,10,11,12,13,14,15,16,17 we can mix styles like

```
codes[:, 8] = imagesA[:, 8]
codes[:, 9] = imagesB[:, 9]
codes[:, 10] = imagesC[:, 10]
codes[:, 11] = imagesA[:, 11]
codes[:, 12] = imagesB[:, 12]
codes[:, 13] = imagesC[:, 13]
codes[:, 14] = imagesA[:, 14]
...
```
in this snippet?
https://github.com/eladrich/pixel2style2pixel/blob/2fba1b0b4d22de8c71188481be3edccf1413ee94/models/psp.py#L80-L88

**Comment by yuval-alaluf** [comment]
Sure! While we only performing using a single image (whose style vectors are passed as `inject_latents`), you can extend the `forward` call of pSp to receive multiple latents to inject. Then in the code snippet you linked you can add the functionality to perform the mixing with the multiple latents.
