### ISSUE TITLE
Question about training the encoder

### ISSUE THREAD

**Issue by xilongzhou** [eladrich/pixel2style2pixel#76]
Dear authors:

Your work is very interesting and I like it very much! Here I have a small question about training the encoder:

In the psp.y L31: self.load_weights() I realize that you load a pretrained encoder 'ir_se50' as initialization and then train the encoder. In the implementation section of the paper, you also mentioned that you use ResNet-IR architecture from the pretrained backbone network on the face recognition dataset. So basically, you use a pretrained backbone architecture as encoder and then fine-tune this encoder together with a fixed styleGAN, am I correct?

I am asking this because I am borrow your idea for another problem, not related to face dataset. I tried using an encoder without pretrained model initialization and the training will fail. I just want to double check if this may be the reason.

Thanks!

**Comment by yuval-alaluf** [comment]
Hi @xilongzhou ,
We're happy to hear about your interested in our work! 
Regarding your question, you are indeed correct that the pSp encoder uses a ResNet-IR backbone that is pre-trained on a face recognition dataset.  
Note that we do in fact fine-tune the encoder during training, but the StyleGAN generator remains fixed throughout training. 
Regarding your second question, I can offer two things you can check: 
- Keep the encoder pre-trained on the faces dataset. Even though you're working on a different domain, the features learned by the pre-trained faces model can still be of use. 
- Change the encoder architecture from a ResNet-IR backbone to, say, a ResNet-50 backbone, which can then use weights pre-trained on ImageNet for example. 
    - This second change entails a bit more work than the first option, but is definitely feasible.

**Comment by xilongzhou** [comment]
Dear Yuval,

Thank you very much for your quick response and suggestion! I will try this to see how it works
