### ISSUE TITLE
Toonify the output more

### ISSUE THREAD

**Issue by cvmlddev** [eladrich/pixel2style2pixel#83]
Hi,
I trained pixel2style2pixel on paired toon dataset(Dataset created using [stylegan2](https://www.justinpinkney.com/toonify-yourself/), around 8000 pairs
Trained psp model using following hyperparameters
`lpips_lambda=0.8 ,  l2_lambda=1,  id_lambda=1 , w_norm_lambda=0.025 ,stylegan_weights =pretrained_models/ffhq_cartoon_blended.pt`

I am actually getting pretty good results
![5002_01](https://user-images.githubusercontent.com/78845460/107499901-876c2500-6bbb-11eb-983b-be2089da5e19.png)

What I would like to have is more toon effect, As in, The output looks too much like the source. 
Was wondering which hyperparameter could help me achieve this?
Thanks

**Comment by yuval-alaluf** [comment]
You could try decreasing the L2 and LPIPS losses a bit. Maybe by doing so, the network will try less to preserve the fine details (e.g. eye size). However, we haven't really tried this ourselves so I am not sure how much of an effect this will have. 

Also, while I don't really know how your paired data looks, the results you'll get with pSp are heavily influenced by the toon data you use for training. If your toon training data does not have a large toon effect, the results you'll get during inference will be similar. 

Overall, however, I think your results look very good! 💪

**Comment by mohammad-rj** [comment]
can u share the colab, to crate toonify look exactly like the photo you shared please

**Comment by watertianyi** [comment]
> 嗨， 我在成对的卡通数据集上训练了 pixel2style2pixel（使用[stylegan2](https://www.justinpinkney.com/toonify-yourself/)创建的数据集，大约 8000 对使用以下超参数训练的 psp 模型 `lpips_lambda=0.8 , l2_lambda=1, id_lambda=1 , w_norm_lambda=0.025 ,stylegan_weights =pretrained_models/ffhq_cartoon_blended.pt`
> 
> 我实际上得到了很好的结果 ![5002_01](https://user-images.githubusercontent.com/78845460/107499901-876c2500-6bbb-11eb-983b-be2089da5e19.png)
> 
> 我想要的是更多的香椿效果，例如，输出看起来太像源了。 想知道哪个超参数可以帮助我实现这一目标？ 谢谢

How did your paired data set come about?

**Comment by xuguozhi** [comment]
how about the paired data details?
