### ISSUE TITLE
Strange results

### ISSUE THREAD

**Issue by accountvb** [eladrich/pixel2style2pixel#84]
Hello, thanks to your help i could run it on my computer after many problems (except toonfiy for me),

unfortunately i keep getting strange results from it

here is some exemples

**StyleGAN Encoding**

https://i.postimg.cc/pVfQNSzP/b7307251-1fc1-11eb-b8ad-02fe89184577.jpg

**Face Frontalization**
https://i.postimg.cc/bv408cmw/200210124007-trump-wh-lawn-0207-restricted-super-tease.jpg
https://i.postimg.cc/Yqt6txzY/Trump-prayer-rtr-img.jpg

can you confirm me please, if it is a normal result or not!

Thanks

**Comment by yuval-alaluf** [comment]
You're getting these results because your data is not properly aligned. 
We provide an alignment script for doing so. After running alignment, rerun the inference script with the aligned images.

**Comment by LightingMc** [comment]
Do you need to align even with the FFHQ-HD dataset?

**Comment by yuval-alaluf** [comment]
@LightingMc , are you asking if you need to align the FFHQ dataset before training/inference? If so, the dataset should be pre-aligned so there is no need.
