### ISSUE TITLE
About the stylegan2

### ISSUE THREAD

**Issue by diaodeyi** [eladrich/pixel2style2pixel#87]
Is this pytorch version of the styleGAN2 implemented by the group of PSP？

**Comment by yuval-alaluf** [comment]
The StyleGAN2 implementation in this repo is taken from rosinality:
https://github.com/rosinality/stylegan2-pytorch

**Comment by diaodeyi** [comment]
ok ，thank you

**Comment by LightingMc** [comment]
so the code is using StyleGan2 by default?

**Comment by yuval-alaluf** [comment]
> so the code is using StyleGan2 by default?

Yes
