### ISSUE TITLE
Alternative use of this project

### ISSUE THREAD

**Issue by geekmangnu** [eladrich/pixel2style2pixel#88]
Hi, sorry for asking a naive question I am still learning GAN. Can this project used for garment virtual try-on? or pose transfer? Projects like [vogue](https://vogue-try-on.github.io/ ) feeds the pose heatmaps to stylegan2 instead of feeding constant. I am trying to accomplish garment virtual try-on, have read lots of papers but confused where to start.Using stylegan is not common in this area only few started to using it (like VOGUE and [Styleposegan](http://gvv.mpi-inf.mpg.de/projects/Styleposegan/)) and seems to have good results. Can inversion also change clothes to a target clothe? I am just asking it not to direct myself wrong way.  I know you are not working on specifically  this narrow subject but probably you have a clear idea that if it can be used for it or not. If you have any recommendation on this area very appreciated. Thank you.

**Comment by yuval-alaluf** [comment]
Hi @geekmangnu , 
It's an interesting question. While I can't say for certain if pSp can be used for solving tasks such as garment try-on, it would definitely be interesting to try. However, the first step I would take is making sure that you are able to train a StyleGAN generator that is able to accurate generate high-quality images like those shown in the links you shared. Once you believe you have a high-quality GAN then you can start exploring various potential research directions such as those you mentioned.

**Comment by geekmangnu** [comment]
Thank you @yuval-alaluf  for the feedback.
