### ISSUE TITLE
Face frontalization

### ISSUE THREAD

**Issue by diaodeyi** [eladrich/pixel2style2pixel#89]
The paper says "First, we randomly flip the target image, thus creating inconsistencies in terms of pose compared to the input image."  The " random " means there are some target image same as input(doesn't flip)?

**Comment by yuval-alaluf** [comment]
Exactly. Some times, the input and target images are identical and sometimes they are the flipped version of each other.

**Comment by diaodeyi** [comment]
This comes from experiment result ？I mean the reason for this design.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuval-alaluf&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月2日(星期二) 晚上10:58
收件人:&nbsp;&quot;eladrich/pixel2style2pixel&quot;<pixel2style2pixel@noreply.github.com&gt;;
抄送:&nbsp;&quot;jeason&quot;<1034242067@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eladrich/pixel2style2pixel] Face frontalization (#89)

**Comment by yuval-alaluf** [comment]
The reason for this design is because if: 
1. (roughly) half the time, the target image is the flipped version of the input image and 
2. (roughly) half the time, the target image is the input image, 
then the output image that will minimize the loss is the frontalized version of the input image.
