### ISSUE TITLE
Downloading models 

### ISSUE THREAD

**Issue by 7khalil** [eladrich/pixel2style2pixel#9]
I have permission issue downloading pre-trained models from provided google drive links

**Comment by yuval-alaluf** [comment]
Hi @7khalil ,
Using the links we provided in the repo you should be able to download the models either manually or via wget.  
Several questions: 
1. What model are you trying to download? 
2. How are you trying to download the model?
2. What error are you getting?

**Comment by 7khalil** [comment]
1. I'm trying to download "StyleGAN Inversion" model for image encoding.
2. I'm trying to download the model via gdown command. but it **worked** after several tries.
3. The type of error I got is "permission privilege".

I have another question :
Could you provide more explanation about tooninfication process, are you using "StyleGAN Inversion" for encoding images into latent space of "StyleGAN FFHQ" or "StyleGAN with tooninification, i.e the blended network"

**Comment by yuval-alaluf** [comment]
Regarding the "permission privilege", I do not use gdown personally so I am not sure what could have caused the issue, but I am happy to hear you got it working.  

Regarding the toonification process. Yes, we train using the "StyleGAN Inversion" task (i.e. `--data_type=ffhq_encode`) and use the "toonified" StyleGAN model as the generator (by setting `--stylegan_weights` to the path containing the toonified `.pt` model file.). That is, we use the bleneded toonified network as our generator.

**Comment by 7khalil** [comment]
Ok, thanks @yuval-alaluf .
