### ISSUE TITLE
Could you provide segmentation and sketch dataset to me?

### ISSUE THREAD

**Issue by wty-ustc** [eladrich/pixel2style2pixel#90]
The two applications seems very interesting, however I couldn't find how to generate these datasets so that I can't train these two models. Could you provide me these two datasets or tell me the methods to generate these datasets?

**Comment by yuval-alaluf** [comment]
Please see issue #42 for details regarding the datasets used in the work (including the segmentation data)
Regarding the sketch dataset, you can generate this yourself from the FFHQ/CelebA-HQ datasets using the provided `generate_sketch_data.py` script.
