### ISSUE TITLE
Inconsistent results of the DeepFaceDrawing samples

### ISSUE THREAD

**Issue by tennysonbc** [eladrich/pixel2style2pixel#92]
Hello，
I used the pretrained sketch to face image model to generate face image on my server.
However the output of DeepFaceDrawing samples are inconsistent with the results from your paper.
Do you know where the problem is?
![sample_1](https://user-images.githubusercontent.com/53414433/110199559-e0199f80-7e93-11eb-9f00-86ee9bbd4930.jpg)
![sample_2](https://user-images.githubusercontent.com/53414433/110199566-e90a7100-7e93-11eb-92e6-3f144be5849f.jpg)
![sample_3](https://user-images.githubusercontent.com/53414433/110199569-f162ac00-7e93-11eb-80ab-5e8d69b43048.jpg)

**Comment by yuval-alaluf** [comment]
The results you obtained above seem to be directly from the output. In the paper, we performed style mixing on the outputs using randomly drawn w latents  in order to show multi-modal results. Therefore, the paper contains much more colorful images thanks to the style mixing.

**Comment by tennysonbc** [comment]
Thanks a lot，I will check it again.

**Comment by tennysonbc** [comment]
Thanks, I will try again.
