### ISSUE TITLE
Train on my own in-domain data

### ISSUE THREAD

**Issue by tearscoco** [eladrich/pixel2style2pixel#93]
Hi guys,

Really impressive work done there!

I am wondering if I want to train on my own in-domain data other than those used in your work, should I start training a StyleGAN model using my data first? It seems that PSP work relies on a pre-trained StyleGAN model trained with the same domain data.

Really appreciate it if you could give some instructions here. Thanks！

**Comment by yuval-alaluf** [comment]
Yes, since pSp operates on a pre-trained StyleGAN, if you want to train pSp on your own domain, you need to start off by training your own StyleGAN generator trained on similar data. 
Thanks to recent works such as StyleGAN-ADA, this should be possible with only a few thousand images.

**Comment by jlnhlfan** [comment]
I have a Mac, but it uses an Intel chip.
I have a computer with an nVidia chip, but it is a Windows computer.
This, the only way I can use this would be through the Colab project. This leads to yet another problem.

Define Inference Parameters This step is where Colab craps on itself, as it cannot define anything resembling parameters. When I try to finish the step, an error is created. It reads: Pretrained model was unable to be downlaoded correctly!

Is this a problem with how I’m doing things, or is it completely normal?

**Comment by yuval-alaluf** [comment]
> Define Inference Parameters
> This step is where Colab craps on itself, as it cannot define anything resembling parameters. When I try to finish the step, an error is created. It reads: Pretrained model was unable to be downlaoded correctly!
> 
> Is this a problem with how I’m doing things, or is it completely normal?

It seems like you were unable to download the pre-trained model correctly. What was the size of the file you got? Please note the comment we wrote in the notebook: 
```
We need to verify that the model was downloaded correctly. All of our models should weigh approximately 1.12GB.
Note that if the file weighs several KBs, you most likely encounter a "quota exceeded" error from Google Drive. 
In that case, you should try downloading the model again after a few hours.
```

**Comment by jlnhlfan** [comment]
I don’t remember it ever downloading.

**Comment by yuval-alaluf** [comment]
> I don’t remember it ever downloading.

Ok, so please make sure the model is downloaded correctly and saved to the `pretrained_models` directory.
