### ISSUE TITLE
Analyze results

### ISSUE THREAD

**Issue by liuliuliu11** [eladrich/pixel2style2pixel#94]
Hello, thank you for sharing your work. In my work, I want to train my own encoder, using part of FFHQ data (about 25000 sheets) as input, without upsampling processing (that is: the upsampling factor is 1 ) Because the GPU capacity of the hardware device is 12209MiB, set batch=4. The styleGAN model is downloaded directly from the provided link. After 8 epochs, the verification result is shown in the figure below. Could you help to analyze the problem?
![0000_50000](https://user-images.githubusercontent.com/41572695/110270688-525bc280-8001-11eb-8341-e9c56e34c8d1.jpg)

**Comment by yuval-alaluf** [comment]
Hi @liuliuliu11 
Can you please clarify what you mean by `the upsampling factor is 1 `? Also, what do you mean by 8 epochs? Is that 50,000 steps?  In any case, please provide the parameters you used for training to provide some more details.

**Comment by liuliuliu11** [comment]
Sorry, I didn’t describe the problem clearly before. When applied to the super-resolution task, I want to train my own pSp model with the help of the provided StyleGAN model pretrained on FFHQ taken from rosinality with 1024x1024 output resolution. The parameter values are all using default values, except for the following changes : 
workers=8;
batch_size=8;
test_batch=4;
test_workers=4;
resize_factors=1.
after 50000 steps, the verification result is as mentioned before. Looking forward to your reply as soon as possible~
![0000_50000](https://user-images.githubusercontent.com/41572695/110285333-1420cc00-801e-11eb-9481-3e3f18215d2c.jpg)

**Comment by yuval-alaluf** [comment]
Can you explain why you are trying to train a super resolution model using only a resize factor of 1? It seems like you would be better of using the `ffhq_encode` settings in this case.

**Comment by liuliuliu11** [comment]
Under the psp framework, both stylegan and encoder are derived from the ffhq data set, and only set resize factor = 1 for detection encoder whether an original image(Without resizing) can be encoded into a hidden code, and then generate the corresponding high-definition image by stylegan. If successful, i can further set the resize factor = other values.

**Comment by yuval-alaluf** [comment]
If you want to encode images into the latent space, you should use the `ffhq_encode` experiment. If you wish to perform super resolution on **down-sampled** images, you should use the `super_resolution` experiment.

**Comment by liuliuliu11** [comment]
ffhq_encode should be part of super_resolution from the code point of view? I know that low-resolution images are input and high-resolution images are output in super-segmentation（SR） tasks . I think this way: if the SR experiment cannot generate a high-resolution image from an image that has not been resized（resize factor=1）, then when the resize factor is 2, 4, 8, 16, it will be more difficult! Please give suggestions~ thanks

**Comment by yuval-alaluf** [comment]
Yes, but to make sure there are no other issues, you should use `ffhq_encode` to ensure that you are able to reconstruct the input images. Once you are able to do this successfully, then you can move on to focusing on super resolution.
